### ISSUE TITLE
insert drawing not shown a results

### ISSUE THREAD

**Issue by xyont** [Proektsoftbg/Calcpad#1]
i'm using latest versions (v5.6.1) in learning step of Calcpad to migrates. All equations, calculation and branching is working properly except for drawing.

there's shown no result even a simple example from insert menus, drawing and line. it display as in code text formatted not a drawing i expected.

could you reproduce my problems?

**Comment by Proektsoftbg** [comment]
Hi xyont, 

Thank you for your feedback! Can you please share your code? You need to insert the drawing first. Then all graphic elements must go inside the <svg> ...</svg> tag. If you are not familiar with SVG, there is a great tutorial here: [https://www.w3schools.com/graphics/svg_intro.asp](https://www.w3schools.com/graphics/svg_intro.asp).

It is also important to have this #val keyword before the drawing. It suppresses the equations and shows only results as numbers. Please check the example bellow:

![изображение](https://user-images.githubusercontent.com/90918363/153092290-f3f447d5-7f97-4cfc-990f-c7e4a37624d9.png)

By using variables in coordinates, you can make your drawings dynamic - it will change each time you change the input data and re-calculate. I have some boilerplates for drawing cross sections with dimensions and even a complete retaining wall. I can share them as well. :)

![изображение](https://user-images.githubusercontent.com/90918363/153093428-2af7f25f-4e4f-4f12-91ef-161a8723e3d3.png)

**Comment by xyont** [comment]
thanks also for response back and hints. regarding the code i failed before, is a click based on menus only. look up to your code were succeed to display the drawings, cause of my previous step did not include svg viewbox. now it's working properly, provide default setting of viewbox make apps become easy for new user.

btw, nice example on retaining wall example. ability to export the drawing in DXF file type formats could be a great step and useful features.

**Comment by Proektsoftbg** [comment]
Great! I am glad it worked. About the DXF export, it is a nice suggestion. Thank you!
