### ISSUE TITLE
rewriting variable units

### ISSUE THREAD

**Issue by xyont** [Proektsoftbg/Calcpad#10]
Calcpad has unique feature in rewriting variable at calculation. however, some US units not displayed as original units.

![2022-02-25 10_45_44-Calcpad 5 6 2](https://user-images.githubusercontent.com/72367311/155650135-1e80a390-5967-4c66-8445-6e05ddb9d918.png)

as can be seen, the units of 'A_se' variable is displayed as original, but 'f_uta' does not.

**Comment by Proektsoftbg** [comment]
Yes, I can see that. Thank you! This is a bug. I have an idea why this is happening. Please, give me 1-2 days and I will fix it. :)

**Comment by xyont** [comment]
right, Calcpad getting better. none catch the unique feature to rewrites variable and the units.
