### ISSUE TITLE
Is there a portable version available?

### ISSUE THREAD

**Issue by coreur** [Proektsoftbg/Calcpad#103]
Calcpad software has brought me a lot of convenience. I want to install calcpad on my work computer, but my work computer has no administrator rights and no network. 
Can you provide a portable version that can be free of installation and administrator rights?

**Comment by Proektsoftbg** [comment]
OK. I will try and will come back soon. :)

**Comment by Proektsoftbg** [comment]
Hi,

I tried to publish a portable version. You can download it and try from here:

https://github.com/Proektsoftbg/Calcpad/blob/main/Setup/calcpad-portable-5.8.9.exe

It is a self-extracting archive. Extract it somewhere on your computer and click Calcpad.application. If nothing happens, try setup.exe. Please, share your experience after.

**Comment by coreur** [comment]
> Hi,
> 
> I tried to publish a portable version. You can download and try it from here:
> 
> https://github.com/Proektsoftbg/Calcpad/blob/main/Setup/calcpad-portable-5.8.9.exe
> 
> It is a self-extracting archive. Extract it somewhere on your computer and click Calcpad.application. If nothing happens, try setup.exe. Please, share your experience after.

----

It works, thank you.
