### ISSUE TITLE
Symbol ‰

### ISSUE THREAD

**Issue by hildebrandopsj** [Proektsoftbg/Calcpad#110]
Hi @Proektsoftbg we have the option to use ‰ symbol like a unit? It's very convenient when we work with strains

**Comment by Proektsoftbg** [comment]
Currently it is not supported, but it is easy to add. I will consider it for the next version. :)
In the same was maybe % can be also a unit, but I shoud think about what to do with % operator.

**Comment by Proektsoftbg** [comment]
It was added in the lates version, together with % units:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.9.8
