### ISSUE TITLE
Question about problem with Mathcad and NET 7.0

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#114]
It's not a bug with Calcpad, just question.

@Proektsoftbg 
Hello, Ned, I see, you have Mathcad Prime installed. May be you help me with it:
https://community.ptc.com/t5/Mathcad/Copy-Paste-issue-with-MathCAD-8-0/m-p/845725#M204261

Ho to reproduce Mathcad problem:
- create a text field (Ctl+T), enter the text;
- enter the formula (Ctrl+Shift+M);
- select the text (Ctrl+C);
- paste the text - it is inserted without a formula (but if you copy only the formula, then it's copied correctly).

Strange things:
- The bug remains after NET 7.0 uninstalling. But I tried several times to reset windows 10 and after it bug is disapeared. And bug bring back every time after NET 7.0 installing and computer rebooting.
- All others clipboard operations works correctly - only pasting text+formula into text area works incorrectly.

**Question**: Have anybody this bug Mathcad Prime too? It's appeared about a month ago.

**Comment by Proektsoftbg** [comment]
OK. It is on the other computer so, I will have a try later in the evening.

If the problem is only with .NET 7, I can easily revert Calcpad back to .NET 6 and provide a special package.
So, far I did not implement any new language features. I only solved algorithmic, design and architectural problems (in terms of software, not construction). :) In fact, .NET 7 brings some performance benefits, but I can say that they are less than 5% for app like Calcpad.

**Comment by cser** [comment]
Returning to NET 6.0 will be the solution to the problem if it is in NET.

But I still have to deal with NET 7.0. I can't reset all applications at work. It only worked at home.

Ideally, we need to get NET developers to release a fix (or workaround instructions).

That is, I need more information - so I'm waiting for a message from you - do you have bug or not with Mathcad Prime

**Comment by Proektsoftbg** [comment]
Hi, I tried several times, but I cannot reproduce the problem on my side. I have .NET 7, but it copies normally each time.

![image](https://user-images.githubusercontent.com/90918363/215273859-401ed8fa-93a9-46bc-9704-20f1b4f927ec.png)

Did you try to download and reinstall MathCAD again?

**Comment by cser** [comment]
Thanks! This is some kind of information. I'll write later what happened.

**Comment by cser** [comment]
@Proektsoftbg may be problem in windows 10, do you use windows 11?

**Comment by Proektsoftbg** [comment]
@cser. No, I am still with Windows 10. And I will be as long as possible. ;)

**Comment by cser** [comment]
Yes, I was wrong, It's not .NET 7.0. I reset my win 10 again yesterday without NET 7.0 installing and bug is appeared again. Сolleagues also have it. It's Microsoft update most likely.

**Comment by Proektsoftbg** [comment]
Thank you! This is useful information. You'd better bring this to the attention of the MathCAD support team and they could possibly find a workaround.

**Comment by cser** [comment]
People already done it:
https://community.ptc.com/t5/Mathcad/Copy-Paste-issue-with-MathCAD-8-0/m-p/845725#M204261
No effect yet - well, OK.

**Comment by cser** [comment]
After all, it was a problem with .NET 4.8 security update, and now instructions to fix it are published:
https://support.microsoft.com/en-gb/topic/kb5022083-change-in-how-wpf-based-applications-render-xps-documents-a4ae4fa4-bc58-4c37-acdd-5eebc4e34556
