### ISSUE TITLE
problem of #input 

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#115]
If you use Folded div Html syntax together with #input, then the notice "Paused! Press F5 to continue or Esc to cancel" always turn up at the end of th output windows, this is not so convient. Because it need the user to click the folded part to find where the input blanket is.

I suggest that the notice come along with the input blanket, where it is folded, the unfolding could be triggered automatically.

**Comment by Proektsoftbg** [comment]
Hi @idealkindom 

Thank you for your feedback. Folding is an Html/CSS feature that is not processed by Calcpad, but the browser that renders the output. So, it is almost impossible for Calcpad to automatically synchronize both. This up to the worksheet developer.

In general, it is not good to brake inside unclosed tags. If you break inside a folded div, the end tag is not rendered yet. So, it folds everything down to the end of the entire Html. So, plan your worksheets structure in a way that breaks do not occur inside tables, folded divs or any other Html elements.

**Comment by Proektsoftbg** [comment]
BTW. I have idea for a hack, in case you cannot figure out how to re-organize the worksheet. Just warp the #input into a div with position that will take it out of the fold, like:
```
'<div style="position:absolute; top:100px;"
#input
'</div>
```
Since Calcpad renders the message where #input occurs, it must fall inside the div.

**Comment by idealkindom** [comment]
> BTW. I have idea for a hack, in case you cannot figure out how to re-organize the worksheet. Just warp the #input into a div with position that will take it out of the fold, like:
> 
> ```
> '<div style="position:absolute; top:100px;"
> #input
> '</div>
> ```
> 
> Since Calcpad renders the message where #input occurs, it must fall inside the div.

That's a.good method. However, if I use no folded div but many #input in a   worksheet, if most parts of the.sheet is.dipalyed before, i.e. using #pre, then it might still be difficult to figure out where the #inpit is during intermediate #input.

**Comment by idealkindom** [comment]
> BTW. I have idea for a hack, in case you cannot figure out how to re-organize the worksheet. Just warp the #input into a div with position that will take it out of the fold, like:
> 
> ```
> '<div style="position:absolute; top:100px;"
> #input
> '</div>
> ```
> 
> Since Calcpad renders the message where #input occurs, it must fall inside the div.

I will try this method.

**Comment by idealkindom** [comment]
> BTW. I have idea for a hack, in case you cannot figure out how to re-organize the worksheet. Just warp the #input into a div with position that will take it out of the fold, like:
> 
> ```
> '<div style="position:absolute; top:100px;"
> #input
> '</div>
> ```
> 
> Since Calcpad renders the message where #input occurs, it must fall inside the div.

Ned,this really works, but incurrs the problem of output overlapping.

**Comment by Proektsoftbg** [comment]
You have to play with the position. Adjust `top:` to suit you needs or add `left:`, etc.

However, I still think that pausing inside fold is not a good idea in general. The main purpose of pausing is to allow the user to view some intermediate results and enter some additional input data if needed. So, he still will have to unfold each time to do that, which is tedious. 

he purpose of fold is to hide some too detailed, long or not so important calculation steps. However, all input data and final results must be visible in the report. This is another reason, not to brake for input inside fold. So, consider folding the details between the breakpoints and now around them.
