### ISSUE TITLE
Question on output copy

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#116]
I wondered what is the purpose of output copy, I tried and paste the result in a word file, but to find that all fraction lines were lost.

However, if you use the button Open with MS Word, it's quite OK.

So, I still dont know the right use method of output copy.

**Comment by Proektsoftbg** [comment]
Output copy can be used with **inline** equation mode. It is a very old Calcpad feature that came before "pro" equations and MS Word export.

I keep it for compatibility, but this is also a the most basic way to copy your output in any software, even in Notepad.
Imagine, you want to include your results in a LaTeX document. Then, you can copy the inline output and decorate it with LaTeX tags. Or any other. You are free to do whatever you want. 

![image](https://user-images.githubusercontent.com/90918363/215254865-c980b01b-dd36-4e8c-a848-c0ab0aedf9ea.png)


Of course, if you want to use MS Word, the built in export is better than copy. That is why we made it.
In the same way, when we add LaTeX export, it will be better than copy as well. :)

**Comment by idealkindom** [comment]
> Output copy can be used with **inline** equation mode. It is a very old Calcpad feature that came before "pro" equations and MS Word export.
> 
> I keep it for compatibility, but this is also a the most basic way to copy your output in any software, even in Notepad. Imagine, you want to include your results in a LaTeX document. Then, you can copy the inline output and decorate it with LaTeX tags. Or any other. You are free to do whatever you want.
> 
> ![image](https://user-images.githubusercontent.com/90918363/215254865-c980b01b-dd36-4e8c-a848-c0ab0aedf9ea.png)
> 
> Of course, if you want to use MS Word, the built in export is better than copy. That is why we made it. In the same way, when we add LaTeX export, it will be better than copy as well. :)

OK, now I understand it's for pure text,maybe the menu could be more clear as "text copy".

**Comment by idealkindom** [comment]
> Output copy can be used with **inline** equation mode. It is a very old Calcpad feature that came before "pro" equations and MS Word export.
> 
> I keep it for compatibility, but this is also a the most basic way to copy your output in any software, even in Notepad. Imagine, you want to include your results in a LaTeX document. Then, you can copy the inline output and decorate it with LaTeX tags. Or any other. You are free to do whatever you want.
> 
> ![image](https://user-images.githubusercontent.com/90918363/215254865-c980b01b-dd36-4e8c-a848-c0ab0aedf9ea.png)
> 
> Of course, if you want to use MS Word, the built in export is better than copy. That is why we made it. In the same way, when we add LaTeX export, it will be better than copy as well. :)

I tried to paste in Notepad++, still find that the denomination lines were missed.

**Comment by Proektsoftbg** [comment]
Probably, you did not switch to "inline" mode:

![image](https://user-images.githubusercontent.com/90918363/215327199-731aa2e6-3f13-48cf-9022-4063d794f5d1.png)

Notepad does not support Html, so it cannot be expected to preserve the formatting.

**Comment by idealkindom** [comment]
> Probably, you did not switch to "inline" mode:
> 
> ![image](https://user-images.githubusercontent.com/90918363/215327199-731aa2e6-3f13-48cf-9022-4063d794f5d1.png)
> 
> Notepad does not support Html, so it cannot be expected to preserve the formatting.

Yes,Ned, you're right. After checking inline mode the paste will not miss fraction lines. However, I think most units may defaultedly set to be inline mode.
