### ISSUE TITLE
Problem on calculation with units

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#117]
1 kN/m^2·1·m = 1 kN/m2·m
you know we want to get 1kN/m on the right hand.

**Comment by Proektsoftbg** [comment]
@idealkindom Thank you for reporting this. Yes, that was how it used to work before, but there were a small bug that squeezed in during the latest changes. I fixed it in the code, but I will be able to upload a new release on Monday when I am back to office.

**Comment by idealkindom** [comment]
> @idealkindom Thank you for reporting this. Yes, that is how it used to work before, but there were a small bug that squeezed in during the latest changes. I fixed it in the code, but I will be able to upload a new release on Monday when I am back to office.

Btw, Ned, if I use m to denote mass of an object, which is very common practice.Then How could I avoiding mixing up of parameter m and unit m.

**Comment by Proektsoftbg** [comment]
Hi, the problem was fixed in version 5.9.4:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.9.4

Now it works as normal as before. 

Please note that there is still possibility to compose units not allowing Calcpad to reduce simplify them. For example, if you have a bending moment in slab, you may want to write it as `M = 10 kNm/m`. It would be quite strange to have `M = 10 kN` for a bending moment. You can prevent reduction by entering the remaining units without values like in the above example. If you want them to get simplified, write `10 kNm/1m` = 10kN.


![image](https://user-images.githubusercontent.com/90918363/217278534-3a9f14e8-2260-417d-979d-cff63f05f091.png)

**Comment by idealkindom** [comment]
> Hi, the problem was fixed in version 5.9.4: https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.9.4
> 
> Now it works as normal as before.
> 
> Please note that there is still possibility to compose units not allowing Calcpad to reduce simplify them. For example, if you have a bending moment in slab, you may want to write it as `M = 10 kNm/m`. It would be quite strange to have `M = 10 kN` for a bending moment. You can prevent reduction by entering the remaining units without values like in the above example. If you want them to get simplified, write `10 kNm/1m` = 10kN.
> 
> ![image](https://user-images.githubusercontent.com/90918363/217278534-3a9f14e8-2260-417d-979d-cff63f05f091.png)

This is very considerable for engineers.I have other two questions. One is that I may want to use m to denote the mass of an object, then how could the mixing of parameter and unit.be avooded. Two is how.to display a.parameter in html comment like in calculation, it can.be easy seen that they are different at present, is it possilbe to control the display of a parameter in symbol, since #val could work to output the value only.

**Comment by Proektsoftbg** [comment]
Almost forgot. About mass and meters, there is no way to use the same symbol `m` for both without making your code ambiguous. Imagine the following situation:
```
'Mass -'m = 10kg
'Several hundred lines of code
'Force -'F = m*5m/s^2
```
Note that if you have a number before _m_, like `5m` it will be always parsed as units, in spite you have a variable _m_. However, you'd better to use some other symbol for your mass. What I do is to use `M` for mass and `m` for meters. Also, you can add some small symbol like `m.`, `m'` or `m_` (m-dot, m-prime or m-underscore).

**Comment by idealkindom** [comment]
> how.to display a.parameter in html comment like in calculation, it can.be easy seen that they are different at present, is it possilbe to control the display of a parameter in symbol, since #val could work to output the value only.

How about  display parameters in html comment like in a calculation, it can be easily seen that they are different at present, is it possilbe to control the display of a parameter in symbol, since #val could work to output the value only.

**Comment by Proektsoftbg** [comment]
I am not sure that I understand the question, but if you mean to display just variables or equations without calculations, you can use `#noc`.

![image](https://user-images.githubusercontent.com/90918363/217515554-b198a922-6b9d-41c2-85bd-7fc3c262f3a5.png)

**Comment by idealkindom** [comment]
> I am not sure that I understand the question, but if you mean to display just variables or equations without calculations, you can use `#noc`.
> 
> ![image](https://user-images.githubusercontent.com/90918363/217515554-b198a922-6b9d-41c2-85bd-7fc3c262f3a5.png)

Thanks Ned. I'm sorry that I didn't find that #noc could perform this purpose very well.

**Comment by Proektsoftbg** [comment]
OK. Great! I am glad it will do the job.
