### ISSUE TITLE
How about search some txt and replaced with nothing

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#119]
I found Calcpad dose not support this.

**Comment by Proektsoftbg** [comment]
Hmm... Did you try with the latest version? I tried it and it works on my side:

![image](https://user-images.githubusercontent.com/90918363/217814434-5c70edf9-aa1a-471c-84b5-1d39ccee409f.png)

Probably there is something else that prevents the operation, some settings maybe?

**Comment by idealkindom** [comment]
> Hmm... Did you try with the latest version? I tried it and it worked on my side:
> 
> ![image](https://user-images.githubusercontent.com/90918363/217814434-5c70edf9-aa1a-471c-84b5-1d39ccee409f.png)
> 
> Probably there is something else that prevents the operation, some settings maybe?

Cool, let try it on version 5.9.4

**Comment by idealkindom** [comment]
> Hmm... Did you try with the latest version? I tried it and it worked on my side:
> 
> ![image](https://user-images.githubusercontent.com/90918363/217814434-5c70edf9-aa1a-471c-84b5-1d39ccee409f.png)
> 
> Probably there is something else that prevents the operation, some settings maybe?

Hey,Ned.I surely tried and find it works. However ,with some condition,i.e. you have to input a space then backspace to trigger this then it could function.

I did not figure out why.
