### ISSUE TITLE
Missing template.html file

### ISSUE THREAD

**Issue by A-Shawqi** [Proektsoftbg/Calcpad#120]
Hi,
I'm trying to build the project on my computer, but it can't find the template.html file on startup and I couldn't find it in the repo files. Am I missing something?
![image](https://user-images.githubusercontent.com/17937102/218256831-eab6bf58-06af-46c6-844b-f8b8712bd61a.png)

I tried to copy the missing html files from the installation directory to the build output folder and it seems working but throws many script errors as shown below.
![image](https://user-images.githubusercontent.com/17937102/218256759-fa416bad-7d96-4d90-86aa-48b856d2d616.png)

Thanks in advance.

**Comment by A-Shawqi** [comment]
It's working normally now after including the jquery scripts file in addition to the missing HTML files.

**Comment by Proektsoftbg** [comment]
The best way is to install the latest Calcpad release in c:\Program Files\Calcpad, then select and copy all installed files into your bin/Debug and bin/Release folders in the project. Then, build and run the application. In this way, you will be sure that nothing will be missing.
