### ISSUE TITLE
Problem with ksi and kip/in^2

### ISSUE THREAD

**Issue by mihdicaballero** [Proektsoftbg/Calcpad#122]
Hi! This is a great software!

I'm having an issue with this unit conversion:
![image](https://user-images.githubusercontent.com/29404688/218569243-a206c519-cdcb-4799-93dc-6fbe67a639d2.png)
This should be the same, but if I use ksi and not kip/in^2 I have units mismatch further in the calculations. 

Am I doing something wrong?

**Comment by mihdicaballero** [comment]
I was using kip and not kipf. Now is solved.
![image](https://user-images.githubusercontent.com/29404688/218571584-8b194355-799a-4bc0-b72d-00438f5f2925.png)

**Comment by Proektsoftbg** [comment]
Hi, I just started answering. :)

Yes there is a difference between pound-force and pound-mass.
In Calcpad is assumed to be lbf and kipf for force and lb and kip for mass.
I know that it is also common to use lb and kip for force and lbm, kipm for mass, but no way to support both.

**Comment by mihdicaballero** [comment]
Yeah, I figured that was the thing. When I looked into the units module in Core I was convinced. Thanks for the support!!
