### ISSUE TITLE
[Enhancement] Paste image from clipboard 

### ISSUE THREAD

**Issue by mihdicaballero** [Proektsoftbg/Calcpad#123]
It would be great to have a paste image from clipboard option when creating these reports. So you make a drawing or sketch, take a screenshot, and then you can paste it automatically, without having to save it in a folder. 

This happens when doing small calculation reports that don't require much thought on graphic design detail, and you just make screenshots and annotations on them before pasting it in the report. 

Maybe the software could automatically save the pasted image as a jpg in the same folder as the calculation file?

**Comment by Proektsoftbg** [comment]
Hi,

thank you for your suggestion. It is a good idea. But I hope you do not expect the image to appear inside the source code like in a Word document. One possible scenario for Calpcad is to save the image in the same folder as the source file and add a reference to it inside the code, like:

`<img src="./image.png">`

The reference will be at the place of the cursor and the image will appear in the output.

**Comment by mihdicaballero** [comment]
Yeah of course, in the source code should appear as you say. I don't know if it much hassle or not, since I'm quite ignorant with this kind of programming. 

Nonetheless, it is not much trouble to save it before as well, like working with LaTeX documents. Surely there are more important features to work on.

**Comment by Proektsoftbg** [comment]
It was implemented in the latest version. Works similar to pasting images here in GitHub: the image is automatically saved and a link is added to its location.

**Comment by mihdicaballero** [comment]
Awesome!
