### ISSUE TITLE
Suggest to support percentage number

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#124]
Many engineering number may be suitable to be displayed in percentage.However , % is invalid syntax in Calcpad.

**Comment by idealkindom** [comment]
> Unfortunately, the % symbol is already used for the remainder (modulo) operator: `8 % 3 = 2` It is not possible to use the same symbol for both. One way is to change the modulo operator to something else, like: `8 mod 3 = 2` or `mod(8; 3) = 2 ` The other way is to use different symbols in code for percent units, like `p`, `pc` or `_%`, that will be converted to % in the output. What do you suggest?

the second approach I think is good enough.

**Comment by Proektsoftbg** [comment]
OK, Great! Thank you! 

So, `%` will remain the modulo operator and `_%` will be percent units. Then, we can also add `‰` for permilles as @hildebrandopsj suggested.  I will include both in the next updates.

**Comment by Proektsoftbg** [comment]
Yes!

**Comment by Proektsoftbg** [comment]
It was added in the latest version:
[45°23'46"](https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.9.8)

Write .% in expressions and |% to convert.

**Comment by idealkindom** [comment]
> It was added in the latest version: [45°23'46"](https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.9.8)
> 
> Write .% in expressions and |% to convert.

Great.
