### ISSUE TITLE
How to put text to the right in same line as equation

### ISSUE THREAD

**Issue by mihdicaballero** [Proektsoftbg/Calcpad#125]
I want to justify text to the right in the same line, like here:

![image](https://user-images.githubusercontent.com/29404688/219363712-9a4a2b5b-ce9b-4484-86e8-93ab81264724.png)

But I don't know what I'm doing wrong that I still get a line break.

![image](https://user-images.githubusercontent.com/29404688/219365835-0cf37406-2ce5-4ed9-a5df-c399d9b4b102.png)

Anyone knows a workaround? I want to know if I could have the equations left aligned and the text right aligned in the same line. Or the other way around.

**Comment by Proektsoftbg** [comment]
```
'<p style="float:right;">hola</p>
a = 2m
```

or

```
'<p class="ref">hola</p>
b = 2m
```
if you need to be exactly as in the example.
If you need to fit everything within A4 page width, warp the whole content into:
```
'<div style="width:180mm">
'Your content
'</div>
```
