### ISSUE TITLE
Compiling and assigning result of multiline function

### ISSUE THREAD

**Issue by mihdicaballero** [Proektsoftbg/Calcpad#127]
Hi! I'm trying to move from Mathcad to Calcpad, since this is an amazing and fast software. 
I have a function that has an if condition inside for calculating an effective moment of inertia. This is what I want to do in Calcpad:

![image](https://user-images.githubusercontent.com/29404688/219904236-c1facbcb-1ca7-4d73-8a51-9eded175804e.png)

And this is what I managed to do:

![image](https://user-images.githubusercontent.com/29404688/219904224-45efe838-3b72-48de-8719-9286e7cf5e57.png)

But I can't assign the function result to a variable when compiling. This is what I get:
![image](https://user-images.githubusercontent.com/29404688/219904262-dbfc7bff-b130-4d55-9a99-afd3d4e5a813.png)
And if I put it in the same line:
![image](https://user-images.githubusercontent.com/29404688/219904282-7c705f3d-1060-4c16-8db7-7022912febd5.png)
![image](https://user-images.githubusercontent.com/29404688/219904309-b9aca2ab-4796-4222-ac4a-8b0dc7fe7e99.png)

I would like to run this function for many values of Ma and assign it to different variables or just the function inside an equation, like this:
![image](https://user-images.githubusercontent.com/29404688/219904355-4ba75a3c-c7da-433d-802b-b99c71001eee.png)

What I managed to do is this:
```
#def Ie$(Mcr$; Ma$)
#if Ma$ ≤ 2/3*Mcr$
Ie = I_g
#else
Ie = I_cr/(1 - (2/3*Mcr$/Ma$)^2*(1 - I_cr/I_g))
#end if
#end def

Ie$(M_cr; M_pp)
I_e.pp = Ie
```
It does the trick but doesn't look quite good. And I can't get to hide the result of the if equation with #hide and #show.
![image](https://user-images.githubusercontent.com/29404688/219904561-7e072b58-f903-45bb-9cdf-33b65fc4c8b0.png)

Also, is there a way to make AutoRun work when working with functions? Because now I have to compile the inputs and then the outputs. Thanks for the help!

**Comment by idealkindom** [comment]
> Hi! I'm trying to move from Mathcad to Calcpad, since this is an amazing and fast software. I have a function that has an if condition inside for calculating an effective moment of inertia. This is what I want to do in Calcpad:
> 
> ![image](https://user-images.githubusercontent.com/29404688/219904236-c1facbcb-1ca7-4d73-8a51-9eded175804e.png)
> 
> And this is what I managed to do:
> 
> ![image](https://user-images.githubusercontent.com/29404688/219904224-45efe838-3b72-48de-8719-9286e7cf5e57.png)
> 
> But I can't assign the function result to a variable when compiling. This is what I get: ![image](https://user-images.githubusercontent.com/29404688/219904262-dbfc7bff-b130-4d55-9a99-afd3d4e5a813.png) And if I put it in the same line: ![image](https://user-images.githubusercontent.com/29404688/219904282-7c705f3d-1060-4c16-8db7-7022912febd5.png) ![image](https://user-images.githubusercontent.com/29404688/219904309-b9aca2ab-4796-4222-ac4a-8b0dc7fe7e99.png)
> 
> I would like to run this function for many values of Ma and assign it to different variables or just the function inside an equation, like this: ![image](https://user-images.githubusercontent.com/29404688/219904355-4ba75a3c-c7da-433d-802b-b99c71001eee.png)
> 
> What I managed to do is this:
> 
> ```
> #def Ie$(Mcr$; Ma$)
> #if Ma$ ≤ 2/3*Mcr$
> Ie = I_g
> #else
> Ie = I_cr/(1 - (2/3*Mcr$/Ma$)^2*(1 - I_cr/I_g))
> #end if
> #end def
> 
> Ie$(M_cr; M_pp)
> I_e.pp = Ie
> ```
> 
> It does the trick but doesn't look quite good. And I can't get to hide the result of the if equation with #hide and #show. ![image](https://user-images.githubusercontent.com/29404688/219904561-7e072b58-f903-45bb-9cdf-33b65fc4c8b0.png)
> 
> Also, is there a way to make AutoRun work when working with functions? Because now I have to compile the inputs and then the outputs. Thanks for the help!

Hi, I am a user too. I think maybe the problem is that you should include Ig and Ie as variables of the function too.However , I did not.testify my opinion.

**Comment by Proektsoftbg** [comment]
Hi, use the If() function:
`f(x; y) = if(x<y; x; y)`

**Comment by mihdicaballero** [comment]
You are a life saver! 
![image](https://user-images.githubusercontent.com/29404688/219946956-9002772a-bc81-4296-b938-07bc88479581.png)
Thanks a lot Ned!

**Comment by mihdicaballero** [comment]
Can we make the output of the if() funciton a string?
![image](https://user-images.githubusercontent.com/29404688/220435516-92788bf2-02eb-4df5-b51a-d971bef20333.png)

**Comment by hildebrandopsj** [comment]
Yes, you can. 

Just write in this form

```r=0.5
#if r < 0,5
' Verifica
#else
'No verifica
#end If

```

I suggest you to take a look in the help, we have some special syntax using calcpad, like #repeat, #if, #show etc. It's Very easy

**Comment by Proektsoftbg** [comment]
As @hildebrandopsj already replied, you should use the #if statement instead.

In general, math functions do not work with strings, but you can define string functions, called "macros". Their names must end with $. For example, you can create an inline function, similar to if() to handle your case:
```
#def if$(cond$; true$; false$)
    #if cond$
        'true$
    #else
        'false$
    #end If
#end def
```
Then, you can use it like that:
```
r = 0.5
if$(r < 1; Verifica; No verifica)
```
![image](https://user-images.githubusercontent.com/90918363/220459438-31c239cd-d478-48e6-bb8e-7243d2192812.png)

Macros are very powerful to mix strings with expressions. You can use them to create your own macro extension to the Calcpad language that automates specific tasks. For example, I made this to easy draw svg images with lines, circles, texts and dimension lines:

https://gist.github.com/Proektsoftbg/1f16d0f85e1007266455177f159eef23

And this is how the result looks:

![image](https://user-images.githubusercontent.com/90918363/220461733-7f145b33-40bf-47c9-9289-e1e60ac392b6.png)

The drawing is parametrically dependent on the input data, not just a static picture. I  am also experimenting with generation of AutoCAD script files from Calcpad in a similar way.

**Comment by mihdicaballero** [comment]
> Yes, you can.
> 
> Just write in this form
> 
> ```
> #if r < 0,5
> ' Verifica
> #else
> 'No verifica
> #end If
> ```
> 
> I suggest you to take a look in the help, we have some special syntax using calcpad, like #repeat, #if, #show etc. It's Very easy

Thanks! I figured that one out, but I wanted to do a one liner.

**Comment by mihdicaballero** [comment]
Thank you for the detailed answer. Macros are other level of working for sure.

I managed to do this:
![image](https://user-images.githubusercontent.com/29404688/220471614-47098570-e4cb-4831-a066-dbab489775eb.png)
And this when it's ok:
![image](https://user-images.githubusercontent.com/29404688/220471681-9b9a5a86-4141-4024-86c3-ac5682669271.png)
I was trying to have an inline check with this solution.
