### ISSUE TITLE
questions on trigonometric function 

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#129]
1.Since the symbol panel could support degree units input like deg, minute and second, why it errors when I input sin(45°23'46")?

2.How about give a shortcut keyboard for these three unit symbols?Hints could pop up when the mouse is hang on the symbol of the panel.

**Comment by Proektsoftbg** [comment]
It supports the units, but not the sequence of mixed numbers and units. You will have to write them as `45° + 23' + 46"`.
About shortcuts, probably, it will be best make it work with Ctrl + G. If you write singe and double quotes and press Ctrl + G to convert to primes and seconds. What do you thing?

**Comment by idealkindom** [comment]
> It supports the units, but not the sequence of mixed numbers and units. You will have to write them as `45° + 23' + 46"`. About shortcuts, probably, it will be best make it work with Ctrl + G. If you write singe and double quotes and press Ctrl + G to convert to primes and seconds. What do you thing?

to be honest I did not really know how to input these three units with keyboard, I input them with click on symbol panel.

**Comment by Proektsoftbg** [comment]
Yes, because they are not available on the keyboard. But what do you think about my suggestion to make them convert from quotes and Ctrl + G similar to Greek letters?

**Comment by idealkindom** [comment]
> Yes, because they are not available on the keyboard. But what do you think about my suggestion to make them convert from quotes and Ctrl + G similar to Greek letters?

1.I suggest to classify them as nondimentional units in the help doc.
2.I suggest to use @ as deg, english punctuations of ' and " correponding to minute and second respectively, in input. For example, we input as sin(30@20'45"),but the output should be as normal as we know in math.How do you think.

**Comment by idealkindom** [comment]
> Yes, because they are not available on the keyboard. But what do you think about my suggestion to make them convert from quotes and Ctrl + G similar to Greek letters?

Also, when we hang the cursor on the symbol of the panel, it's better to pop up a text hint of keyboard shortcut.

**Comment by Proektsoftbg** [comment]
OK, but you still will have to press Ctrl+G to convert because @ ' and " are used for other purposes - delimiters and comments.

**Comment by idealkindom** [comment]
> OK, but you still will have to press Ctrl+G to convert because @ ' and " are used for other purposes - delimiters and comments.

then hiw about input as sin(40#35$20%) or sin(40#35'20")，or you could imagine other key combinations that are easy to type in.

**Comment by Proektsoftbg** [comment]
I added the conversion of @ ' and " with Ctrl + G, but it is more difficult with the mixed format `45°23'46"`. So, for now you still have to write "`+`" between them: `45° + 23' + 46"`.

https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.9.8

**Comment by idealkindom** [comment]
> I added the conversion of @ ' and " with Ctrl + G, but it is more difficult with the mixed format `45°23'46"`. So, for now you still have to write "`+`" between them: `45° + 23' + 46"`.
> 
> https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.9.8

That's great.
