### ISSUE TITLE
Failing on new line inserting after start

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#134]
![image](https://user-images.githubusercontent.com/655339/222139253-de583068-6f9c-45cf-87b0-5cec1583e5ca.png)

It's failing on first try to insert new line in opened file. File was opened by _double click_ (not from File menu).
It happens only if right panel don't show anything.
Calcpad file: [Test.zip](https://github.com/Proektsoftbg/Calcpad/files/10860941/Test.zip)

**Comment by Proektsoftbg** [comment]
Hi, I am almost sure I have fixed that. Please, try do download the same release again, uninstall and install it fresh.

**Comment by cser** [comment]
Hello! I installed 
I have now uninstalled, downloaded, installed - nothing has changed O_o.

Имя: calcpad-setup-en-x64.exe
Размер: 15389400 байтов (14 MiB)
CRC32: C582FEC0
CRC64: 71DA8016B477C746
SHA256: 1C60056F0BD6FA50CEE7BE9C262D2A4C88EBC682DB27264FA61B153562AE2FC2
SHA1: 9A8D3B48E298028DE680D6A45F7CB7FA419D82F7
BLAKE2sp: DB3BF708225820E66BCCC468C0DEF3F09C8B5C420E7351E461CDB8907E50DD54

**Comment by Proektsoftbg** [comment]
OK. Thank you! At least, the global exception handling works!
I will play now a little more with it. It is tricky because it does not happen in debug. only at runtime. Some actions are asynchronous and probably the order of execution is different.

**Comment by Proektsoftbg** [comment]
I worked on this and it must be fixed now:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.9.8

Can you please check on your side and give some feedback. :) 
Stability is important.
