### ISSUE TITLE
New units

### ISSUE THREAD

**Issue by jgagnonNT** [Proektsoftbg/Calcpad#135]
Hello it would be great to include the following units:
- knots (kts) (speed)
- Poise and centipoise (dynamic viscosity)
- stokes (St) and centistokes (cSt) (Kinematic viscosity)

**Comment by Proektsoftbg** [comment]
Hi @jgagnonNT! I am not familiar with this units, but I will read about them and add to Calcpad. :)

**Comment by Proektsoftbg** [comment]
Done! You can check in the latest v.5.9.8 release:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.9.8

**Comment by jgagnonNT** [comment]
Much appreciated! 
It seems the "knot" unit is not in the documentation on the right.

**Comment by Proektsoftbg** [comment]
OK, Thank you! I will update it accordingly.
