### ISSUE TITLE
[Enhancement] Double-click from preview to specific code

### ISSUE THREAD

**Issue by mihdicaballero** [Proektsoftbg/Calcpad#139]
It could be great if the double click function that show you the document if you click in the code also could work the other way around:

Double-click in the preview and send you to the code that generated that.

What do you think @Proektsoftbg?

**Comment by Proektsoftbg** [comment]
Hi!

I think that this would be very useful. I recently stumbled with the problem to find a certain formula in the code, that I saw it was wrong in the output. It took me some time to find and fix it. I see how to implement this.

**Comment by Proektsoftbg** [comment]
This is not an easy thing to do. Links work fine now, but they appear only when there is an error. Probably, we can add some popup left arrow with link in the beginning of each line. It is easy with some CSS. It will not be visible by default, but if you move the pointer over the line, it will unfold. Then, it scroll to the respective line on the left, when clicked.

What do you think?

![image](https://user-images.githubusercontent.com/90918363/226477290-514e4cc3-6ee3-4e38-82d1-aac5d878c32c.png)

**Comment by mihdicaballero** [comment]
I believe it does the trick

**Comment by Proektsoftbg** [comment]
I think I fixed this. When you hover over a line in the output, a small arrow appears on the left which is a link to the respective line in the source code. It is not officially published yet, but you can download and try the new version from:

https://github.com/Proektsoftbg/Calcpad/blob/main/Setup/calcpad-setup-en-x64.exe

**Comment by mihdicaballero** [comment]
This is a great update!!!
