### ISSUE TITLE
Multiline functions

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#14]
It seems that only one way to implement multiline functions exists (fast and clear):
1. Use includes instead of functions;
    ```
    #include filename
    ```
    It's works like simple text insertion in this place (several includes in different parts of the file are allowed)
2. Use variable replaces with #include (include bonus)
    file main.cpd:
    ```
    τ_max=200MPa
    τ=150MPa
    #include check_stress: τ->σ; τ_max->σ_max
    ```
    file check_stress.cpd:
    ```
    #if σ ≤ σ_max
      '<font color="green">It is all OK ('σ' ≤ 'σ_max')</font>
    #else
      '<font color="red">It is problem ('σ' > 'σ_max')</font>
    #end if
    ```
    file main.cdp processed like this single file:
    ```
    τ_max=200MPa
    τ=150MPa
    #if τ ≤ τ_max
      '<font color="green">It is all OK ('τ' ≤ 'τ_max')</font>
    #else
      '<font color="red">It is problem ('τ' > 'τ_max')</font>
    #end if
    ```
3. namespaces instead of local variables
    It's just an invisible prefixes for variables.
    Bonus - block #namespace...#namespace end - to make it more automatic
    ```
    a=10'       shows a=10
    b=20'       shows b=20
    ns1::a=11'  shows a=11
    a'          shows a=10
    ::a'        shows a=10
    ns1::a'     shows a=11
    b'          shows b=20
    ::b'        shows b=20
    #namespace ns1
      a'        shows a=11
      b'        shows b=20 - if b missing for this namespace search in top namespace
      b=21'     when assigning - use current namespace
      b'        shows b=21
      ::b'      shows b=20
      ns1::a'   shows a=11
      ::a'      shows a=10
    #end namespace
    a'          shows a=10
    b'          shows b=20
    ns1::a'     shows a=11
    ns1::b'     shows b=21
    #namespace ns1
      a'        shows a=11
    #end namespace
    ```
P.S. Includes is the most wanted feature here. Even if nothing else will be implemented. (it's solves problems with big file navigation, very nice to extract generated svg images/methods into separate files, it's partly solves problems with missing string values)

**Comment by Proektsoftbg** [comment]
Hi,
#include is a great idea and it is easy to implement without even touching the math engine. It can be entirely in the preprocessing part - just need to scan the file contents and insert the text at the corresponding place.

But now it occurs to me that your idea can be extended. Similar to C language preprocessor directives, we can also use #define to make string variables and multiline functions (macros). It can be also a preprocessing feature - just replacing strings and can be implemented quickly. I suggest the following syntax:

**Single line variable**:

`#define CHECK_OK$ = '<font color="green">The check is satisfied.</font>`

usage:

```
#if τ ≤ τ_max
    CHECK_OK$
#else
    CHECK_NOT_OK$
#end if
```

**Single line macro**:

`#define CHECK_OK$(X$) = '<font color="green">The check is satisfied: X$ < X$_max</font>`

usage:

```
#if τ ≤ τ_max
    CHECK_OK$(τ)
#end if
```
result:

```
#if τ ≤ τ_max
     '<font color="green">The check is satisfied: τ < τ_max</font>`
#end if
```
The multiline versions will work in the similar way, and similar syntax. Just skip the equal sign "=" and and #end at the end.

**Multiline variable**:

```
#define MULTILINE_VARIABLE_NAME$
'First line
'Second line
'etc.
#end def
```

**Multiline macro**:

```
#define CHECK$(X$)
#if X$ ≤ X$_max
  '<font color="green">It is all OK ('X$' ≤ 'X$_max')</font>
#else
  '<font color="red">It is problem ('X$' > 'X$_max')</font>
#end if
#end def
```

uasge:

`CHECK$(τ)`

The result will be obtained by replacing all 'X$' with 'τ' and then replacing CHECK$(τ) with the respective content.

Then, we can keep #include, to organize the code into modules - mainly for larger parts of code. One module can contain many macros and variables. In this case, I prefer not to pass variables to modules. You can define macros inside for that purpose. Then, the #include statement will have the following syntax:

`#include MODULE_NAME`

The program will try to resolve the MODULE_NAME either as absolute path (local or network), relative path, URL string or even SQL string. For that purpose, it will be good also to define default INCLUDE_BASE_PATH$ variable. It can be folder, absolute URL or database connection string. 

Then if your files are on a server or some other folder, it will not be necessary to repeat the whole path everywhere, just file names. The path will be added automatically. If it is a database source, the program will open a connection in the beginning and close it at the end of the code.
The latest would be useful if you decide to distribute your worksheets and want your modules to be accessible from everywhere, similar to images.

If you like the above option, It will take about a week to implement and then I will give it to you for further testing.

About namespaces, it would be a good option to encapsulate you code a little bit on module level. It is a little bit more difficult, but it is possible. We can do this later.:)

**Comment by cser** [comment]
Thank you for response!

Yes, macroses syntax seems very good.

The only thing that confuses: I don't want to refuse implicit replacement in separated files includes without '$' in code (`<var_name_inside_extenral_file> <- <var_name>; '<var_name2_inside_extenral_file> <- <var_name2>`).
But for macroses this syntax (with '<-') is not short enough and makes definition not so clear.
On the other hand - for separate files short parameters syntax like '#include file(τ)' is not flexible enough (and I want them to be read like regular calculation files, without '$').

May be make 2 syntaxes - for parameters for include and for parameters for macroses?

ANYWAY: It would be better implement #include without parameters at first - perhaps some questions will disappear.

**Comment by Proektsoftbg** [comment]
Hi,

Rewriting variables in external files with #include is very easy and flexible. However, I think that it provides too much freedom to mess the things up in larger files. In this way, you may overwrite variables that are not intended for that, duplicate variable names, etc. 

Imagine that you have a longer file and have different checks including Von-Misses somewhere in the file:
```
...
σ_red = sqrt(σ^2 + 3*τ^2)
...
```
You have not intended these variables to be replaced, but someone decides to use your library and replaces τ->σ. Then, the Von Misses check will become: 
```
...
σ_red = sqrt(τ^2 + 3*τ^2)
...
```
I hope, you understand my point. It may encourage bad software practices that will make the code difficult to read, understand and maintain. Having modules is a powerful feature and we must think in advance. In the future, some people may use it to create complex hierarchy of libraries. This can be considered as bad language design. So, I would wish to enforce better capsulation as modern languages do.

When you create a macro, you must preliminary specify the variables that are intended for rewriting. All other variables are safe. So it would be better to use macros for that purpose. Having this, rewriting of variables on #include becomes obsolete. It would be better to use external variables. Imagine that you have to make three stress checks: σ, τ and σ_red and organize them in a file. It may look like this "stress_checks.cpd":
```
#external σ, τ, σ_max, τ_max
#define CHECK$(Sig; Max)
#if Sig ≤ Max
  '<p class=“OK“>The stress is satisfied ('Sig' ≤ 'Max')</p>
#else
  '<p class=“err“>The stress is NOT satisfied ('Sig' > 'Max')</p>
#end if
#end def
CHECK$(σ; σ_max)
CHECK$(τ; τ_max)
σ_red = sqrt(σ^2 + 3*τ^2)
CHECK$(σ_red; 1.15*σ_max)
```
The main file will look as follows "beam_design.cpd":
```
...
σ = M/W
τ = V*S/(b*I)
σ_max = 250MPa
τ_max = σ_max/sqrt(3)
#include stress_checks.cpd
...
```
The result will be the following unwrapped code:
```
...
σ = M/W
τ = V*S/(b*I)
σ_max = 250MPa
τ_max = σ_max/sqrt(3)
#if σ ≤ σ_max
  '<p class=“OK“>The stress is satisfied ('σ' ≤ 'σ_max')</p>
#else
  '<p class=“err“>The stress is NOT satisfied ('σ' > 'σ_max')</p>
#end if
#if τ ≤ τ_max
  '<p class=“OK“>The stress is satisfied ('τ' ≤ 'τ_max')</p>
#else
  '<p class=“err“>The stress is NOT satisfied ('τ' > 'τ_max')</p>
#end if
σ_red = sqrt(σ^2 + 3*τ^2)
#if σ_red ≤ 1.15*σ_red 
  '<p class=“OK“>The stress is satisfied ('σ_red' ≤ '1.15*σ_red ')</p>
#else
  '<p class=“err“>The stress is NOT satisfied ('σ_red' > '1.15*σ_red ')</p>
#end if
...
```
When you write your "stress_checks.cpd", Calcpad will not report σ, τ, σ_max, τ_max as not initialized. Instead, it will automatically provide a side-box with a table (variable manager) where you can put their initial values.

**Comment by Proektsoftbg** [comment]
BTW, we can provide even better encapsulation by introducing public variables and even access modifiers:
"stress_checks.cpd":
```
#namespase checks
#public σ, τ, σ_max, τ_max
...
```
"beam_design.cpd":
```
...
checks.σ = M/W
checks.τ = V*S/(b*I)
checks.σ_max = 250MPa
checks.τ_max = σ_max/sqrt(3)
#include stress_checks.cpd
...
```
Access modifiers may look as follows:
```
#in-public σ, τ
#out-public σ, τ
#ref-public σ, τ
```
and
```
#in-external σ, τ
#out-external σ, τ
#ref-external σ, τ
```
'in' variables cannot be rewritten - only read. They must exist before calling #include. You can write σ = ... but the value will be ignored after leaving the module;
'out' variables require initialization inside the module, but their values are kept after leaving it, and can be read outside;
'ref' variables must be specified outside before calling the module, and their values may be rewritten inside.

I generally prefer the Java and C# dot-like style 'namespace.variable', instead 'namespace::variable'.

**Comment by cser** [comment]
Wow!
So many new keyword scares me.
I write later, But I can say one thing for sure: missing public/private/internal is not a problem even for Python (I was C# programmer and I liked they modificators, but for engineering calculation problem is out there)

**Comment by Proektsoftbg** [comment]
These are just suggestions. Of course we can do without them. Only #external variables will be enough, mainly to make development end testing of "partial" modules easier. Please, check the previous post. :)

**Comment by cser** [comment]
What's clear:

1. > Rewriting variables in external files with #include is very easy and flexible. However, I think that it provides too much freedom to mess the things up in larger files. In this way, you may overwrite variables that are not intended for that, duplicate variable names, etc.

    OK, replacing by `->` was a mistake, forgot about it, `#include` just includes external file and nothing more.

2. Macros one line and multiline syntax is nice.

----------------------------------------

Now about namespaces and internals/in/outs. Namespaces or local variables is needed. Otherwise we will have reusing problems and we will drown in variable suffixes. The question is how exactly to implement it.

1. > I generally prefer the Java and C# dot-like style 'namespace.variable', instead 'namespace::variable'.

    How to separate variable `var` inside namespace `var` from variable `var.var`?
If you know how to solve this problem, then of course will be better to use a dot.

2. > ```
   > #external σ, τ, σ_max, τ_max
   > #define CHECK$(Sig; Max)
   > #if Sig ≤ Max
   >   '<p class=“OK“>The stress is satisfied ('Sig' ≤ 'Max')</p>
   > #else
   >   '<p class=“err“>The stress is NOT satisfied ('Sig' > 'Max')</p>
   > #end if
   > #end def
   > CHECK$(σ; σ_max)
   > CHECK$(τ; τ_max)
   > σ_red = sqrt(σ^2 + 3*τ^2)
   > CHECK$(σ_red; 1.15*σ_max)
   > ```
   
    What happened if #external missing?
    If it will not work without listing all used top-level variables - it's sounds very bad. It's wanted to see top-level variables without any boilerplate (if local variable doesn't override them).
    
    Is #external file or namespace dependent?

I just don't fully understand what this constraints do, trying to reread posts...

**Comment by Proektsoftbg** [comment]
About the '$': The idea came from the BASIC language where '$' was used for strings. 

![image](https://user-images.githubusercontent.com/90918363/159329209-befa69f9-e985-4a1a-b9eb-00881a331d9d.png)


It will help not to confuse string variables and macro parameters with numerical variables and rewrite one of them by accident. Even if you are careful, there is a risk to rewrite some units of measurement. They are too many to remember. We also must be careful about words in comments.

**Comment by cser** [comment]
Thank you very much!
Now I understand that #external mostly for testing and makes no problems, on the contrary - it will help.

> I suggest for now to start with macros (#define), #include and #external only. This will be stage one.
It's sounds cool.

> About the '$': The idea came from the BASIC language where '$' was used for strings.
> It will help not to confuse string variables and macro parameters with numerical variables and rewrite one of them by accident. Even if you are careful, there is a risk to rewrite some units of measurement. They are too many to remember. We also must be careful about words in comments.

Yes, now I also think that my idea was too weird.

**Comment by Proektsoftbg** [comment]
Yes, you are right. So, let be "::". It reminds me about C++ and I hate this language. :) But OK, I will swallow it. ;)

And your idea was actually excellent. Because it pointed me to C preprocessor directives. Now we will have string variables, multiline functions and modules, implemented entirely at preprocessing stage. It means no touching the language/math processor. It is just a matter of string handling, so we can do it easy and fast. And it is very suitable specifically for Calcpad.

So, I think we had a nice and useful discussion so far and the syntax was shaped. I will do some coding now and upload what is ready for testing. Thank you for your cooperation!

**Comment by cser** [comment]
Тhank you again, Ned!

**Comment by cser** [comment]
Some idea:
Do we need the spesial syntax `#external σ, τ, σ_max, τ_max` and special UI for this?
May be just introduce block that will be cut out from file on inclue?

```
#external σ, τ, σ_max, τ_max
```
And special UI

vs

```
#do not include
σ=?
τ=?
σ_max=200MPa
τ_max=0.54*σ_max
#end do not include
```
Second case seems more flexible.

**Comment by Proektsoftbg** [comment]
Yes, maybe this would be simpler. 
What about instead of `#do not include` to write just `#local`?

**Comment by cser** [comment]
`#local`/`#end local` - will be OK
`#local`/`#global` will be not OK - it will break nested includes

**Comment by cser** [comment]
To be more precise `#local`/`#global` is a problem **only** for `#include` inside `#local`/`#global` block and only for incorrect include order implementation.
So, #local/#global is OK too. The question is only what's more readable.

**Comment by Proektsoftbg** [comment]
`#local`/`#global` sounds better for me. It is shorter and more clear. If you have `#include` inside `#local`, it will be simply not processed when the file is included in its turn. If that is what you want, it's OK. If not, just move it to the `#global` section. :)

**Comment by Proektsoftbg** [comment]
Hi, Thank you!

Yes it is possible in general, but I have to enable it on GitHub. They have very convenient system for that. I myself donate some projects that I use. However, I am slowly advancing on that issue anyway, but it takes time. I had some heavy design projects to deliver recently. From now on I will have more time to work on Calcpad. :)

**Comment by cser** [comment]
Okey! Let's wait a little longer. Anyway, enable github donates of course if it's not a problem.

**Comment by cser** [comment]
I have summarized and specified the requirements for macros here:
https://gist.github.com/cser/dabe6e064915701be3d3bb5f50db4d42

**Comment by Proektsoftbg** [comment]
#include is almost ready:

![image](https://user-images.githubusercontent.com/90918363/179226124-762e6978-2038-4b82-8786-0cbc325179bc.png)

**Comment by cser** [comment]
It's sounds so good...
But I can't understand, what's wrong:
![image](https://user-images.githubusercontent.com/655339/179256056-44d8f842-088e-49aa-829e-2b586048b342.png)

**Comment by Proektsoftbg** [comment]
Nothing is wrong, you just do not have it yet. :)

**Comment by cser** [comment]
@Proektsoftbg, see pull request please!

**Comment by Proektsoftbg** [comment]
Almost done implementing string variables and macros! Some little fixes only remain and in 2-3 days, I will upload an update.

Here is one sample.
![image](https://user-images.githubusercontent.com/90918363/182433878-7939d613-3145-47a4-bf26-7e600764964e.png)
An you will also be able to view and check the generated (unwarped) code:
![image](https://user-images.githubusercontent.com/90918363/182434114-aafee8b5-71d7-436d-8eba-0fb1ad7a0ca4.png)

**Comment by cser** [comment]
Nice to here it! (while I'm waiting, I'm using build from pull request without dynamic features)

According to the screenshots, it is very pleasing that string passing into macros, but how separate this string from variable if it has no spaces?
Another things that bother: is it principial that `#def` body has no indentation?

**Comment by cser** [comment]
This is just a showing of how necessary macros are. This is a part of script that I use in my work:
![image](https://user-images.githubusercontent.com/655339/182553204-5e1abfd1-4ec0-4436-9246-54960bfeef45.png)

**Comment by Proektsoftbg** [comment]
1. It is not necessary to have spaces. You can have some of course, but only if you really need them. Lets take the following example:
```
#def Suffix$(s$) = variables$. 
Suffix$(_max) ' = variable_max
```
Calcpad will consider the whole string `variables$`. That is why we need that both macros and macro parameters end with `$`. The macro parser starts from the `$` backward to discover the whole literl. Then it scans forward until it finds the longest part that matches an existing macro or parameter.

2. I will add identation to #def. It is no problem.
3. Thank you for the screenshot. You really have to do complicated stress checks. Only, please use '$' at the end of macro parameters as well. It improves parsing, as discussed above. For the same reason, macros are allowed to have latin letters [A-Z][a-z], numbers [1-9] and underscore "_". They must start with a letter and finish with '$'.

**Comment by cser** [comment]
1 - I think I got it and so far it seems cool.
2, 3 - OK.

**Comment by Proektsoftbg** [comment]
![image](https://user-images.githubusercontent.com/90918363/182586112-261076a6-daaf-45e4-9fe0-a238b7478aec.png)
It is OK in my version. I will send it to you soon.

**Comment by Proektsoftbg** [comment]
@cser, I have implemented macros and includes and uploaded an update: [v.5.8](https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.8).

There is a sample file to demonstrate the new features: [Macros.zip](https://github.com/Proektsoftbg/Calcpad/files/9276612/Macros.zip)

Input boxes are still not supported in macros. I will change this later. As far as I know, you do not use them much, so I uploaded what is ready, so that you will not wait so long :).

Documentation has not been updated as well.

However, I updated syntax definitions for external editors Notepadd++. CudaText and Sublime:
[https://github.com/Proektsoftbg/Calcpad/tree/main/Setup/Syntax-for-external-editors](https://github.com/Proektsoftbg/Calcpad/tree/main/Setup/Syntax-for-external-editors)

Macros and includes are pre-processed by the program. As a result, their contents are replaced in the code and unwarped source code is generated. After that, the calculations are continued as normal. You can view the unwarped code, by the respective checkbox on the bottom-right part of the main window. If there is an error in the preprocessing, it is reported in respect to the initail code. If there is an error in the calculations, it is reproted in respect to the lines in unwarped code. If you click the line number link, the code will unwarp and scroll to that line.

That makes debugging of macros easier. Otherwise, you can get lost very easilly.
All defined macros are automatically included in the autocomplete list, to make them easier to insert.
We can consider better autocomplete in the future, that can include short information about the function/macro and its parameters: 

[https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#general-tags](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#general-tags)

**Comment by cser** [comment]
It finally happened! 

![image](https://user-images.githubusercontent.com/655339/183361861-1d8e3197-f42f-4374-9569-5e61239ffcaf.png)

I updated my simple calculation - it looks fine.
It's only one thing confusing - that user need to insert additional lines in macro that can be placed not just alone in line:
```diff
-#def VAL$(x)
+#def VAL$(x$)
+	'<span/>'
 	#val
-	'<font>'x'</font>
+	'<font>'x$'</font>
 	#equ
+	'<span/>'
 #end def
```
But right now it seems like the **best solution** because the logic is clear.
Alternative way (that uses in pull request build) is short, but leads to a struggle with fuzzy line wrapping rules.

**Comment by cser** [comment]
> @cser, I have implemented macros and includes and uploaded an update: v.5.8.

> There is a sample file to demonstrate the new features: Macros.zip

looked

> Input boxes are still not supported in macros. I will change this later. As far as I know, you do not use them much, so I uploaded what is ready, so that you will not wait so long :).

Yes, I still don't use input fields.

> Documentation has not been updated as well.

> However, I updated syntax definitions for external editors Notepadd++. CudaText and Sublime:
https://github.com/Proektsoftbg/Calcpad/tree/main/Setup/Syntax-for-external-editors

Thanks! I still use CudaText for big document (~1500 lines). Embedded editor works so slowly on this document even while autocalculation turned off (it's unclear what a problem: error checking or autocomplete?). Plus it has multiple carets and another editor features.

> Macros and includes are pre-processed by the program. As a result, their contents are replaced in the code and unwarped source code is generated. After that, the calculations are continued as normal. You can view the unwarped code, by the respective checkbox on the bottom-right part of the main window. If there is an error in the preprocessing, it is reported in respect to the initail code. If there is an error in the calculations, it is reproted in respect to the lines in unwarped code. If you click the line number link, the code will unwarp and scroll to that line.

Yes, I tried it -  unwrapped code displaying helped a lot with my calculation updating.

> That makes debugging of macros easier. Otherwise, you can get lost very easilly.
All defined macros are automatically included in the autocomplete list, to make them easier to insert.
> We can consider better autocomplete in the future, that can include short information about the function/macro and its parameters:
> https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#general-tags

Тhere are no thoughts - I hated javadocs when was a programmer :).

**Comment by Proektsoftbg** [comment]
Great! I am glad that it works for you.
Probably I can optimize the internal editor to work faster. There were plenty of new features added recently.

Next steps is to fully implement the deg/rad/grad units as discussed. Also, input values embedded in code {1.23}.
We need to update the documentation and other resources.

I thhink that the next majour change should be vectors and matrices. They are needed very much to make Calcpad a fully functional math environment.

I will close this issue now as it was generally implemented. If you find anything, you can open a separate issue since this one became too long ad difficult to follow.
