### ISSUE TITLE
why html UI dose not work in a #if #else conditional loop

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#140]
My question is as the title goes.

Html UI could be displayed in the output if it was defined in a if else condional loop. However, it's not interactive anymore.

**Comment by Proektsoftbg** [comment]
Hi, I am not sure that I understand the question. It displays as always:

![image](https://user-images.githubusercontent.com/90918363/226341271-c97775d4-48a8-4802-818a-b84f91298b7a.png)

**Comment by idealkindom** [comment]
> Hi, I am not sure that I understand the question. It displays as always:
> 
> ![image](https://user-images.githubusercontent.com/90918363/226341271-c97775d4-48a8-4802-818a-b84f91298b7a.png)

Ned,try this:

a = 1000
#post
#if a ≡ 1000


'Select an option: <select name="target1">
'<option value="11;12">x1; y1</option>
'<option value="21;22">x2; y2</option>
'<option value="31;32">x3; y3</option>
'</select>
'<p id="target1"> Values:'x = ? {31}','y = ? {32}'</p>


'<p>Select: 
'<input name="target2" type="radio" id="opt1" value="1"/>
'<label for="opt1">option 1</label>
'<input name="target2" type="radio" id="opt2" value="2"/>
'<label for="opt2">option 2</label>
'<p id="target2">Value -'opt = ? {2}'</p>


'<p><input name="target3" type="checkbox" id="chk1" value="3"/>
'<label for="chk1">Checkbox 1</label></p>
'<p id="target3">Value -'chk = ? {3}'</p>

#end if

**Comment by Proektsoftbg** [comment]
Hi!

I do not think this code will work in Calcpad. Probably GitHub changes something. Please, post a screenshot or put your code in a `code` block. Also, you have a `#post` on the second line. This will prevent the code after it to show as an input form.

**Comment by idealkindom** [comment]
> Hi!
> 
> I do not think this code will work in Calcpad. Probably GitHub changes something. Please, post a screenshot or put your code in a `code` block. Also, you have a `#post` on the second line. This will prevent the code after it to show as an input form.

![image](https://user-images.githubusercontent.com/18344868/226345514-e3e4f27d-2022-405c-bbf5-356f93d98f3a.png)

**Comment by idealkindom** [comment]
> I added a #post before #if

I added a #post before #if because I don't want #if come into the output.

**Comment by Proektsoftbg** [comment]
Hi,

Your screenshot shows the report after being calculated. It is normal that all input fields are inactive in the report.

 How about before calculations - in input mode?

**Comment by Proektsoftbg** [comment]
You can make it with a little JS (jQuery). In this example, I made it to display different images immediately after you select an option. Check out this example:
https://github.com/Proektsoftbg/Calcpad/blob/main/Examples/Structural%20Design/Reinforced%20Concrete/SLS%20Design%20of%20Beam%20with%20Rectangular%20Section.cpd

Try this code:

```
'<p id="type" class="flip_base" style="display:none">'type = ? {0}'</p>
#pre
'<p><select data-target="type" class="flip_trigger"> 
'<option value="1">Cantilever with concentrated load</option>
'<option value="2">Cantilever with uniformly distributed load</option>
'<option value="3">Simply supported beam with concentrated load</option>
'<option value="0">Simply supported beam with uniformly distributed load</option>
'</select></p>
#hide
#if type ≡ 1
	#show
	'<img class="side flip flip_1" src="https://calcpad.eu/media/structures/rc/design/deflection-cantilever-force.png" alt="deflection-cantilever-force.png" style="width:150pt;">
	#post
	'Cantilever with concentrated load
	#hide
#else if type ≡ 2
	#show
	'<img class="side flip flip_2" src="https://calcpad.eu/media/structures/rc/design/deflection-cantilever-uniform.png" alt="deflection-cantilever-uniform.png" style="width:150pt;">
	#post
	'Cantilever with uniformly distributed load
	#hide
#else if type ≡ 3
	#show
	'<img class="side flip flip_3" src="https://calcpad.eu/media/structures/rc/design/deflection-beam-force.png" alt="deflection-beam-force.png" style="width:150pt;">
	#post
	'Simply supported beam with concentrated load
	#hide
#else if type ≡ 0
	#show
	'<img class="side flip flip_0" src="https://calcpad.eu/media/structures/rc/design/deflection-beam-uniform.png" alt="deflection-beam-uniform.png" style="width:150pt;">
	#post
	'Simply supported beam with uniformly distributed load
	#hide
#end if
#show
'<script>if(window.jQuery){$(".flip_trigger").change(function(){$(".flip").hide();$(".flip_"+$(this).val()).show();});$(".flip").hide();$(".flip_"+$(".flip_base input").val()).show();}</script>
```

**Comment by idealkindom** [comment]
> jQuery

Al right. Maybe this is way.
