### ISSUE TITLE
Inverse trigonometric functions units

### ISSUE THREAD

**Issue by emanuelemaz** [Proektsoftbg/Calcpad#144]
When an inverse trigonometric function is used it returns a unitless output.
Example:
![image](https://user-images.githubusercontent.com/34983402/230738102-c9be8ee8-e271-4e1d-ba5a-c1d2f90f1bd7.png)
Trying to add a unit after the function returns:
![image](https://user-images.githubusercontent.com/34983402/230738358-3412be9a-0297-41c4-a206-309e58c9c24a.png)
Only way to use units with the funciton is multiplying with 1 and the unit:
![image](https://user-images.githubusercontent.com/34983402/230738433-e8c6dd52-22d4-4b39-ae07-00d910fd262c.png)
It would be nice if it used the compiler switch unit or the radio button unit.

**Comment by Proektsoftbg** [comment]
Hi, return values are unitless, by default. To turn this option on, you only have to define the variable: `ReturnAngleUnits = 1` in the beginning.

Then, all values from inverse trig functions will be returned into the current units for angles, as you wish. If you want to hide  these settings from the output, enclose them with #hide - #show:

![image](https://user-images.githubusercontent.com/90918363/230745365-45b20245-b7c4-47bc-9f3f-6ccd95f3867b.png)

**Comment by emanuelemaz** [comment]
Thanks! I didn't notice it in the docs, my bad.
