### ISSUE TITLE
Multiple conversions on same line

### ISSUE THREAD

**Issue by jgagnonNT** [Proektsoftbg/Calcpad#148]
Hello,

It would be great to have the possibility to show multiple unit conversions on the same line.
For example, in the calculation below, the last line would output : P=F/A=0.0187psi=0.129kPa
![image](https://user-images.githubusercontent.com/111089248/234874488-a66edcba-02a3-422c-8fae-2061bcf1f388.png)

**Comment by Proektsoftbg** [comment]
Yes, it may be useful in some cases. 
If this helps, please note that you do not need to repeat the formula on each line. 
You can write only the variable, you need to convert:
```
P = F/A|psi
P|kPa
```
Or you can combine them in one line with some text that sounds “smart“:
`P = F/A|psi'or'P|kPa'in SI uits

![image](https://user-images.githubusercontent.com/90918363/234941153-a7a4e77d-0d9a-4d6c-a67b-ba5da54bb82f.png)
