### ISSUE TITLE
Error in converting to degrees

### ISSUE THREAD

**Issue by johnnyontheweb** [Proektsoftbg/Calcpad#149]
Hello,
I'm trying CalcPad since a few days, my compliments for it.
I encounter a strange error in a formula like this one, in which I want the output in degrees since I'm calculating an angle:
```
θ = acot(min(sqrt((b*0.5*fc)/(As/s*fy) - 1); 2.5))|°
```
the error is: `Error in ... on line.... .... "unitless" are inconsistent with the target units "°".`

Am I missing something? thanks in advance

**Comment by johnnyontheweb** [comment]
I have angle in Deg, but I still have to add `*°` to the formula above to get the results. Why acot does not add it automatically? thanks

**Comment by Proektsoftbg** [comment]
Hi,

By default, trigonometric functions return "unitless" results. This is needed for backward compatibility with older versions and for all cases where the user just do not want to use units. If you want the trigonometric functions to return angles with units, you have to switch it on by defining the variable:

`ReturnAngleUnits = 1`

You can hide it with #hide - #show if you do not want it to appear in the report.

![image](https://user-images.githubusercontent.com/90918363/235127682-29095059-3eb6-49ef-bf82-83adf0cb9d25.png)

**Comment by johnnyontheweb** [comment]
thanks a lot
