### ISSUE TITLE
Load data from external files 

### ISSUE THREAD

**Issue by andsan3** [Proektsoftbg/Calcpad#15]
Thanks for the great program.
 Is it possible to load data from external files (txt, sql, Excel)

**Comment by Proektsoftbg** [comment]
Hi, thank you!

If you mean something like connection function, it is not implemented yet. The best you can do now is to copy the data into your worksheet and probably organize it into some of the interpolation/data sampling functions like in the following example:

https://github.com/Proektsoftbg/Calcpad/blob/main/Examples/Interpolation.cpd

Can you please give some details about the use case where this is needed?

**Comment by andsan3** [comment]
1. Import FEA result from txt, csv.
2. Import cross-section properties from sql base.
3. value = import_excel (C:\"file.xlsx"; "Sheet1"; row; col).

**Comment by cser** [comment]
It's no arrays/matrixes yet, so you need to wrap table into calling function `take(n, a1, a2, a3, ...)`/`line(x, y1, y2, y3, ...)` anyway 😔 . It's may be possible to do it automatic with RegEx (change clipboard with sed/sd command line tools or with text editor).
```
x, 10, 21, 33, 44, 15, 36, 47
y, 23, 34, 45, 44, 15, 36, 34
```
```
x(i)=take(i; 10; 21; 33; 44; 15; 36; 47)
y(i)=take(i; 23; 34; 45; 44; 15; 36; 34)
```

**Comment by Proektsoftbg** [comment]
I will close this issue for now. Until we add vectors and matrices, it is pointless to add data import.
So, the only options for now is to copy your data into your file and organize it into some interpolation/vector functions.
When we add #import, it can be separate cpd file (see issue #14 ).

There is another option. For example, If you need to select steel sections, you can warp the data with a "select" html element and fill input boxes automatically.

Check this example:
https://github.com/Proektsoftbg/Calcpad/tree/main/Examples/Structural%20Design/Steel
