### ISSUE TITLE
The import of Notepad++ always fail

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#155]
I tried with Calcpad 6.0.5 and Notepad++ 8.5.2.

**Comment by Proektsoftbg** [comment]
Hi! 

Can you please clarify what do you mean by "import of Notepad++"? What are you trying to do? What is actually happening?

**Comment by idealkindom** [comment]
> Hi!
> 
> Can you please clarify what do you mean by "import of Notepad++"? What are you trying to do? What is actually happening?

I mean syntax support of Calcpad in Notepad++,i.e. import language support file in Notepad++.

**Comment by Proektsoftbg** [comment]
It works on my side. Probably there is some machine-specific problem, but unless you provide more detailed information I will not be able to help you.

![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/528594cc-6cb1-419f-8d71-a7d9a61246fa)
