### ISSUE TITLE
How can I re-use the result form the previous calculation as first operand in next calculation?

### ISSUE THREAD

**Issue by pstein** [Proektsoftbg/Calcpad#165]
Assume I type 23+35 in first line and hit RETURN
The output pane right shows 58. Good

Now I want to add 7 to it.
So I add 

+ 7

....but the output pane on the right shows 

"Error in "+7" on line [2]: Missing operand.

Bad.
How can I re-use the result from previous calculation as first operand (if no first operand is entered)?

**Comment by Proektsoftbg** [comment]
Calcpad is not a type of interactive calculator as you probably expect. In Calcpad, you create a complete calculation worksheet and run it. To use previous results, assign them to variables (`a = 23 + 35`, then `b = a + 7`). Check the Examples in your Documents\Calcpad folder or here:
https://github.com/Proektsoftbg/Calcpad/tree/main/Examples

For this type of interactive calcs, you can use the Cli app:

![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/3566ac55-0855-4c83-a7a3-207a558b6581)

There, you can type "ans" to get the pervious result.
