### ISSUE TITLE
How to reduce line height (gap between lines) in left and right panes to 1 or 2 empty pixel lines?

### ISSUE THREAD

**Issue by pstein** [Proektsoftbg/Calcpad#166]
I want to see as many lines in left and right panes WITHOUT having to scroll.
Therefore I want to reduce line height or more precisely:
Reduce the space gap between two lines.

1 or 2 empty white pixel rows are enough.
How can I achieve this?

**Comment by Proektsoftbg** [comment]
Hi! You cannot reduce only the line height. If it will help, you can zoom the font size in and out by pressing Ctrl and rolling the mouse wheel on the left and right pane.
