### ISSUE TITLE
How to AUTO-save calculation history at exit?

### ISSUE THREAD

**Issue by pstein** [Proektsoftbg/Calcpad#167]
Whenever I exit CalcPad I am prompted if I want to save all calculations.

How can I tell CalcPad to automatically save all (or previous 30) calculations at exit and don't bother me any more with this prompt?

**Comment by Proektsoftbg** [comment]
Calcpad works with files as any other windows application. It needs you to specify a filename. It is the same behavior as Excel, Word or any other program.

You can also try the online app:
https://calcpad.eu/Ide

It does not prompts you to save a file, just keeps the last input in your local browser storage.
