### ISSUE TITLE
How to deploy to website?

### ISSUE THREAD

**Issue by berkdemir** [Proektsoftbg/Calcpad#170]
Hi,
Sorry if I have missed, but do you have a (hopefully easy) methodology to deploy the calculations to a website like you did, for example, here? 
https://calcpad.eu/Worksheet/21/bending-design-of-rectangular-section
This can be useful for both publishing online, but also sharing html directly with colleagues who don't use calcpad.

**Comment by snoozy2323** [comment]
I was checking for that today, too. That is really a good usecase. You can find the possible solutions in this thread:
https://github.com/Proektsoftbg/Calcpad/discussions/105

Please let me know if you can implement any of the solutions.

**Comment by Proektsoftbg** [comment]
Hi, this will be possible after we make a public website or public web API.
A webpage alone would not be able to work without being powered by the Calcpad calculation engine behind. About the current state of this feature, please read this answer:

https://github.com/Proektsoftbg/Calcpad/discussions/97#discussioncomment-6221993
