### ISSUE TITLE
Add indication of the calcpad version on the web page

### ISSUE THREAD

**Issue by Plinsboorg** [Proektsoftbg/Calcpad#173]
Hello, 

I have another enhancement ticket. 
When I'm using Calcpad online IDE I have no way to determine the software version I use. 
The desktop app has it in the Widow header. Unfortunately, there is no such thing in the web version.
It might be difficult to report a bug in the future without the ability to specify the version on which the bug occurred.

I would suggest adding the web app version somewhere below the How does it work? section when you scroll down the page.
Please, let me know if the version number is available it's just I wasn't able to find it.

**Comment by Proektsoftbg** [comment]
Good suggestion. Thank you!

I will think about an appropriate place for it.

**Comment by Plinsboorg** [comment]
@Proektsoftbg is it implemented already?
I don't seem to find the revision number still.

**Comment by Proektsoftbg** [comment]
Hi! Not yet. Not so fast, it is summertime. :)

**Comment by Proektsoftbg** [comment]
Oh, I am sorry! Probably clicked the wrong button.

**Comment by Proektsoftbg** [comment]
Done!
https://calcpad.eu/Ide
