### ISSUE TITLE
How about a condition like a<x<b

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#174]
I defined two functions with Calcpad built-in function of siwtch,both of which could run, but the results of the first function is undefined.
I guess I understand the reason, however I really hope that the first kind of description of condition could also work.  In this way, the  function could be defined and dispayed in a better way.

l(d) = switch(0.057 ≤ d < 0.076; line((d - 0.057)/(0.076 - 0.057) + 1; 0.81; 0.84); 0.076 ≤ d < 0.085; line((d - 0.076)/0.009 + 1; 0.84; 0.85))
l(0.057)
l(0.076)

l2(d) = switch((.057 ≤ d)*(d < 0.076); line((d - 0.057)/(0.076 - 0.057) + 1; 0.81; 0.84); (0.076 ≤ d)*(d < 0.085); line((d - 0.076)/0.009 + 1; 0.84; 0.85))
l2(0.057)
l2(0.076)
l2(0.0849)

**Comment by Proektsoftbg** [comment]
Hi, @idealkindom!

You are thinking right. Although this is how conditions look in books, Calcpad does not work in this way. And other programming languages that applies as well.

Conditional operators return `0` or `1`. So, if we have:
`d = 0.06`
then
`0.057 ≤ d '= 1`

If there are several conditional operators in a row, they will evaluate from left to right. So:
`0.057 ≤ d < 0.076` = `(0.057 ≤ 0.06) < 0.076` = `1 < 0.076` = `0`

The correct way is to combine both conditions with logical AND operator:
`0.057 ≤ d ∧ d < 0.076`

This will evaluate as:
`0.057 ≤ 0.06 ∧ 0.06 < 0.076`
`1 ∧ 1`
`1`
