### ISSUE TITLE
It seem that mWh is not supported as a unit for Calcpad

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#176]
It seem that mWh is not supported as a unit for Calcpad

**Comment by snoozy2323** [comment]
You can just type mW*h or create a custom unit like that:
.mWh = 1mW*h

**Comment by idealkindom** [comment]
> You can just type mW_h or create a custom unit like that: .mWh = 1mW_h

Thanks  a lot.

**Comment by FEA-eng** [comment]
@idealkindom I think that this issue can be closed since mWh unit is supported now.
