### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by hildebrandopsj** [Proektsoftbg/Calcpad#178]
Hi @Proektsoftbg ,

Can you help me? I cannot install the last version of calcpad on my office computer. The problem it's on my side? The IT guy tryed with login privilege but failed too.

![image](https://github.com/Proektsoftbg/Calcpad/assets/86059123/d955b5c7-52a4-4a7d-893b-eb590fec3056)

**Comment by Proektsoftbg** [comment]
Hi, It seems that it is trying to replace a font that is already installed.
What happens if you try to click "Ignore"?

**Comment by hildebrandopsj** [comment]
Hi Ned, i don`t know why, but this morning it worked! Mysteries of IT
