### ISSUE TITLE
Time units handled incorrectly

### ISSUE THREAD

**Issue by FifoIronton** [Proektsoftbg/Calcpad#18]
#### Description
When using the Online IDE with Calcpad, time units (`s`, `min`, `h`, `Hz`) are not handled correctly. This makes calculations such as Rotations Per Minute quite prone to error.  
A specific example is `1 / 1min = 1 h^-1` in calcpad. As well, the default units of multiplications of `1 min * 1 ms` are `h`.

#### Screenshots
![image](https://user-images.githubusercontent.com/18233244/163809953-377e467d-8132-4887-9d94-65b5b1e70d9f.png)

#### To Reproduce
I used the following to show unexpected bahaviour
```
t = 1min
1/t
t * 1 Hz
t_2 = 1 ms
1/t_2
t * t_2
```

**Comment by Proektsoftbg** [comment]
OK, It is ready!
You can try it now on calcpad.eu or download the updated desktop version:
https://github.com/Proektsoftbg/Calcpad/releases/tag/5.6.6

**Comment by FifoIronton** [comment]
Thanks for looking into this! I found another issue with time units when playing around:
![image](https://user-images.githubusercontent.com/18233244/163842479-887924cc-22f3-404a-9077-e2df1a2877ed.png)

I would expect this to give `y=60 min^-1`, rather than `60 s^-1`
```
x = 1/s
y = x * 60 s / min
```

**Comment by Proektsoftbg** [comment]
Thank you!

This one was fixed too. I amended the previous release.

![image](https://user-images.githubusercontent.com/90918363/164009202-5d0e0d2b-7f3d-4e07-ab83-d8482eebf6c9.png)

**Comment by FifoIronton** [comment]
Great to see the tool improving. Thanks!
