### ISSUE TITLE
Is it possible to make #include support .cpdz file

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#186]
As the title goes. The need come from the fact that the subroutine file may demands no change when share a main program with colleagues.

**Comment by Proektsoftbg** [comment]
Hi @idealkindom! Thank you for pointing that out.

I am surprised it does not. Probably I have missed something. :( It is possible and it is a must. I will fix this in the next release. 

Another idea about cpdz files is to pack all dependencies like local images, the included modules, etc. inside. Then, you will have to distribute a single file. What do you think about it?

**Comment by hildebrandopsj** [comment]
This option will make the distribution of cpdz so much easier!

Hildebrando Pereira dos Santos Junior
------------------------------

Engenheiro Civil | (13) 99803-7364 |

***@***.***

www.pereirasantos.eng.br

Essa mensagem e seus anexos: (I) contém informações confidenciais; (II) são
exclusivos para o(s) destinatário(s) deste email; (III) possuem fins
específicos, e (IV) são protegidos em face dos dispositivos das leis
brasileiras e mais especificamente da LGPD – Lei Geral de Proteção de
Dados, Lei no. 13.709 de 14/09/2018, com as alterações definidas pela lei
13.853 de 08/07/2019. Se você não é o destinatário dessa mensagem, delete-a
e avise ao emitente.


Em ter., 29 de ago. de 2023 às 15:09, Ned Ganchovski <
***@***.***> escreveu:

**Comment by idealkindom** [comment]
> Hi @idealkindom! Thank you for pointing that out.
> 
> I am surprised it does not. Probably I have missed something. :( It is possible and it is a must. I will fix this in the next release.
> 
> Another idea about cpdz files is to pack all dependencies like local images, the included modules, etc. inside. Then, you will have to distribute a single file. What do you think about it?

Surely, to be honest I also have this on mind, that a "merge" module for Calcpad is needed to include all the elements in one cpdz file, thus making it very convenient for distribution.

**Comment by idealkindom** [comment]
> Hi @idealkindom! Thank you for pointing that out.
> 
> I am surprised it does not. Probably I have missed something. :( It is possible and it is a must. I will fix this in the next release.
> 
> Another idea about cpdz files is to pack all dependencies like local images, the included modules, etc. inside. Then, you will have to distribute a single file. What do you think about it?

One more thing,is it possible to add trigger image into Html UI? It's also the same for selection but without show the results below.

**Comment by Proektsoftbg** [comment]
This is now fixed in the latest version 6.1.5.
[/](https://github.com/Proektsoftbg/Calcpad/releases/tag/v6.1.5)
