### ISSUE TITLE
Does apostrophe with Latin latter works?

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#187]
This feature was announced with the release of 6.1.1.However, I could not repeat it on 6.1.3.Anyone tested?

**Comment by Proektsoftbg** [comment]
I just tried it and it worked. Are you sure that you are using the same apostrophe?

It must be this one: `. It is on the top left of the keyboard.

![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/b1a8c2fc-1948-413f-961e-5a05216202bc)

**Comment by idealkindom** [comment]
> I just tried it and it worked. Are you sure that you are using the same apostrophe?
> 
> It must be this one: `. It is on the top left of the keyboard.
> 
> ![image](https://user-images.githubusercontent.com/90918363/264995816-b1a8c2fc-1948-413f-961e-5a05216202bc.png)

So it only works in Cli not in Calcpad's cpd file ??

**Comment by Proektsoftbg** [comment]
Yes. In Calcpad it is the same as before - with Ctrl + G.

In Cli, the console does not accept Ctrl + G, so we escape it with `. This is only for Cli.
