### ISSUE TITLE
Font error during installation of Calcpad 6.1.4

### ISSUE THREAD

**Issue by FEA-eng** [Proektsoftbg/Calcpad#197]
Hi,

when trying to update from 6.1.3 to 6.1.4 and when installing 6.1.4 from scratch on one of my Windows 10 computers, I received the following error message:

![error](https://github.com/Proektsoftbg/Calcpad/assets/59876896/2f16cb5b-a13c-478b-9db7-b7ac20007b06)

One sentence in this error message is in Polish (my OS is set to that language). It can be translated to "Access denied".

I clicked Ignore and Calcpad seems to be working fine but it still might be worth reporting.

**Comment by Proektsoftbg** [comment]
Hi! Thank you for reporting that.

Probably the font is already installed and currently in use by some process.
So, ignoring its replacement would not do any harm.

This can happen with any shared resource on Windows during installation.
