### ISSUE TITLE
Show values of formula but do not calculate the final value

### ISSUE THREAD

**Issue by Itenium** [Proektsoftbg/Calcpad#199]
Good day.

Sometimes a formula becomes very long, and it goes to the next line. 
A way to display the formula, substitution of values, and then the answer in more than one line. 
It would help, that there are a similar function as #noc, that 
1) only shows the substituted values in the formula (excluding the original formula and final answer)
2) shows the formula, with substituted values with the formula (excluding the final answer)

To help what I mean I give a small example.
m = 5
c = 3
y = m * x + c
x = 6
for case 1) y = 5 * 6 + 3
for case 2) y = m * x + c = 5 * 6 + 3

**Comment by Proektsoftbg** [comment]
Yes, I did and got the following:

m = 5
c = 3
y = m·x + c
x = 6
for case 1) y = 5·6 + 3
for case 2) y = m·x + c
y = 33

**Comment by BenGonGon** [comment]
> Yes, I did and got the following:
> 
> m = 5 c = 3 y = m·x + c x = 6 for case 1) y = 5·6 + 3 for case 2) y = m·x + c y = 33

It was a formatting example for Itenium like he want to see.

**Comment by Proektsoftbg** [comment]
Hi!
This feature is now available in v6.1.9:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v6.1.9
