### ISSUE TITLE
Linear Interpolation - Options

### ISSUE THREAD

**Issue by hildebrandopsj** [Proektsoftbg/Calcpad#203]
Hi @Proektsoftbg ,

Is it possible to configure the linear function to use x values of 5 by 5 or another number?

![151fd82e-b0c1-4056-86e3-b61e11889102](https://github.com/Proektsoftbg/Calcpad/assets/86059123/7053f22c-7c05-43e9-8719-ac785f1c5422)

**Comment by idealkindom** [comment]
> @hildebrandopsj Yes, sure.
> 
> You can apply any kind of transformation that maps x ∈ [a; b] to k ∈ [1; n] as a function. In your case, `k(x) = 0.1*x + 1` Then call: `f_2(x) = line(k(x); ...)` or simply `f_2(x) = line(0.1*x + 1; ...)` For k(x), you will get:
> 
> ```
> k(0) = 0.1*0 + 1 = 1
> k(40) = 0.1*40 + 1 = 4 + 1 = 5
> ```
> 
> It is also possible to have just some x-values against some y-values:
> 
> ```
> x(k) = line(k; x1; ...; xn)
> y(k) = line(k; y1; ...; yn)
> ```
> 
> Then, you can define f(x) as follows:
> 
> ```
> k(ξ) = $Root{x(k) = ξ @ k = 1 : n}
> f(x) = y(k(x))
> ```
> 
> Please, check this example that interpolates wind load values against height above ground level: https://github.com/Proektsoftbg/Calcpad/blob/main/Examples/Demos/Interpolation.cpd

In this example, You listed several colors. I understand the sequence of plotting lines is fixed. Why not give a list in Help file of all the colors' name?

**Comment by idealkindom** [comment]
> @hildebrandopsj Yes, sure.
> 
> You can apply any kind of transformation that maps x ∈ [a; b] to k ∈ [1; n] as a function. In your case, `k(x) = 0.1*x + 1` Then call: `f_2(x) = line(k(x); ...)` or simply `f_2(x) = line(0.1*x + 1; ...)` For k(x), you will get:
> 
> ```
> k(0) = 0.1*0 + 1 = 1
> k(40) = 0.1*40 + 1 = 4 + 1 = 5
> ```
> 
> It is also possible to have just some x-values against some y-values:
> 
> ```
> x(k) = line(k; x1; ...; xn)
> y(k) = line(k; y1; ...; yn)
> ```
> 
> Then, you can define f(x) as follows:
> 
> ```
> k(ξ) = $Root{x(k) = ξ @ k = 1 : n}
> f(x) = y(k(x))
> ```
> 
> Please, check this example that interpolates wind load values against height above ground level: https://github.com/Proektsoftbg/Calcpad/blob/main/Examples/Demos/Interpolation.cpd

Another problem about this problem is that when output a docx file, the line colors in the plot is OK, but the line colors after the functions are not OK. Instead, they are all dark.

**Comment by Proektsoftbg** [comment]
@idealkindom Chart colors are:
Red
Green
Blue
Goldenrod
Magenta
DarkCyan
Purple
DarkOrange
Maroon
YellowGreen

https://github.com/Proektsoftbg/Calcpad/blob/a315b0acc944faf5c9040bb323d2fbcbc123abe9/Calcpad.Core/Plotter/ChartPlotter.cs#L207

In the latest versions, we improved the convertion of Html formatting to Word. If you try the example from this blog post, it will preserve colors:

https://calcpad.blog/2023/04/30/how-to-add-title-labels-and-legend-to-a-calcpad-plot/

<img width="636" alt="image" src="https://github.com/Proektsoftbg/Calcpad/assets/90918363/c24bfcec-bf54-4e01-acd0-87d1f0514a2f">

Anyway, more plotting options were already promised and will be done. :)

**Comment by idealkindom** [comment]
Very interesting, I used Fuchasia for Magenta, and orange for Goldenrod, it also works. The problem only exits with the output docx file. I tested with the  installer  in the setup directory, which was built about 2 days back.

The codes are here:




"Interpolation

'<h4>Data functions in Calcpad</h4>

f_1(x) = take(x; 9; 2; -1; 1; 4.5; 6; -4)' - discrete values (vector) <span style="color:blue;">▬▬</span>

f_2(x) = line(x; 9; 2; -1; 1; 4.5; 6; -4)' - linear interpolation <span style="color:green;">▬▬</span>

f_3(x) = spline(x; 9; 2; -1; 1; 4.5; 6; -4)' - Hermite spline interpolation <span style="color:red;">▬▬</span>

f_4(x) = spline(x; 8; 1.8; -1; 1; 4.; 5; -3)' - Hermite spline interpolation <span style="color:orange;">▬▬</span>

f_5(x) = spline(x; 7; 1.5; -1; 1; 4.; 4; -4.5)' - Hermite spline interpolation <span style="color:Fuchsia;">▬▬</span>

f_6(x) = spline(x; 7.5; 1.2; -2; 1.2; 4.2; 4.3; -4.1)' - Hermite spline interpolation <span style="color:Jungle;">▬▬</span>

' 

$Plot{f_3(x) & f_2(x) & f_1(x) & f_4(x) & f_5(x) & f_6(x) @ x = 1 : 7}

'<table class="borderless">

'<thead>

'<tr><th>函数</th><th>图例</th></tr>

'</thead>

'<tbody>

'<tr><td>''f<sub>1</sub>(x)''</td><td><span style="color:blue;">▬▬</span></td></tr>

'<tr><td>''f<sub>2</sub>(x)''</td><td><span style="color:green;">▬▬</span></td></tr>

'<tr><td>''f<sub>3</sub>(x)''</td><td><span style="color:red;">▬▬</span></td></tr>

'<tr><td>''f<sub>4</sub>(x)''</td><td><span style="color:orange;">▬▬</span></td></tr>

'<tr><td>''f<sub>5</sub>(x)''</td><td><span style="color:fuchsia;">▬▬</span></td></tr>

'</tbody>

'</table>
















At 2023-09-30 04:32:48, "Ned Ganchovski" ***@***.***> wrote:

@idealkindom Chart colors are:
Red
Green
Blue
Goldenrod
Magenta
DarkCyan
Purple
DarkOrange
Maroon
YellowGreen

https://github.com/Proektsoftbg/Calcpad/blob/a315b0acc944faf5c9040bb323d2fbcbc123abe9/Calcpad.Core/Plotter/ChartPlotter.cs#L207

In the latest versions, we improved the convertion of Html formatting to Word. If you try the example from this blog post, it will preserve colors:

https://calcpad.blog/2023/04/30/how-to-add-title-labels-and-legend-to-a-calcpad-plot/

Anyway, more plotting options were already promised and will be done. :)

**Comment by Proektsoftbg** [comment]
@idealkindom This is because you use `<span>`. Replace all spans with `<b>` and the colors will appear.
For some reason `<span>` is not pocessed. Probably because it is not a formatting tag and before colors, it was not doing anything. I will fix that, thank you.

**Comment by idealkindom** [comment]
Thks a lot.
















At 2023-09-30 22:35:12, "Ned Ganchovski" ***@***.***> wrote:

@idealkindom This is because you use <span>. Replace all spans with <b> and the colors will appear.
For some reason <span> is not pocessed. Probably because it is not a formatting tag and before colors, it was not doing anything. I will fix that, thank you.
