### ISSUE TITLE
The incovnience due to angle unit of deg in calculation 

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#213]
The following code looks like to run without any problem:
a = 1m
b = a|cm
γ = atan(a/b)*deg

however, if the substitution process is coserved, the"*",i.e., mutiplier operator always appear, making it look so strange.
That why I suggest to introduce a mechanism to let unit angle with rad as default, which means all the real number could be an angle in radian, while in deg should be transformed.

**Comment by Proektsoftbg** [comment]
Hi!

Yes, this is possible. Write your code as follows:
```
#hide
ReturnAngleUnits = 1
#rad
#show
a = 1m
b = a|cm
γ = atan(a/b)|deg
```
This will return by default in radians, unless you transform it to degrees with `|deg`.
<img width="193" alt="image" src="https://github.com/Proektsoftbg/Calcpad/assets/90918363/15a0d2e9-8d47-4293-bd09-ab47648d7dc6">

**Comment by idealkindom** [comment]
> Hi!
> 
> Yes, this is possible. Write your code as follows:
> 
> ```
> #hide
> ReturnAngleUnits = 1
> #rad
> #show
> a = 1m
> b = a|cm
> γ = atan(a/b)|deg
> ```
> 
> This will return by default in radians, unless you transform it to degrees with `|deg`. <img alt="image" width="193" src="https://user-images.githubusercontent.com/90918363/273391085-15a0d2e9-8d47-4293-bd09-ab47648d7dc6.png">

Very nice. I have not noticed there is a function of "ReturnAngleUnits".Thks a lot.

**Comment by Proektsoftbg** [comment]
No problem! You are always welcome.
