### ISSUE TITLE
Color  works in 6.1.5 corrupted in 6.1.6

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#214]
1. The code is here:
```
"Interpolation
'<h4>Data functions in Calcpad</h4>
f_1(x) = take(x; 9; 2; -1; 1; 4.5; 6; -4)' - discrete values (vector) <b style="color:blue;">▬▬</b>
f_2(x) = line(x; 9; 2; -1; 1; 4.5; 6; -4)' - linear interpolation <b style="color:green;">▬▬</b>
f_3(x) = spline(x; 9; 2; -1; 1; 4.5; 6; -4)' - Hermite spline interpolation <b style="color:red;">▬▬</b>
f_4(x) = spline(x; 8; 1.8; -1; 1; 4.; 5; -3)' - Hermite spline interpolation <b style="color:orange;">▬▬</b>
f_5(x) = spline(x; 7; 1.5; -1; 1; 4.; 4; -4.5)' - Hermite spline interpolation <b style="color:Fuchsia;">▬▬</b>
f_6(x) = spline(x; 7.5; 1.2; -2; 1.2; 4.2; 4.3; -4.1)' - Hermite spline interpolation <b style="color:Jungle;">▬▬</b>
'<!--'PlotHeight = 250','PlotWidth = 400'--> 
$Plot{f_3(x) & f_2(x) & f_1(x) & f_4(x) & f_5(x) & f_6(x) @ x = 1 : 7}
'<table class="borderless">
'<thead>
'<tr><th>函数</th><th>图例</th></tr>
'</thead>
'<tbody>
'<tr><td>''f<sub>1</sub>(x)''</td><td><b style="color:blue;">▬▬</b></td></tr>
'<tr><td>''f<sub>2</sub>(x)''</td><td><b style="color:green;">▬▬</b></td></tr>
'<tr><td>''f<sub>3</sub>(x)''</td><td><b style="color:red;">▬▬</b></td></tr>
'<tr><td>''f<sub>4</sub>(x)''</td><td><b style="color:orange;">▬▬</b></td></tr>
'<tr><td>''f<sub>5</sub>(x)''</td><td><b style="color:fuchsia;">▬▬</b></td></tr>
'</tbody>
'</table>
```

2. the output screenshot on Calcpad 6.1.5:
![image](https://github.com/Proektsoftbg/Calcpad/assets/18344868/a362aa7a-760f-4b2c-9230-85c1399a2b07)

**Comment by idealkindom** [comment]
> Please, when you post a code, select it all and click <> on the toolbar in GitHub to make it a code block. Otherwise, it is rendered as Html. Now I did it for you to see how it looks.

`"Interpolation
'<h4>Data functions in Calcpad</h4>
f_1(x) = take(x; 9; 2; -1; 1; 4.5; 6; -4)' - discrete values (vector) <b style="color:blue;">▬▬</b>
f_2(x) = line(x; 9; 2; -1; 1; 4.5; 6; -4)' - linear interpolation <b style="color:green;">▬▬</b>
f_3(x) = spline(x; 9; 2; -1; 1; 4.5; 6; -4)' - Hermite spline interpolation <b style="color:red;">▬▬</b>
f_4(x) = spline(x; 8; 1.8; -1; 1; 4.; 5; -3)' - Hermite spline interpolation <b style="color:orange;">▬▬</b>
f_5(x) = spline(x; 7; 1.5; -1; 1; 4.; 4; -4.5)' - Hermite spline interpolation <b style="color:Fuchsia;">▬▬</b>
f_6(x) = spline(x; 7.5; 1.2; -2; 1.2; 4.2; 4.3; -4.1)' - Hermite spline interpolation <b style="color:Jungle;">▬▬</b>
' 
$Plot{f_3(x) & f_2(x) & f_1(x) & f_4(x) & f_5(x) & f_6(x) @ x = 1 : 7}
'<table class="borderless">
'<thead>
'<tr><th>函数</th><th>图例</th></tr>
'</thead>
'<tbody>
'<tr><td>''f<sub>1</sub>(x)''</td><td><b style="color:blue;">▬▬</b></td></tr>
'<tr><td>''f<sub>2</sub>(x)''</td><td><b style="color:green;">▬▬</b></td></tr>
'<tr><td>''f<sub>3</sub>(x)''</td><td><b style="color:red;">▬▬</b></td></tr>
'<tr><td>''f<sub>4</sub>(x)''</td><td><b style="color:orange;">▬▬</b></td></tr>
'<tr><td>''f<sub>5</sub>(x)''</td><td><b style="color:fuchsia;">▬▬</b></td></tr>
'</tbody>
'</table>
`

**Comment by Proektsoftbg** [comment]
And still, it is not clear what is corrupted in 6.1.6. Your screenshot shows 6.1.5 and it is fine. In 6.1.6 I see almost the same, except for the green window background which probably comes from the Windows theme.

![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/be25c396-16f8-4e85-b5cb-4c78725839ca)

Can you please, be more specific. No one sees what you see. Show a screen what is corrupted and not what is fine. Explain in a few words what do you expect, what do you get and what is actually wrong with it.

**Comment by Proektsoftbg** [comment]
Hi, I saw you posted the code. It is still not exactly what we need. Code block in GitHub is three apostrophes on the line before the code and three - on the line after the code.:
```
"Interpolation
'<h4>Data functions in Calcpad</h4>
f_1(x) = take(x; 9; 2; -1; 1; 4.5; 6; -4)' - discrete values (vector) <b style="color:blue;">▬▬</b>
...
```
One apostrophe is an inline code and we lose the lines.

**Comment by idealkindom** [comment]
> And still, it is not clear what is corrupted in 6.1.6. Your screenshot shows 6.1.5 and it is fine. In 6.1.6 I see almost the same, except for the green window background which probably comes from the Windows theme.
> 
> ![image](https://user-images.githubusercontent.com/90918363/273577451-be25c396-16f8-4e85-b5cb-4c78725839ca.png)
> 
> Can you please, be more specific. No one sees what you see. Show a screen what is corrupted and not what is fine. Explain in a few words what do you expect, what do you get and what is actually wrong with it.

I press F4 then F5 to run the code， but everytime it crash and close out.So I don't know what results it gave out. I run the same piece of code on my work PC,which is an old win7 PC, it could run but all the lines are black.

**Comment by idealkindom** [comment]
> Hi, I saw you posted the code. It is still not exactly what we need. Code block in GitHub is three apostrophes on the line before the code and three - on the line after the code.:
> 
> ```
> "Interpolation
> '<h4>Data functions in Calcpad</h4>
> f_1(x) = take(x; 9; 2; -1; 1; 4.5; 6; -4)' - discrete values (vector) <b style="color:blue;">▬▬</b>
> ...
> ```
> 
> One apostrophe is an inline code and we lose the lines. I am sorry to bother you, but this will really make our work easier in the future.

How about now:
'''"Interpolation
'<h4>Data functions in Calcpad</h4>
f_1(x) = take(x; 9; 2; -1; 1; 4.5; 6; -4)' - discrete values (vector) <b style="color:blue;">▬▬</b>
f_2(x) = line(x; 9; 2; -1; 1; 4.5; 6; -4)' - linear interpolation <b style="color:green;">▬▬</b>
f_3(x) = spline(x; 9; 2; -1; 1; 4.5; 6; -4)' - Hermite spline interpolation <b style="color:red;">▬▬</b>
f_4(x) = spline(x; 8; 1.8; -1; 1; 4.; 5; -3)' - Hermite spline interpolation <b style="color:orange;">▬▬</b>
f_5(x) = spline(x; 7; 1.5; -1; 1; 4.; 4; -4.5)' - Hermite spline interpolation <b style="color:Fuchsia;">▬▬</b>
f_6(x) = spline(x; 7.5; 1.2; -2; 1.2; 4.2; 4.3; -4.1)' - Hermite spline interpolation <b style="color:Jungle;">▬▬</b>

$Plot{f_3(x) & f_2(x) & f_1(x) & f_4(x) & f_5(x) & f_6(x) @ x = 1 : 7}
'<table class="borderless">
'<thead>
'<tr><th>函数</th><th>图例</th></tr>
'</thead>
'<tbody>
'<tr><td>''f<sub>1</sub>(x)''</td><td><b style="color:blue;">▬▬</b></td></tr>
'<tr><td>''f<sub>2</sub>(x)''</td><td><b style="color:green;">▬▬</b></td></tr>
'<tr><td>''f<sub>3</sub>(x)''</td><td><b style="color:red;">▬▬</b></td></tr>
'<tr><td>''f<sub>4</sub>(x)''</td><td><b style="color:orange;">▬▬</b></td></tr>
'<tr><td>''f<sub>5</sub>(x)''</td><td><b style="color:fuchsia;">▬▬</b></td></tr>
'</tbody>
'</table>
'''

**Comment by idealkindom** [comment]
I clicked "<>" and put the code between ``
`"Interpolation
'<h4>Data functions in Calcpad</h4>
f_1(x) = take(x; 9; 2; -1; 1; 4.5; 6; -4)' - discrete values (vector) <b style="color:blue;">▬▬</b>
f_2(x) = line(x; 9; 2; -1; 1; 4.5; 6; -4)' - linear interpolation <b style="color:green;">▬▬</b>
f_3(x) = spline(x; 9; 2; -1; 1; 4.5; 6; -4)' - Hermite spline interpolation <b style="color:red;">▬▬</b>
f_4(x) = spline(x; 8; 1.8; -1; 1; 4.; 5; -3)' - Hermite spline interpolation <b style="color:orange;">▬▬</b>
f_5(x) = spline(x; 7; 1.5; -1; 1; 4.; 4; -4.5)' - Hermite spline interpolation <b style="color:Fuchsia;">▬▬</b>
f_6(x) = spline(x; 7.5; 1.2; -2; 1.2; 4.2; 4.3; -4.1)' - Hermite spline interpolation <b style="color:Jungle;">▬▬</b>

$Plot{f_3(x) & f_2(x) & f_1(x) & f_4(x) & f_5(x) & f_6(x) @ x = 1 : 7}
'<table class="borderless">
'<thead>
'<tr><th>函数</th><th>图例</th></tr>
'</thead>
'<tbody>
'<tr><td>''f<sub>1</sub>(x)''</td><td><b style="color:blue;">▬▬</b></td></tr>
'<tr><td>''f<sub>2</sub>(x)''</td><td><b style="color:green;">▬▬</b></td></tr>
'<tr><td>''f<sub>3</sub>(x)''</td><td><b style="color:red;">▬▬</b></td></tr>
'<tr><td>''f<sub>4</sub>(x)''</td><td><b style="color:orange;">▬▬</b></td></tr>
'<tr><td>''f<sub>5</sub>(x)''</td><td><b style="color:fuchsia;">▬▬</b></td></tr>
'</tbody>
'</table>
`

**Comment by idealkindom** [comment]
```"Interpolation
'<h4>Data functions in Calcpad</h4>
f_1(x) = take(x; 9; 2; -1; 1; 4.5; 6; -4)' - discrete values (vector) <b style="color:blue;">▬▬</b>
f_2(x) = line(x; 9; 2; -1; 1; 4.5; 6; -4)' - linear interpolation <b style="color:green;">▬▬</b>
f_3(x) = spline(x; 9; 2; -1; 1; 4.5; 6; -4)' - Hermite spline interpolation <b style="color:red;">▬▬</b>
f_4(x) = spline(x; 8; 1.8; -1; 1; 4.; 5; -3)' - Hermite spline interpolation <b style="color:orange;">▬▬</b>
f_5(x) = spline(x; 7; 1.5; -1; 1; 4.; 4; -4.5)' - Hermite spline interpolation <b style="color:Fuchsia;">▬▬</b>
f_6(x) = spline(x; 7.5; 1.2; -2; 1.2; 4.2; 4.3; -4.1)' - Hermite spline interpolation <b style="color:Jungle;">▬▬</b>

$Plot{f_3(x) & f_2(x) & f_1(x) & f_4(x) & f_5(x) & f_6(x) @ x = 1 : 7}
'<table class="borderless">
'<thead>
'<tr><th>函数</th><th>图例</th></tr>
'</thead>
'<tbody>
'<tr><td>''f<sub>1</sub>(x)''</td><td><b style="color:blue;">▬▬</b></td></tr>
'<tr><td>''f<sub>2</sub>(x)''</td><td><b style="color:green;">▬▬</b></td></tr>
'<tr><td>''f<sub>3</sub>(x)''</td><td><b style="color:red;">▬▬</b></td></tr>
'<tr><td>''f<sub>4</sub>(x)''</td><td><b style="color:orange;">▬▬</b></td></tr>
'<tr><td>''f<sub>5</sub>(x)''</td><td><b style="color:fuchsia;">▬▬</b></td></tr>
'</tbody>
'</table>
```

**Comment by idealkindom** [comment]
> Hi, I saw you posted the code. It is still not exactly what we need. Code block in GitHub is three apostrophes on the line before the code and three - on the line after the code.:
> 
> ```
> "Interpolation
> '<h4>Data functions in Calcpad</h4>
> f_1(x) = take(x; 9; 2; -1; 1; 4.5; 6; -4)' - discrete values (vector) <b style="color:blue;">▬▬</b>
> ...
> ```
> 
> One apostrophe is an inline code and we lose the lines. I am sorry to bother you, but this will really make our work easier in the future.

How about now:
```
"Interpolation
'<h4>Data functions in Calcpad</h4>
f_1(x) = take(x; 9; 2; -1; 1; 4.5; 6; -4)' - discrete values (vector) <b style="color:blue;">▬▬</b>
f_2(x) = line(x; 9; 2; -1; 1; 4.5; 6; -4)' - linear interpolation <b style="color:green;">▬▬</b>
f_3(x) = spline(x; 9; 2; -1; 1; 4.5; 6; -4)' - Hermite spline interpolation <b style="color:red;">▬▬</b>
f_4(x) = spline(x; 8; 1.8; -1; 1; 4.; 5; -3)' - Hermite spline interpolation <b style="color:orange;">▬▬</b>
f_5(x) = spline(x; 7; 1.5; -1; 1; 4.; 4; -4.5)' - Hermite spline interpolation <b style="color:Fuchsia;">▬▬</b>
f_6(x) = spline(x; 7.5; 1.2; -2; 1.2; 4.2; 4.3; -4.1)' - Hermite spline interpolation <b style="color:Jungle;">▬▬</b>

$Plot{f_3(x) & f_2(x) & f_1(x) & f_4(x) & f_5(x) & f_6(x) @ x = 1 : 7}
'<table class="borderless">
'<thead>
'<tr><th>function</th><th>legend</th></tr>
'</thead>
'<tbody>
'<tr><td>''f<sub>1</sub>(x)''</td><td><b style="color:blue;">▬▬</b></td></tr>
'<tr><td>''f<sub>2</sub>(x)''</td><td><b style="color:green;">▬▬</b></td></tr>
'<tr><td>''f<sub>3</sub>(x)''</td><td><b style="color:red;">▬▬</b></td></tr>
'<tr><td>''f<sub>4</sub>(x)''</td><td><b style="color:orange;">▬▬</b></td></tr>
'<tr><td>''f<sub>5</sub>(x)''</td><td><b style="color:fuchsia;">▬▬</b></td></tr>
'</tbody>
'</table>
```

**Comment by Proektsoftbg** [comment]
OK, thank you. Now this is more specific. This is not a color related problem. It is a different thing and it is not the normal way Calcpad works. Actually, colors are purely an Html feature. Calcpad does nothing about them, but adding this Html to the output and showing it in the Html viewer on the right "as is".

About crashes, maybe it is related to installation. Uninstall Calcpad completely. Then, download the latest release and make a clean install:
https://github.com/Proektsoftbg/Calcpad/releases/download/v6.1.6/calcpad-setup-en-x64.exe

Also, please make sure you install the latest .NET 7:
[https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.11-windows-x64-installer](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.11-windows-x64-installer)

Is your computer 32 or 64 bit? If 32 bit, install this instead:
[https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.11-windows-x86-installer](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.11-windows-x86-installer)

If it still does not work, goto:
c:\Users\<Your user name>\AppData\Local\Proektsoft_EOOD\
and delete everything.

These will reset the program settings to their defaults.

About Windows 7, maybe the problem is the older OS. It is not supported anymore by Microsoft, including .NET.
Anyway, if the rest is working, the problem may come from old browser capabilities. Try installing IE 11 at least:
https://download.microsoft.com/download/3/D/E/3DEF3F86-A862-470C-A1D0-2525419428AF/IE11-Windows6.1-x86-bg-bg.exe

If it does not work, install MS Edge.

**Comment by idealkindom** [comment]
> OK, thank you. Now this is more specific.
> 
> This is actually is not a color related problem. It is a different thing and it is not the normal way Calcpad works. Actually, colors are purely an Html feature. Calcpad does nothing about them, but adding this Html to the output and showing it in the Html viewer on the right "as is".
> 
> About crashes, maybe it is related to installation. Uninstall Calcpad completely. Then, download the latest release and make a clean install: https://github.com/Proektsoftbg/Calcpad/releases/download/v6.1.6/calcpad-setup-en-x64.exe
> 
> Also, please make sure you install the latest .NET 7: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.11-windows-x64-installer
> 
> Is your computer 32 or 64 bit? If 32 bit, install this instead: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.11-windows-x86-installer
> 
> If it still does not work, goto: c:\Users<Your user name>\AppData\Local\Proektsoft_EOOD and delete everything.
> 
> These will reset the program settings to their defaults.
> 
> About Windows 7, maybe the problem is the older OS. It is not supported anymore by Microsoft, including .NET. Anyway, if the rest is working, the problem may come from old browser capabilities. Try installing IE 11 at least: https://download.microsoft.com/download/3/D/E/3DEF3F86-A862-470C-A1D0-2525419428AF/IE11-Windows6.1-x86-bg-bg.exe
> 
> If it does not work, install MS Edge.

I downloaded All the code zip and find the install file. I tried delete the user file,this is a win 10 X64 PC, Microsoft Edge as web browser. However, it still crash in full screen mode.

**Comment by idealkindom** [comment]
Nothing, just crashed out. It could run normally with two windows open for sure.
















At 2023-10-09 20:59:43, "Ned Ganchovski" ***@***.***> wrote:

Hi! Thank you!

Do you get some message after that or a log file displayed?

**Comment by Proektsoftbg** [comment]
Aha! OK, thank you. Now I see where the problem is. Please, wait for a while...

**Comment by idealkindom** [comment]
Thks a lot.
















At 2023-10-09 21:03:54, "Ned Ganchovski" ***@***.***> wrote:

Aha! OK, thank you. Now I see where the problem is. Please, wait for a while...

**Comment by Proektsoftbg** [comment]
The problem is that you do not have input fields and compile to input form (what you call "full screen").

It crashes now, because it validates the input data in the latest version. I will fix that.

**Comment by idealkindom** [comment]
It's great that you diagnose it.
Another trivial problem is why everytime I click "new" icon on toolbar, it pop up reminds that I discard or save the present sheet?
I think the convinent logic is that the present worksheet turn to background, a new window of Calcpad is opened. How do you think?
















At 2023-10-09 21:08:22, "Ned Ganchovski" ***@***.***> wrote:

The problem is that you do not have input fields and compile to input form (what you call "full screen").

It crashes now, because it validates the input data in the latest version. I will fix that.

**Comment by Proektsoftbg** [comment]
Hi, crashing was fixed!

You can download  and install the latest version from:
https://github.com/Proektsoftbg/Calcpad/releases/download/v6.1.6/calcpad-setup-en-x64.exe

Since I did not update the revision letter, uninstall the old version, before installing the new one to make sure that everything is replaced properly.

**Comment by idealkindom** [comment]
Great news.

在 2023-10-09 23:25:25，"Ned Ganchovski" ***@***.***> 写道：


Hi, crashing was fixed!

You can download and install the latest version from:
https://github.com/Proektsoftbg/Calcpad/releases/download/v6.1.6/calcpad-setup-en-x64.exe

Since I did not update the revision letter, uninstall the old version, before installing the new one to make sure that everything is replaced properly.
