### ISSUE TITLE
Editing Units names "Labels"

### ISSUE THREAD

**Issue by Engbinsalah** [Proektsoftbg/Calcpad#216]
Hi, 
Thanks for this wonderful software that made calculations super easy. 

I would like to ask if it is possible to edit the units' labels, for example if I want to show in the calculation sheet the force units in US Customary units as 'kip' or 'k' instead of 'kipf' 
Do I have the option to edit? 

Regards,

**Comment by Proektsoftbg** [comment]
Hi!

There are different aliases of kip units in Calcpad: kip, kipf and kip_f. You can also define your own units/aliases by putting a dot before the name, e.g.: `.kips = kip`

![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/c42e7201-750e-460a-8d44-d8299027af50)

**Comment by Engbinsalah** [comment]
Hi, 

Thanks for your response, that is what I needed 

Regards
