### ISSUE TITLE
Confliction between atan and atan2

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#217]
With angle unit defaulted as deg, the built-in function of atan and atan2 gives out different angle units, the codes are as follows:
```
atan(1)
atan2(1; 1)
b = atan2(sqrt(3); 1)
b = atan2(sqrt(3); 1)|deg
atan2(1; sqrt(3))
```

**Comment by Proektsoftbg** [comment]
@idealkindom thank you for reporting this.

Yes, unlike other trig functions, `atan2` is not unit-aware. It returns the answer always in radians.
There was a reason for that, but now i cannot remember why we did so. I will try to recall.
In all cases, it is good to know that.

**Comment by idealkindom** [comment]
> @idealkindom thank you for reporting this.
> 
> Yes, unlike other trig functions, `atan2` is not unit-aware. It returns the answer always in radians. There was a reason for that, but now i cannot remember why we did so. I will try to recall. In all cases, it is good to know that.

How about reconcider my earlier suggestion that let radian or 1 be default for trigometric function, why deg is a unit that must be typed for recognition.

**Comment by Proektsoftbg** [comment]
OK. I made the atan2 function units aware to match the others.
https://github.com/Proektsoftbg/Calcpad/releases/tag/v6.1.7

I cannot find any reason why we have not changed it so far. Thank you for reporting this.

About making radians to be default and using  degrees explicitly, you can set it on your computer and work like this. There is no need to change anything in the program now. Also it is not good to restrict everybody to this only option. Lets users to be able to choose. For me personally, it is more convenient to have degrees by default.
