### ISSUE TITLE
Lenght of input boxes

### ISSUE THREAD

**Issue by hildebrandopsj** [Proektsoftbg/Calcpad#218]
Hi Ned,

It's possible to make the input boxes in the form adjustable? In my recent worksheet some values have five decimal places.

![image](https://github.com/Proektsoftbg/Calcpad/assets/86059123/62a38eee-5f24-4979-98b8-21110ef125fb)

**Comment by Proektsoftbg** [comment]
Hi! @hildebrandopsj! This is easy to do with a little css. 

If you want to set all input boxes, just add the following line on the top of your worksheet:
`'<style>input[type=text] {width:80pt;}</style>`

If you want to set just some of the boxes, then, the line should become as follows:
`'<style>.w80 input[type=text] {width:80pt;}</style>`

Further in the text, enclose the input boxes you want into paragraphs with class="w80":
`'<p class="w80">'L = ? {1}' - length of beam</p>`

For example, this is what happens with the cubic equation worksheet:
```
'<style>.w80 input[type=text] {width:80pt;}</style>
"Cubic Equation
'<hr/>
f(x) = x^3 + a*x^2 + b*x + c'= 0
'Coefficients:
a = ? {-6}
b = ? {11}
'<p class="w80">'c = ? {-6}'</p> 
```

![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/b41b41d2-0a80-41a4-8ebc-87ee1846ace4)

**Comment by hildebrandopsj** [comment]
Thank you! It worked!
