### ISSUE TITLE
Now it's failing on Ctrl+F

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#22]
Version 5.7.1 crashes when trying to call the search from the menu or by Ctrl+F (it doesn't matter what is open or written in the text field)

**Comment by Proektsoftbg** [comment]
Uh, thank you very much! I saw it right away. It is fixed now. 
I amended the same release 5.7.1. You can download and reinstall it again. Uninstall the previous one before that.

**Comment by cser** [comment]
Yeh, works now!
