### ISSUE TITLE
Self-deploy calcpad online ide

### ISSUE THREAD

**Issue by 164K** [Proektsoftbg/Calcpad#222]
Is the calcpad online ide opensource? I want to deploy it on my own server, so that I can access it on all platform.

**Comment by Proektsoftbg** [comment]
Sorry, currently the web version is not available open source. 
We have not actually decided what to do with it and there is still a lot of work. 

Probably, you can consider some remote desktop of app streaming solution to use the desktop version.
Anyway, once we port the UI to Avalonia, the full Calcpad will be available for all platforms.

**Comment by 164K** [comment]
Thanks for your response! Wish all the best for your project.
