### ISSUE TITLE
3 questions to ask

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#227]
1、 How to define a variable with double levels of subscriptes?Before Calcpad support Matrix calculation, is it possible to support dynamic subscript, such as  a_[i], with i=1,...,n.

2、When I open multiple windows of Caclapd, the PC always get stuck.

3、Is it possible to support string as varible value, for example Steel =I14 or I18,I19, then those section specifications could be defined as function of section type.

**Comment by Proektsoftbg** [comment]
Hi!

1. You cannot define multiple level subscripts. Use comma instead, e.g. `a_k,1`. Actually, the "second level" is reserved for indices of  vectors and matrices. Actually, what you call "dynamic subscript" is simply a vector index. We need to have vectors implemented internally to use such option. What we can do about this is to develop vectors first (they are quite ahead) and release them with basic features and then, the rest. At least, defining a vector, storing and reading a value by index.

2. Probably you are running out of resources. How many windows you have, when this happens and what are your computer specs. Please note that .NET 7.0 does not support Windows 7 and older and may consume a lot of memory. We noticed that, but cannot explain why.

3. You can use macro variables for this purpose: Steel$ = I14. But you cannot use strings in calculations or comparisons like: `#if s == I14`. So, use just numbers to identify types and finally, attach them to the text with #val:

Section = 14
#val
'Section type: I'Section
#equ

That is how I make specifications.

**Comment by idealkindom** [comment]
Now I understand.My working PC is win7. Since I tried to use I14 as argument but with failure, I transfer to 14. I tried this because long experience of using Maxima.

Wish the features of vectors and matrices come soon.

在 2023-11-03 00:11:45，"Ned Ganchovski" ***@***.***> 写道：


Hi!

You cannot define multiple level subscripts. Use comma instead, e.g. a_k,1. Actually, the "second level" is reserved for indices of vectors and matrices. Actually, what you call "dynamic subscript" is simply a vector index. We need to have vectors implemented internally to use such option. What we can do about this is to develop vectors first (they are quite ahead) and release them with basic features and then, the rest. At least, defining a vector, storing and reading a value by index.

Probably you are running out of resources. How many windows you have, when this happens and what are your computer specs. Please note that .NET 7.0 does not support Windows 7 and older and may consume a lot of memory. We noticed that, but cannot explain why.

You can use macro variables for this purpose: Steel$ = I14. But you cannot use strings in calculations or comparisons like: #if s == I14. So, use just numbers to identify types and finally, attach them to the text with #val:

Section = 14
#val
'Section type: I'Section
#equ

That is how I make specifications.

**Comment by Proektsoftbg** [comment]
OK. I will try my best. :)
