### ISSUE TITLE
Unit symbol on "Deg" to "Rad or "Gra"

### ISSUE THREAD

**Issue by BasilioPV** [Proektsoftbg/Calcpad#228]
Changing from "Deg" to "Rad or "Gra"
<img width="89" alt="image" src="https://github.com/Proektsoftbg/Calcpad/assets/93596576/f6dfdba6-621e-4033-8ed8-8706ec3fcc16">

Puts the same unit symbol on the result " º ", instead of " º ", " rad " and " grad "

**Comment by Proektsoftbg** [comment]
Hi! Can you please share your code?

Are there any additional settings in the worksheet like #deg or native units attached>

**Comment by BasilioPV** [comment]
Sorry, I'ts my mistake, the units are just a text string. I'm newby on your program :-)

But: Why angle units are not shown?:
![image](https://github.com/Proektsoftbg/Calcpad/assets/93596576/1b24c5af-4515-410e-9e9c-495ffe55964f)

**Comment by Proektsoftbg** [comment]
Returning angles in units is optional. One may not want to use units in his/her worksheets at all and it is not obligatory.
So, you have to define:

`ReturnAngleUnits = 1`

in the beginning of your code to get angles returned with units.

**Comment by BasilioPV** [comment]
Excellent! thanks!
