### ISSUE TITLE
Large equations in a break line

### ISSUE THREAD

**Issue by BasilioPV** [Proektsoftbg/Calcpad#234]
When using large equations, the break point cuts the equation at the middle with ugly output. It is possible to cut the equation by the latest equal and, in the next line, start with a tab the equation??

<img width="1142" alt="image" src="https://github.com/Proektsoftbg/Calcpad/assets/93596576/0a3d8310-77b3-4a39-b9bb-6bbf7c5464ea">

Obiusly, if the equation is very large, there is no option to break it...

**Comment by Proektsoftbg** [comment]
Hi! Thank you this is a good idea.

Yes, we can do that very easy. We will introduce a variable `LineLength`. If you assign a value to it, say `LineLength = 80`, it will break all equations that will output more symbols. Otherize, Calcpad will not know if the equation will fit or not, because the rendering is actually performed in the browser.

**Comment by BasilioPV** [comment]
It perfect for me! Thanks!

**Comment by Proektsoftbg** [comment]
This is what I can do very quickly. It is related to previous discussions #199 and #226 about introducing optional substitution switches inside worksheets. With a short additional macro, this can solve also your issue until we implement it natively. Is this what you need for splitting equations?

![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/0cf63a31-d96c-4506-957f-155fb34b9c53)

**Comment by BasilioPV** [comment]
Yes, it's fine for me! Thanks!

**Comment by BasilioPV** [comment]
#def eq_split$(eq$)
#hide
eq$
#show
#noc
eq$'<span class="eq"> =</span>
#equ
#novar
'&emsp;&emsp;<span class="eq"> =</span>'eq$
#varsub
#end def

"Longitudinal Resistance<hr/><small>According to <strong>CSR</strong></small>
'<div style="max-width:180mm">
'<p class="ref">[CSR P1 CH1 S4]</p>
'Rule Length : 'L = ? {73.2864}m
'<p class="ref">[CSR P1 CH1 S4]</p>
'Moulded breadth of ship : 'B = ? {17}m
'<p class="ref">[CSR P1 CH1 S4]</p>
'Block coefficient at draught T<sub>SC</sub> : 'C_B = ? {0.8646}
#post
#If L < 90m
'For L < 90 m:
'<p class="ref">[LR Ship Rules]</p>
C_w = 0.0412m^-1*L + 4
#Else If (L ≥ 90m) ∧ (L ≤ 300m)
'For L >= 90 m and L <= 300 m:
'<p class="ref">[CSR P1 CH1 S4]</p>
C_w = 10.75 - ((300m - L)/100m)^1.5
#Else If (L ≥ 300m) ∧ (L ≤ 350m)
'For L >= 300 m and L <= 350 m:
'<p class="ref">[CSR P1 CH1 S4]</p>
C_w = 10.75
#Else
'For L > 350 m:
'<p class="ref">[CSR P1 CH1 S4]</p>
C_w = 10.75 - ((L - 350m)/150m)^1.5
#end if

'<p class="ref">[CSR P1 CH4 S4]</p>
'Vertical hogging wave bending moment amidships : '
eq_split$(M_WV_h_mid = 0.19*1*1*1*C_w*L^2*B*C_B*(1kNm/1m^3)|kNm)

**Comment by Proektsoftbg** [comment]
This is the next version 6.1.9. You still do not have it, because for now it exists only on my computer :). Let me make a few more tweaks and tests and I will publish it, probably tomorrow.

**Comment by BasilioPV** [comment]
Thanks!

**Comment by Proektsoftbg** [comment]
Hi!

I released this version 6.1.9:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v6.1.9

You can use the new features for variable substitution control to shorten your equations of split them in two lines. You can use the code bellow.

Macro for splitting equations:
```
#def eq_split$(eq$)
#hide
eq$
#show
#noc
eq$'<span class="eq"> =</span>
#equ
#novar
'&emsp;&emsp;<span class="eq"> =</span>'eq$
#varsub
#end def
```
Usage:
```
'Variables
a = 10m/s^2
m = 20t
'Equation
#nosub
'No substitution, only variables - #nosub
F = m*a|kip
#novar
'No variables, only substitution - #novar
F = m*a|kip
#varsub
'Variables and substitution - #varsub
F = m*a|kip
'Spit equation - eq_split $ (eq $)
eq_split$(F = m*a|kip)
F
```

**Comment by BasilioPV** [comment]
Hi!
This works well in Calcpad! But the export to word are missing the last and first equal on a line break?¿

![image](https://github.com/Proektsoftbg/Calcpad/assets/93596576/13e31aa9-2639-47e7-87a8-fd084021a471)

On word:

![image](https://github.com/Proektsoftbg/Calcpad/assets/93596576/2241830f-16db-43c8-aa1a-93f0b106ac64)

**Comment by Proektsoftbg** [comment]
OK, I see. Then do not put <span class=eq></span> around the equal sign "=". So, the macro will become.

```
#def eq_split$(eq$)
#hide
eq$
#show
#noc
eq$'=
#equ
#novar
'&emsp;&emsp;='eq$
#varsub
#end def
```
Btw, Word should split long equations automatically, so if you finally will export everything to Word, it is not necessary to split them in Calcpad.

**Comment by BasilioPV** [comment]
Thanks! Now is fully working!

**Comment by Proektsoftbg** [comment]
OK, this is what I figured out about splitting longer equations in a better looking way:

![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/df02bd64-81d7-4c8c-ae86-9a56901b082f)

Just add `#split` before the equations you want to split and `#wrap` to restore the default behavior. It is simple and much easier than the above solution. If OK, I can include it in the next release 6.2.0.

**Comment by BasilioPV** [comment]
Thanks! Solved!
