### ISSUE TITLE
Plot equation defined on intervals

### ISSUE THREAD

**Issue by BasilioPV** [Proektsoftbg/Calcpad#236]
I need to plot a function defined by intervals:

<img width="320" alt="image" src="https://github.com/Proektsoftbg/Calcpad/assets/93596576/b900a95a-16dc-4cd0-b1f1-960b51a92490">

Is it possible on Calcpad?

**Comment by Proektsoftbg** [comment]
Yes, this is very easy with Calcpad. Just use the switch function. Here is an example:
```
f_sw(x; L) = switch(x ≤ 0 ∨ x ≥ L; 0; x ≤ 0.1*L; 1.5*x/L; x ≥ 0.9*L; 1.5*(L - x)/L; x ≥ 0.3*L ∧ x ≤ 0.7*L; 1)
$Plot{f_sw(x; 5) @ x = 0 : 5}
```
Another, even more elegant way is to use the Calcpad's internal line interpolation function:
```
x(k; L) = line(k; 0; 0.1; 0.3; 0.7; 0.9; 1)*L'- x-values
y(k) = line(k; 0; 0.15; 1; 1; 0.15; 0)'- y-values
k_x(x; L) = $Root{x(k; L) - x @ k = 1 : 6}
f_sw(x; L) = y(k_x(x; L))
$Plot{f_sw(x; 5) @ x = 0 : 5}
```
They both will produce the same result:
![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/02b785b4-40e7-4b46-9b94-824848938bce)

**Comment by BasilioPV** [comment]
Great!! Thanks!!

**Comment by BasilioPV** [comment]
On this code:

K = 5m
f_sw(x; L) = switch(x ≤ 0 ∨ x ≥ L; 0; x ≤ 0.1*L; 1.5*x/L; x ≥ 0.9*L; 1.5*(L - x)/L; x ≥ 0.3*L ∧ x ≤ 0.7*L; 1)
$Plot{f_sw(x; K) @ x = 0 : K}

Has the output:

<img width="545" alt="image" src="https://github.com/Proektsoftbg/Calcpad/assets/93596576/e07d5d55-10f3-480e-a3a4-2e804897beab">

What are I missing? Thanks

**Comment by BasilioPV** [comment]
this workaround works:
<img width="673" alt="image" src="https://github.com/Proektsoftbg/Calcpad/assets/93596576/661355dd-eed8-426e-812b-dcdbb49c6b84">

<img width="405" alt="image" src="https://github.com/Proektsoftbg/Calcpad/assets/93596576/c92c90d2-e7b1-4ac4-8802-2cb554527a03">

Only non-dimensional values can be plotted?

**Comment by Proektsoftbg** [comment]
Both limits in the plot function have to be of consistent dimensions (not necessarily equal, but convertible to each other). So, you have to write:

`$Plot{f_sw(x; K) @ x = 0m : K}`

5m and unitless zero are not consistent.

**Comment by BasilioPV** [comment]
Still not work after "0m" change. Can you test it?

**Comment by Proektsoftbg** [comment]
This applied for all other zeros. Also, I think you forgot the multiplications between numbers and 'L' In this way, 'L' becomes unit 'liters'. Here is the correct code:
```
K = 5m
f_sw(x; L) = switch(x ≤ 0m ∨ x ≥ L; 0; x ≤ 0.1*L; 1.5*x/L; x ≥ 0.9*L; 1.5*(L - x)/L; x ≥ 0.3*L ∧ x ≤ 0.7*L; 1)
$Plot{f_sw(x; K) @ x = 0m : K}
```

**Comment by BasilioPV** [comment]
Ok! Thanks!
