### ISSUE TITLE
Select Data Target

### ISSUE THREAD

**Issue by hildebrandopsj** [Proektsoftbg/Calcpad#24]
Hi,

I trying to create a selection list to a variable called fck, but indepent of the selection made it bring the results of previous variables:

![image](https://user-images.githubusercontent.com/86059123/177216601-16c03521-c0c1-46e0-8385-e9d7474df76f.png)
![image](https://user-images.githubusercontent.com/86059123/177216491-1355714e-9eb2-434c-9ae3-01e991a07307.png)

Here is the code:
```
'<h3> Dimensionamento de Seções</h3>'
'<hr />
'<h4>Materiais</h4>'
'<h5>Coeficientes de Ponderação</h5>'
'Coeficiente de minoração do aço
γ_s = ? 
'Coeficiente de minoração do concreto
γ_c = ? 
'<h4>Concreto</h4>'
#pre
'<p>Escolha o fck - 
'<select data-target="fck">
'<option value=15>C15</option>
'<option value=18>C18</option>
'<option value=20>C20</option>
'<option value=25>C25</option>
'<option value=30>C30</option>
'<option value=35>C35</option>
'<option value=40>C40</option>
'<option value=45>C45</option>
'<option value=50>C50</option>
'<option value=55>C55</option>
'<option value=60>C60</option>
'<option value=65>C65</option>
'<option value=70>C70</option>
'<option value=75>C75</option>
'<option value=80>C80</option>
'<option value=85>C85</option>
'<option value=90>C90</option>
'</select></p>
#post
'<table id="fck">
'<tr><td>'f_ck = ? '</td></tr>
'</table>
f_cd = f_ck/γ_c
α_v2 = 1 - f_ck/250
#if f_ck ≤ 50
f_ctm = 0.3*f_ck^(2/3)
#else
f_ctm = 2.12*ln(1 + 0.11*f_ck)
#end if
```
Someone can tell me what i'm doing wrong?

Best regards

**Comment by GreatApo** [comment]
> Someone can tell me what i'm doing wrong?
> 
> Best regards

The input needs to be created in the pre state so that the value is assigned, then you need to start the post process

```
#show
'<table id="fck">
'<tr><td>'f_ck = ? '</td></tr>
'</table>
#post
```

**Comment by Proektsoftbg** [comment]
You'd better also put the id in the immediately enlosing element, which is td in your case:
```
#show
'<table>
'<tr><td id="fck">'f_ck = ? '</td></tr>
'</table>
#post
```
You can even just use a paragraph element. If you wan't to hide it so that that the user would not put any other values add also display:none style:
#show
'<p id="fck" style="display:none;">'f_ck = ? '</p>
#post
```

**Comment by Proektsoftbg** [comment]
Hi! Thank's a lot! Great code BTW! :)
The problem is that you have input fields "?" in the #post section:
```
'Tensão Normal
σ_cp = ? 'MPa
'Taxa de armadura
ρ = ? /100
```
You can simply add #show before and it will become like this:
```
#show
'Tensão Normal
σ_cp = ? 'MPa
'Taxa de armadura
ρ = ? /100
#post
```
To avoid this problem, always make sure that all question marks are in #show or #pre sections so that to appear in the input stage. In future versions we can make the parser to detect such cases automatically and report them as errors to the user. 

Your code is very similar to what we do here to Eurocodes. :)

**Comment by hildebrandopsj** [comment]
> > Someone can tell me what i'm doing wrong?
> 
> The input needs to be created in the pre state so that the value is assigned, then you need to start the post process
> 
> ```
> #show
> '<table id="fck">
> '<tr><td>'f_ck = ? '</td></tr>
> '</table>
> #post
> ```



> Hi! Thank's a lot! Great code BTW! :) The problem is that you have input fields "?" in the #post section:
> 
> ```
> 'Tensão Normal
> σ_cp = ? 'MPa
> 'Taxa de armadura
> ρ = ? /100
> ```
> 
> You can simply add #show before and it will become like this:
> 
> ```
> #show
> 'Tensão Normal
> σ_cp = ? 'MPa
> 'Taxa de armadura
> ρ = ? /100
> #post
> ```
> 
> To avoid this problem, always make sure that all question marks are in #show or #pre sections so that to appear in the input stage. In future versions we can make the parser to detect such cases automatically and report them as errors to the user.
> 
> Your code is very similar to what we do here to Eurocodes. :)

I get it now! Thank you guys!

@Proektsoftbg our national code have a great influence from Eurocode, personally i use eurocode when some things are missing or need to be clarifyied.

Now i have three last questions:

1) How can i donate to this project?
2) How can i contribute to this project?
3) We have a forum or anything similar to share codes, examples, tutorials?

**Comment by Proektsoftbg** [comment]
Hi, I am glad you have managed. :) Thank you for your questions. You are so kind!

1. I have not enabled sponsorship yet but I can do it if there is any interest.
2. Any contributors are welcomed. There are a lot of things that need to be done, that require different skills. The general method is to clone the repository make changes and place pull requests. But it is good to coordinate the work.  I can open a discussion for that purpose: https://github.com/Proektsoftbg/Calcpad/discussions. 
3. There are some external forums currently:
- in Reddit: https://www.reddit.com/r/calcpad
- in Quora: https://calcpad.quora.com
- github has also some nice forum like features. We can use the discussions or wiki pages for that purpose. 
I can also set up a forum inside the calcpad official website: https://calcpad.eu
FYO there is a blog as well: https://calcpad.blog
