### ISSUE TITLE
Reference text on the same line when export to word

### ISSUE THREAD

**Issue by BasilioPV** [Proektsoftbg/Calcpad#240]
The following code:

<img width="195" alt="image" src="https://github.com/Proektsoftbg/Calcpad/assets/93596576/1631d905-3ac6-4507-afe1-9f0096114107">

Shows correctly at Calcpad:

<img width="445" alt="image" src="https://github.com/Proektsoftbg/Calcpad/assets/93596576/712a3cb7-3f9b-422d-ae2d-55e2057aaf5a">

But when export to Word shows:

<img width="581" alt="image" src="https://github.com/Proektsoftbg/Calcpad/assets/93596576/a9d237a7-3428-4595-9c41-a15c6b38dc1d">

How can I get a word output similar to the Calcpad's render?

**Comment by Proektsoftbg** [comment]
Hi!

We know that. For now, we cannot convert Html floating text to Word. So, this is the way refs are currently exported. You can leave them this way, it does not look so bad. :)

Another option, that is also not perfect is to add the refs on the same line with span:
`'Length -'a = 2m'<span class="ref">[ref]</span>`
It will show on the same line win Word, but not right aligned. You can quickly align them later with tabs, and you will skip the extra line.

Finally, you can align refs manually in the code with Em-spaces:
`'Length -'a = 2m'                                  <span class="ref">[ref]</span>`

It is a little more difficult to code, but there will be nothing to do in Word later. It all depends on whether your code is for one time use or will be used multiple times.

We will improve this in the future versions.

**Comment by BasilioPV** [comment]
Thanks!
