### ISSUE TITLE
HTML Output - Live calculation

### ISSUE THREAD

**Issue by BasilioPV** [Proektsoftbg/Calcpad#241]
It is possible to compile a calcpad to HTML and get a live calculation with it?

**Comment by Proektsoftbg** [comment]
Hi!

You cannot compile Calcpad code to a standalone webpage. You can save it as Html, but it will be static.
Without having Calcpad in the background to perform the calculations, the page will be "dead".

But you can make dynamic web pages that perform calculations like those on https://calcpad.eu/Category/1/home. For that purpose, you need the cloud version of Calcpad that powers the website in the backend. This is what Calcpad was initially created for and that is why it is so much integrated with Html.

We plan to open the Calcpad cloud platform to public and allow Calcpad users to share worksheets online. But we still have a lot of work to do before that. If you need to publish Calcpad worksheets too much, I can install and host a Calcpad server for you, but you will need to take the expenses for the hosting by your own.

**Comment by BasilioPV** [comment]
Thanks for offering the service, it is not necessary for me now. Thanks for your support!
