### ISSUE TITLE
Input value goes back to initial values after reopening the program

### ISSUE THREAD

**Issue by strsthapa** [Proektsoftbg/Calcpad#243]
Code: - I_x =? {48} in^4 
This is the original value the I_x was set, when the program is executed and new values are replaced the calculations are done for the updated values, however when I close and reopen the program the I_x value goes back to 48 instead of last value. It would be useful if it's replaced by the last user input value.

**Comment by Proektsoftbg** [comment]
Hi!

Did you try to save the file with the new values? You need to save it to persist the new values for the next time.

**Comment by strsthapa** [comment]
Yeah! it works, thank you :)
