### ISSUE TITLE
#warp instead of #wrap ?

### ISSUE THREAD

**Issue by Erikbernhart** [Proektsoftbg/Calcpad#248]
most minor issue ever, but in your calcpad.read.me you refer to #warp and warping around text.
I believe the correct function is #wrap and not #warp  

might be handy to change that in next versions of the readme.

![image](https://github.com/Proektsoftbg/Calcpad/assets/128965906/c2c38284-b732-4c16-b530-ea6f1c7baaa8)

**Comment by Proektsoftbg** [comment]
Hi! Thank you! Its a typo. The correct word is #wrap. Both words are so similar. :)
