### ISSUE TITLE
Installation problem in Linux .deb

### ISSUE THREAD

**Issue by defencedog** [Proektsoftbg/Calcpad#257]
Following instructions: https://github.com/Proektsoftbg/Calcpad/tree/main/Setup/Linux
All prerequisites are installed ...
However while installing deb this error occurs

```
Note, selecting 'calcpad' instead of './Calcpad.6.2.0.deb'
The following NEW packages will be installed:
  calcpad
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/38.8 MB of archives.
After this operation, 128 MB of additional disk space will be used.
Get:1 /home/ukhan/Downloads/Calcpad.6.2.0.deb calcpad all 6.2.0 [38.8 MB]
Selecting previously unselected package calcpad.
(Reading database ... 325956 files and directories currently installed.)
Preparing to unpack .../Downloads/Calcpad.6.2.0.deb ...
Unpacking calcpad (6.2.0) ...
Setting up calcpad (6.2.0) ...
: not foundkg/info/calcpad.postinst: 2: 
/var/lib/dpkg/info/calcpad.postinst: 4: Syntax error: "&&" unexpected
dpkg: error processing package calcpad (--configure):
 installed calcpad package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 calcpad
N: Download is performed unsandboxed as root as file '/home/ukhan/Downloads/Calcpad.6.2.0.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Linux pop-os 6.5.6-76060506-generic #202310061235~1697396945~22.04~9283e32 SMP PREEMPT_DYNAMIC Sun O x86_64 x86_64 x86_64 GNU/Linux

**Comment by Proektsoftbg** [comment]
Hi, 

What Linux version/distro is this? It seems that some permissions are denied. Did you run it as superuser (sudo)?
Try to remove it and install again:
sudo apt-get remove --purge calcpad
sudo apt-get install -y <path-to-your-downloads-folder>/Calcpad.6.2.0.deb

**Comment by Proektsoftbg** [comment]
Hi!

For some reason, my VS 2022 has replace all line endings in text files with windows mode CRLF. Now I got them back to LF and recompiled. You can download the package again and reinstall using the above instructions.

You can ignore the last message:
N: Download is performed unsandboxed as root as file '/home/ukhan/Downloads/Calcpad.6.2.0.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

It is irrelevant.
