### ISSUE TITLE
reading list of data from matrix table

### ISSUE THREAD

**Issue by xyont** [Proektsoftbg/Calcpad#26]
hi,

is there any similar function to LookUp as in Spreadsheet? required to read a list of data (row/column) based on specific reference.

best, 

for clarity, bellow figures are an example user function of Smath i've got from community

![2022-07-11 03_21_14-](https://user-images.githubusercontent.com/72367311/178160900-5e43761a-0e1b-4a09-a1ef-3f1cb8a3167c.png)

**Comment by xyont** [comment]
sorry, i did not follow the discussion regularly. there's available example screenshot for what i'm seeking for, where i can see the simple code for similar example?

![155005408-0e177d46-0088-423b-bd6f-b93441d2d69b](https://user-images.githubusercontent.com/72367311/178161522-11c99c9c-5852-465b-a59e-bc0d3d462a00.png)

**Comment by Proektsoftbg** [comment]
Yes, this is one way of doing that, in case you need to fill input boxes automatically, based on a user selection.You can also find the source code here:

[https://github.com/Proektsoftbg/Calcpad/blob/main/Examples/Structural%20Design/Steel/I%20section.cpd](https://github.com/Proektsoftbg/Calcpad/blob/main/Examples/Structural%20Design/Steel/I%20section.cpd)

The other way is to use the take, line and spline functions. You can not only look for values but also interpolate:
```
'Add your matrix row by row as follows:
r_1(j) = take(j; 11; 12; 13)
r_2(j) = take(j; 21; 22; 23)
r_3(j) = take(j; 31; 32; 33)
M(i; j) = take(i; r_1(j); r_2(j); r_3(j))
'Define the lookup vector (numerical values only):
Lookup(i) = take(i; 1.1; 2.2; 3.3)
'The lookup value is: 'x = 2.2
'Use the $find function to find the corresponding index for that lookup value
i = $find{Lookup(i) - x @ i = 1 : 3}
'Return the values from the matrix
M(i; 1)
M(i; 2)
M(i; 3)
```
If you run the above example, you will get: `21, 22, 23`. There is no need to write your own functions.
You can also combine both approaches. You can use the Html select element to fill only the index and then, get all values with take functions.

**Comment by xyont** [comment]
great, the function is available as built-in and the interpolation features also.

**Comment by Proektsoftbg** [comment]
Yes, this is a new feature since version v.5.6.
