### ISSUE TITLE
Rearrange Equation to find unknown variable

### ISSUE THREAD

**Issue by sapmaskey** [Proektsoftbg/Calcpad#260]
Would it be possible to rearrange an equation to report unknown variable?

For example:
Phi = 0.9
Mn = 100 kip.ft
Fy = 50 ksi
Phi*Mn = Fy*Zx
Zx = ?

This could be helpful for longer equations.

Please point me to the post if this already a feature. 

Thanks for your time.

**Comment by Proektsoftbg** [comment]
Hi!

If you mean to solve for the variable Zx symbolically and get Zx = Phi*Mn/Fy, Calcpad cannot do that. It is a numerical package and does not include symbolic evaluations. It can only calculate the formulas you enter in the code.

We do not plan to develop a symbolic engine. It is a huge task and there are many symbolic CAS's already available.

**Comment by sapmaskey** [comment]
Thanks Ned
