### ISSUE TITLE
Bug - Help Print

### ISSUE THREAD

**Issue by hildebrandopsj** [Proektsoftbg/Calcpad#261]
Hi @Proektsoftbg!

I think i have discovered a bug. If my code have some #input or #pause in it and i press the button "Open with MS Word", Calcpad export the Help, not the worksheet.

This only happen if we press the button before press F5 to continue the code.

**Comment by Proektsoftbg** [comment]
Hi! Thank you! I will try this.

**Comment by Proektsoftbg** [comment]
Hi! I fixed this in the latest release. Now it is printed even if calculations are paused.
