### ISSUE TITLE
Bug - Select Unit

### ISSUE THREAD

**Issue by hildebrandopsj** [Proektsoftbg/Calcpad#262]
Hi @Proektsoftbg 

Maybe i found another bug, if i have some variable in my code that match some unit, for example:

![image](https://github.com/Proektsoftbg/Calcpad/assets/86059123/48151bca-3fca-4487-ae19-081d4f886944)

When trying to assign kNm/m to M_pb,c,Sd = 0, the /m always bring the variable, even if we use the m unit in the selector

![image](https://github.com/Proektsoftbg/Calcpad/assets/86059123/8c7c54cc-5a59-4f17-8eea-96f45cad6187)

Maybe the soluton is to create the unit Moment per unit lenght (kNm/m)

Happy new year my friend!

**Comment by Proektsoftbg** [comment]
Hi! To make difference between a unit and a variable with equal names, add dot before the unit : `.m`.
The dot will not be visible in the output. For the selector, it just inserts the displayed text. Maybe it is possible to make the selector to add the dot automatically, if you have also a variable. This is a good idea. I will think about it.

Happy New Year to all Calcpad friends. Great times are coming for Calcpad next year. Significant improvements will be added like vectors and matrices. Vectors are quite ahead already.

**Comment by ralphingefranz123** [comment]
then we will get vectors  etc. ?(~ date

**Comment by Proektsoftbg** [comment]
@ralphingefranz123 . It is not possible to tell an exact date, Even approximate. I have to do this along with my regular job.

**Comment by Proektsoftbg** [comment]
I made to insert the unit with a dot from the autocomplete list, if a variable with the same name has been already defined.

**Comment by hildebrandopsj** [comment]
Thank you!
