### ISSUE TITLE
Error on install - A device attached to the system is not functioning

### ISSUE THREAD

**Issue by escull** [Proektsoftbg/Calcpad#265]
Hello, 

First, Calcpad is now my favourite engineering calculator. An excellent tool indeed!

I am getting a weird error trying to install on my work machine. (Win 11 - i5)
 
<img width="274" alt="image" src="https://github.com/Proektsoftbg/Calcpad/assets/6353909/474fa84f-5f35-43a7-9067-b5c9708369ed">

I have checked all hardware in device manager but there doesn't seem to be any issues. 

I have installed dotnet sdk 8. 

<img width="325" alt="image" src="https://github.com/Proektsoftbg/Calcpad/assets/6353909/9ea91f36-3466-4a5c-9d39-eaba18896ceb">

Am doing something wrong? 

Is there a portable/ non-install version? 

Big Thanks!

**Comment by Proektsoftbg** [comment]
Hi! It looks like some antivirus software is making problems.
Check the antivirus for recent detection or putting the file into quarantine.

**Comment by escull** [comment]
Hi! 

Yes, it is a virus scan issue. 

My IT team will no longer help me with the install as a threat has been detected. (sad)

Interestingly the MS Store version installs and runs fine... 

Will there be an update to the MS Store version?

**Comment by Proektsoftbg** [comment]
Hi,

The MS Store version is actually the same, it is just a bit older. This is certainly a false alarm.
After compiling, we sign the program files with our official Digicert EV code signing certificate.
After that, the code cannot be modified, without breaking the corresponding hash.

I think you can safely take it out of quarantine and report a false alarm.
In all cases, it is an open source software. You can clone the source code and compile it by yourself on your own computer with VS 2019. Nothing can be safer than that. :)
