### ISSUE TITLE
Left Pane & Right Pane Sync

### ISSUE THREAD

**Issue by berkdemir** [Proektsoftbg/Calcpad#268]
I am sure there is a solution, but couldn't find:
When we have a long sheet, how can we get the right pane to follow the left pane? Or if it does not follow, how can we get it to the selected row? Right now, for example, I go to row 300 in left pane, but right side is on row 100.

**Comment by Proektsoftbg** [comment]
Hi!

There are two ways to sync the right panel to the left: double click on the line of code or press Ctrl+Enter.

To sync the left panel to the right, hover the mouse over the line in the output until a small blue arrow appears on the left. Then, click the arrow.

**Comment by berkdemir** [comment]
Hi,
Syncing the left panel to the right does not work for me, it never did to be honest.

https://github.com/Proektsoftbg/Calcpad/assets/40423004/d263d8e8-7f96-4448-8df7-c4452fc7f222

**Comment by Proektsoftbg** [comment]
So, you click the arrow and nothing happens? Is this with the latest version 6.2.1?
This option uses some JavaScript to catch the click. It is possible that is some local problem with the computer security settings. Maybe JS is disabled? Can you please try on another computer with the latest version?

**Comment by berkdemir** [comment]
If it works with others, it should be a local problem, but I don't have a chance to try with other computer.
I tried with a clean script, it's same. 
I have no idea about my Javascript settings etc. If Calcpad didn't install, I don't even know if I have it.
