### ISSUE TITLE
Map Plot Error

### ISSUE THREAD

**Issue by murilo-s** [Proektsoftbg/Calcpad#279]
Hello,

I'm having trouble while trying to plot a map. I'm using a switch function and I get an error that the calculated unit is "unitless", but I'm checking all terms separately and the units are correct. MY assumption is that there is a bug when plotting a map with a switch function. See image:

![image](https://github.com/Proektsoftbg/Calcpad/assets/146354581/ee225839-2e2f-496f-83b4-ebd57211441e)

Thanks.

**Comment by Proektsoftbg** [comment]
This certainly is not related to $Map. It occurs somewhere in the function. I can see that you have two switch cases "<" and "≡". It is not clear what happens when it is ">". My advice is always to have a "default" case - a final expression without check before it.

**Comment by murilo-s** [comment]
Thanks. That was the problem. Although my "y" is varying from 0...L, the function needs a general rule. When I fixed this, it worked fine.
