### ISSUE TITLE
Function with y, instead of x issue

### ISSUE THREAD

**Issue by murilo-s** [Proektsoftbg/Calcpad#280]
Hi,

I'm getting a warning of undeclared variable when using a f(y) function instead of f(x) function. But the weird part is that it is plotting correctly. See image:

![image](https://github.com/Proektsoftbg/Calcpad/assets/146354581/ee386612-47e5-4a17-a30e-6e3c7c9368d6)

Thanks.

**Comment by Proektsoftbg** [comment]
Aha! Thank you, i see. Maybe I manually set the highlighter to set x_sup as declared when meets $Sup. Probably it does not work with other variables. I will take a closer look.

**Comment by murilo-s** [comment]
Great, thanks!

**Comment by Proektsoftbg** [comment]
Hi!

This is now fixed in version 6.2.3:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v6.2.3

Cheers!
Ned

**Comment by murilo-s** [comment]
Awesome, Ned!

Thanks!
