### ISSUE TITLE
Long Function

### ISSUE THREAD

**Issue by murilo-s** [Proektsoftbg/Calcpad#281]
Hi,

Is it possible to break the codeline in multiple lines in long functions?

For example, i have this function:
![image](https://github.com/Proektsoftbg/Calcpad/assets/146354581/c19488ef-fb0d-426a-987a-3a17ec4c2002)

But to make the code easier to understand and work, I wanted to do something like this:
![image](https://github.com/Proektsoftbg/Calcpad/assets/146354581/dfe5c307-62e2-42d5-8b99-b18d6a0e307a)

But as you can see, the function stops working.

Thanks,

**Comment by Proektsoftbg** [comment]
Hi, @murilo-s!

This has been requested some time ago and I am almost done with it, but not released yet. You can continue the line by adding " _" and the end.

![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/7f90d7dc-fb86-47b8-b129-c167c8d835e8)

I am not sure this is fully working. If you want, I can send you a beta version to test it and if it is OK, we can release it as 6.2.2.

**Comment by murilo-s** [comment]
Hey Ned, thats great!

Yes, I would like to test the beta version.

Thanks!

**Comment by Proektsoftbg** [comment]
Hi, you can download the updated version from this link:
https://github.com/Proektsoftbg/Calcpad/blob/main/Setup/calcpad-setup-en-x64.exe

I did not publish it officially yet. Please, try it first to see if it is working. Add " _" (space and underscore) and the end of the line to continue the expression on the next line.

![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/38894161-1610-4dd8-b8be-c9e1aae5efca)

**Comment by murilo-s** [comment]
Great, Ned.. thanks!

I did a quick test here and apparently it is working fine. I'll try a bit more tomorrow.
