### ISSUE TITLE
Switch Function Output

### ISSUE THREAD

**Issue by murilo-s** [Proektsoftbg/Calcpad#284]
Hi,

I noticed that the switch function output gets weird with longer function. See below:

![image](https://github.com/Proektsoftbg/Calcpad/assets/146354581/5faf518c-d989-453e-97c5-b88795f6b270)

Thanks.

**Comment by Proektsoftbg** [comment]
Hi,

Yes, this is because it does not fit on a single line. Currently, I cannot figure out what to do in such cases.

I could only recommend to use shother variables, like `DS` and `DR` and add some legend if necessary:
```
'DS = Diaphragm Shear
'DR = Diaphragm Reaction
```
