### ISSUE TITLE
Redefinition of a formula

### ISSUE THREAD

**Issue by berkdemir** [Proektsoftbg/Calcpad#285]
Hi,

I think this is a bug. Calcpad does not allow redefinition of a formula, **if you change the input parameters.** In addition to that, the error message does not make sense.
![image](https://github.com/Proektsoftbg/Calcpad/assets/40423004/1b8dbfe8-275b-4ebe-a03b-e7a467331fa0)

**Comment by Proektsoftbg** [comment]
Hi,

Yes, thank you. This is a bug. I also noticed that. It works only when the number of parameters is the same.

**Comment by Proektsoftbg** [comment]
Hi!

I fixed this in version 6.2.2:
https://github.com/Proektsoftbg/Calcpad/blob/main/Setup/calcpad-setup-en-x64.exe

Please, try it first before publishing it officially.

**Comment by berkdemir** [comment]
I cannot try somehow, the company PC does not allow me. But thanks!
