### ISSUE TITLE
PDF Font Size

### ISSUE THREAD

**Issue by berkdemir** [Proektsoftbg/Calcpad#290]
It's a feature request.
When I create a long sheet, I tend to go to word first, because the PDF export is too big in fonts for my taste. Word to PDF works for me of course, no problem, but it would have been nice to be able to set up a font size for PDF exports. (Or maybe get a hint from the zoom level of the right pane)

**Comment by Proektsoftbg** [comment]
Zooming the view do not actually zoom the Html document content. For that purpose, please add the following line on the top of your code:
`'<style>body {zoom: 0.8;}</style>`

This will affect both the Html and the Pdf export.

You can also try to use the print command with some of the available pdf printers like CutePDF:
https://www.cutepdf.com/index.htm
There is a zoom option and some others as well.

Currently, we are not able to customize much the pdf export. We are using an external project for that purpose:
https://github.com/wkhtmltopdf/wkhtmltopdf

Unfortunately, this project is not supported anymore and probably we will need to search for another solution in the future.

**Comment by berkdemir** [comment]
`'<style>body {zoom: 0.8;}</style>` is good enough for me, thanks.
