### ISSUE TITLE
Does Units in comments still work

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#291]
I tried but found it could not work like before.

**Comment by Proektsoftbg** [comment]
Yes, they work fine here. What happens at your side?

**Comment by idealkindom** [comment]
I revised the code in help.html to ""Units in comments
'Length -'l = ? {3}'%u
'Area -'A = ? {8}'%u2
'Volume -'V = ? {7}'%u3
'Scale factor -'Units
"
and now itworks fine. That part content of the help.html should be revised otherwise misunderstood.

在 2024-03-15 22:12:06，"Ned Ganchovski" ***@***.***> 写道：


Yes, they work fine here. What happens at your side?

**Comment by Proektsoftbg** [comment]
Yes, you are right thank you. Now you must set default values after the question marks like `a = ?{1}`.

In the early versions, they were set at the end of the file which caused problems with macros and modules.
