### ISSUE TITLE
An example that could not be reproduced like that in help.html

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#292]
f(z; c) = $Repeat{z = z^2 + c @ i = 1 : 1000}
PlotHeight = 400
PlotWidth = 400
PlotStep = 1
$Map{abs(f(0; x + 1i*y)) @ x = -1.5 : 0.5 & y = -1 : 1}

What I got from the output window is quite different from that shown in help.html.

**Comment by Proektsoftbg** [comment]
Yes, probably because this was created with an older version of Calcpad. Now you get the inverted version of the set.
If you want to get the picture in the manual, use directly this function:
$Map{mandelbrot(x; y) @ x = -1.5 : 0.5 & y = -1 : 1}

![image](https://github.com/Proektsoftbg/Calcpad/assets/90918363/c53b0ecf-92f1-4a22-9c6e-a055c4d00de1)

**Comment by idealkindom** [comment]
> Yes, probably because this was created with an older version of Calcpad. Now you get the inverted version of the set. If you want to get the picture in the manual, use directly this function: $Map{mandelbrot(x; y) @ x = -1.5 : 0.5 & y = -1 : 1}
> 
> ![image](https://private-user-images.githubusercontent.com/90918363/313418878-c53b0ecf-92f1-4a22-9c6e-a055c4d00de1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MzU3OTMsIm5iZiI6MTcxMDYzNTQ5MywicGF0aCI6Ii85MDkxODM2My8zMTM0MTg4NzgtYzUzYjBlY2YtOTJmMS00YTIyLTljNmUtYTA1NWM0ZDAwZGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDAwMzEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMTdkNjhkM2JkNGNiOWE5YjUwNmVjNmMwZWQwNjc5NGRmODU2NjAzM2FjMjViNWZjZWY5ZDE3NjU2ZjMzZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OWJtSpvRaefu0BfzzxOaXQ9jygdRlpqCeLsy2z74Br0)

Oh, yes.So mandelbrot now is a predefined function but not supported ny autocompletion yet.

**Comment by Proektsoftbg** [comment]
I fixed this in version 6.2.2.
