### ISSUE TITLE
Is it possible to portablize Calcpad

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#301]
For so convenient tool like Calcpad, if it could be portablized, then it shall gain more convenient use. Just imagine that you can store it in a USB disk.

**Comment by Proektsoftbg** [comment]
Yes, it is easy to do. I will post it later today.

**Comment by Proektsoftbg** [comment]
Hi!

I made a portable version and uploaded here:
https://calcpad.eu/download/calcpad-portable-en-x64.zip

Please, try if it works. Just download the fine and unzip it on a flash drive or a folder on your computer.

**Comment by idealkindom** [comment]
Great!I will test it as much as possible.

在 2024-04-18 23:55:13，"Ned Ganchovski" ***@***.***> 写道：


Hi!

I made a portable version and uploaded here:
https://calcpad.eu/download/calcpad-portable-en-x64.zip

Please, try if it works. Just download the fine and unzip it on a flash drive or a folder on your computer.

**Comment by idealkindom** [comment]
> Hi!
> 
> I made a portable version and uploaded it here: https://calcpad.eu/download/calcpad-portable-en-x64.zip
> 
> Please, try if it works. Just download the file and unzip it on a flash drive or a folder on your computer.

Hi,Ned.I tried the portable Calcpad and until now it works fine, except for that all the UI and help files are in Bulgraian.

**Comment by Proektsoftbg** [comment]
Aha! OK. Sorry for that. Probably I forgot to switch the locale. I will rebuild and upload it again later today.

**Comment by idealkindom** [comment]
Thks so much. You know the portablization of Calcpad is that you don't have to link to net and download and install .Net runtime anymore. At the same time, the influence on calculation speed is neglectable.

在 2024-04-19 17:34:34，"Ned Ganchovski" ***@***.***> 写道：


Aha! OK. Sorry for that. Probably I forgot to switch the locale. I will rebuild and upload it again later today.

**Comment by Proektsoftbg** [comment]
Hi!

I fixed it and it is in English now. The link is the same:
https://calcpad.eu/download/calcpad-portable-en-x64.zip

**Comment by idealkindom** [comment]
> Hi!
> 
> I fixed it and it is in English now. The link is the same: https://calcpad.eu/download/calcpad-portable-en-x64.zip

Thanks a lot.
