### ISSUE TITLE
Using Gravity constant

### ISSUE THREAD

**Issue by rogandersson** [Proektsoftbg/Calcpad#305]
I expected F to compute in the unit of force (N). What am I missing?
![Capture](https://github.com/Proektsoftbg/Calcpad/assets/169234522/67d891c9-b266-4ee0-b129-96c821f55b20)

**Comment by Proektsoftbg** [comment]
Hi! By default, "g" is unit for mass (grams). To work with the gravity constant or any other, you have to insert it from the "Insert" menu or the right hand panel.

g = 9.80665m/s^2

**Comment by rogandersson** [comment]
Understood, On the windows client I used the button in the panel (as it states "Gravitational acceleration on Earth" when I hoover over it) but as you say it ends up in one unit of gram. Now I know how to proceed, thanks!
![Capture](https://github.com/Proektsoftbg/Calcpad/assets/169234522/d22ae23b-3949-4707-9294-eeaa066cb9bf)

**Comment by Proektsoftbg** [comment]
Hi! Thank you!

Yes, you can use this button to quickly insert the symbol, but need to insert the definition first anyway.
Probably, we can make this button to warn you if you haven't and prompt to insert it for you.
In this way, we can improve the user experience in the future. :)

Thank you for your feedback. It provided valuable information for us about flaws in the UX design
