### ISSUE TITLE
Strange ineffctive plot limitation 

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#311]
f(x) = x^3 - x^2
$Plot{f(x) & 2|f(x) & f(x)|1 @ x = -5 : 5}
The plot limitations does not work and the revision will be very wierd.Anyone intrested could reproduce and play with the upper and lower limitions for plotting.

**Comment by Proektsoftbg** [comment]
Hi!

You plot also "`f(x)|1`" which means that the abscissa is x = f(x) and the ordinate is y=1.
f(x) = -150 for x = -5
f(x) = 100 for x = 5
So it plots a straight line between (-150; 1) and (100; 100).

**Comment by idealkindom** [comment]
> Hi!
> 
> You plot also "`f(x)|1`" which means that the abscissa is x = f(x) and the ordinate is y=1. f(x) = -150 for x = -5 f(x) = 100 for x = 5 So it plots a straight line between (-150; 1) and (100; 100).

OK,I understand now.Thks.
