### ISSUE TITLE
Request fraction power on unit not calculated

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#312]
Some units like m/kg^(1/3) is better preserved as it is, otherwise the substition and calculation makes its weird. 

This kind of units mainly come from The dynamics of explosion and its use, by Josef Henrych;Explosion-Resistant Buildings by M.Y.H. Bangash.

**Comment by marcostrmuniz** [comment]
this is not the solution, but it works:
m/root(kg; 3)

**Comment by idealkindom** [comment]
Very good!

在 2024-05-28 04:11:31，Muniz ***@***.***> 写道：


this is not the solution, but it works:
m/root(kg; 3)

**Comment by Proektsoftbg** [comment]
@marcostrmuniz thank you. To be honest, even I didn't know that. :)

**Comment by idealkindom** [comment]
> this is not the solution, but it works: m/root(kg; 3)

Here are some strange variations:
``
r = 10'm
Q = 23'kg
Rr = r*m/root(Q; 3)/root(kg; 3)
Rr = r*m/(root(Q; 3)*root(kg; 3))
Rr = r/root(Q; 3)*m/root(kg; 3)

r = 10m
Q = 23kg
Rr = r/root(Q; 3)
``
