### ISSUE TITLE
Calcpad crash when editing existing parameters in formula

### ISSUE THREAD

**Issue by bigbluegg** [Proektsoftbg/Calcpad#313]
I am currently using the desktop version. When opening an existing file and editing the formula (e.g., changing V_R to V_S), it crashed when deleting R and typing in S. It also happens when moving the placeholder into the round bracket.

Can someone give me some help, please?

PC: windows 10, .Net 8, MS, adobe reader, Inventor, Vault

**Comment by Proektsoftbg** [comment]
Hi!

 Try to uninstall the program completely, then download and clean install the latest release:
 https://github.com/Proektsoftbg/Calcpad/releases/download/v6.2.3/calcpad-setup-en-x64.exe
 
 If this does not help, please provide more specific information. Does it happen on any worksheet and any kind of edit or just on a specific file and specific variable (v_R).

Maybe it is the further contents of the worksheet where the error occurs. Can you post the file in this case?

**Comment by bigbluegg** [comment]
Hi Proek,

I tried your solution, but it does not fix the problem. 

In case there is something wrong with the file I generated, I tried another file named "Cornu Spiral", which is an example file in C:\......\Documents\Calcpad\Examples\Mathematics\Parametric Curves, but the same error happens.

at the moment, only on editing round bracket and variables like v_R

e.g. **A=3*k+6*(d+7t)*^1.6**    location indicated below **(**_**d**

When I move placeholder by arrow key or use mouse to click the location marked with "_", the program kills itself. But no issues when placing to the left of round bracket and to the right of d. Of course, it also happens on the variable e.g. v_R

I have tried on my another laptop, ASUS zenbook, the same issue happens. This laptop has win 11 installed, but everything else is the same to the PC.

**Comment by Proektsoftbg** [comment]
Hi! Thank you for your feedback! But sorry, I cannot reproduce the program. I move the cursor everywhere and nothing happens. Can you please, post an exact worksheet code and exact position where to click? Does it happen to anyone else here guys?

**Comment by bigbluegg** [comment]
Hi Proek,

I have captured a video showing the issue. The video does not capture the mouse, but I guess it can be interpreted by the location of place holder. The time of crashing happens when I moved the click the place between the "2" and ")" at the end of the video.

https://github.com/Proektsoftbg/Calcpad/assets/69374611/a822bef9-45cd-46b9-bb6a-412de0027874

**Comment by GregorSiefert** [comment]
> Hi Proek,
> 
> I have captured a video showing the issue. The video does not capture the mouse, but I guess it can be interpreted by the location of place holder. The time of crashing happens when I moved the click the place between the "2" and ")" at the end of the video.

Im having the exact same issue, did you find a fix?

**Comment by Proektsoftbg** [comment]
@GregorSiefert Yes, I believe we did. Please download and try with the latest version.

**Comment by GregorSiefert** [comment]
It worked, thanks :)
