### ISSUE TITLE
"Quadratic Equation komplex

### ISSUE THREAD

**Issue by ralphinge123** [Proektsoftbg/Calcpad#315]
'The discriminant is less than zero. There are no real roots,2konjugiert komplexe lösungen.

- [ ] 

- [ ] 
[Quadratic Equation_version1.pdf](https://github.com/user-attachments/files/15751697/Quadratic.Equation_version1.pdf)

**Comment by Proektsoftbg** [comment]
Thanks for sharing, Ralph. Probably it will be better to put these things in Discussions:
https://github.com/Proektsoftbg/Calcpad/discussions
