### ISSUE TITLE
olyProperties

### ISSUE THREAD

**Issue by ralphinge123** [Proektsoftbg/Calcpad#319]
i have a question :?

[PolyProperties.pdf](https://github.com/user-attachments/files/15916777/PolyProperties.pdf)
can we do this with calcpad????

**Comment by idealkindom** [comment]
Since Calcpad doesn't support list or vector calculation, I think it's not direct and easy to do this task with Calcpad.

**Comment by idealkindom** [comment]
> It will be possible with the new version. Now you can do it in another way - to wrap the geometry into functions x(s), y(s).

That's a exciting news.

**Comment by Proektsoftbg** [comment]
Now you can do it with version VM 7.0.7.
https://github.com/Proektsoftbg/Calcpad/releases/tag/v7.0.7
