### ISSUE TITLE
Option to have more control over default units

### ISSUE THREAD

**Issue by imartincei** [Proektsoftbg/Calcpad#332]
When using imperial units, the program seems to choose default units and not give much control over when this is chosen.

![image](https://github.com/Proektsoftbg/Calcpad/assets/154382162/d53cb74e-4afd-4c9a-8b08-fb38a5f255f7)

![image](https://github.com/Proektsoftbg/Calcpad/assets/154382162/aa25c3d9-6ef2-4d5c-8c50-fb790d67face)

All of these units are defined in psf, but CalcPad wants to convert it to ksi and then back to psf. This makes the calculations look very messy, so it would be great if I could force the software to use psf as the default or suppress the function that is automatically converting it to ksi. I looked through the docs and existing issues and couldn't find any information on this.

**Comment by Proektsoftbg** [comment]
It should not convert it in this case. Maybe this is a bug. I will look at it.

**Comment by Proektsoftbg** [comment]
This is fixed in the new version Calcpad VM 7.0.7. Now default units remain psf and not spontaneously changed to ksi.
https://github.com/Proektsoftbg/Calcpad/releases/tag/v7.0.7
