### ISSUE TITLE
Some un sophisticated equation can't be solved

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#346]
The code is here
```
N(α) = 0.6204639*α^(-2.111817)
N2(α) = 0.83/α^2 - 1.9
$Plot{N(α) & N2(α) @ α = 0.05 : 0.8}
'Fig.1
N2(α) = 0.83/α^2 - 1.9
NN(R2; R1) = 0.83*(R2/R1)^2 - 1.9
R1(k; q) = k*cbrt(q)
k = 2
q_m = $Root{R1(k; q) - 0.4 @ q = 0 : 9000}
R2 = 1
W(q) = NN(R2; R1(k; q))*q
$Plot{W(q) @ q = 0.00001 : 0.035}
W_max = $Sup{W(q) @ q = 0.00001 : 0.05}

q_r = $Root{W(q) - W_max @ q = 0.00001 : 0.035}
q_r2 = $Find{W(q) - W_max @ q = 0.00001 : 0.035}

$Plot{W(q) & q_r|W(q_r) @ q = 0.00001 : 0.05}
$Plot{W(q) & q_r2|W(q_r2) @ q = 0.00001 : 0.05}
```
I also tried this with Maxima and get the answer in a blink of an eye.
However,I defined a step for the vairable and a tolerance for the function, using #repeat #loop to go flank to the answer with Calcpad.

**Comment by Proektsoftbg** [comment]
Hi!

Yes, Calcpad cannot find roots where the functions "touches" the x-axis from one side as W(q) = W_max does. It uses bracketing methods, so the function must cross the x-axes, i.e. the signs at both ends of the interval must be opposite. For example, see:
https://en.wikipedia.org/wiki/Bisection_method

However, you do not actually need to use $Root and $Find for that purpose. $Sup and $Inf alone does the job. You only need to add:

```
q_r = q_sup
$Plot{W(q) & q_r|W(q_r) @ q = 0.00001 : 0.05}
```

So, if your parameter name is q, the program automatically creates a variable q_sup for maximum and q_inf for minimum. So, it gets even easier than Maxima.

![image](https://github.com/user-attachments/assets/52961f64-ae4a-4e74-8e03-23695f690edf)

**Comment by idealkindom** [comment]
wow, the varible with the special subscript is pre-conserved by Calcpad internally.This is the first time I know this.Thks a lot.

在 2024-08-15 19:35:53，"Ned Ganchovski" ***@***.***> 写道：


Hi!

Yes, Calcpad cannot find roots where the functions "touches" the x-axis from one side as W(q) = W_max does. It uses bracketing methods, so the function must cross the x-axes, i.e. the signs at both ends of the interval must be opposite. For example, see:
https://en.wikipedia.org/wiki/Bisection_method

However, you do not actually need to use $Root and $Find for that purpose. $Sup and $Inf alone does the job. You only need to add:

q_r = q_sup
$Plot{W(q) & q_r|W(q_r) @ q = 0.00001 : 0.05}


So, if your parameter name is q, the program automatically creates a variable q_sup for maximum and q_inf for minimum. So, it gets even easier than Maxima.

image.png (view on web)

**Comment by Proektsoftbg** [comment]
Yes, exactly. You're welcome! :)
