### ISSUE TITLE
Some features needed but I have not found in Calcpad

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#35]
1.How could I define of standalone function and call it from another worksheet? The problem is easy to understand.

2.How could I convert a parameter's unit in the worksheet? Is there any special function or syntax for that?

**Comment by cser** [comment]
1. It's just appeared in prerelease, see #include
[Calcpad version 5.8.1.](https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.8.1)
There exists 2 types of functions: nomal pure one-line (defines just like `f(x;y)=x^2+y`) and macroses (can contains text, see #def)
2. Like this?
```
x = 100mm'shows x=100mm
x'shows x=100mm
x|m'shows x=100mm=0.1m
x'shows x=100mm
y = x|m'shows y=x=100mm=0.1m
y'shows 0.1m
```

**Comment by idealkindom** [comment]
> 1. It's just appeared in prerelease, see #include
>    [Calcpad version 5.8.1.](https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.8.1)
>    There exists 2 types of functions: nomal pure one-line (defines just like `f(x;y)=x^2+y`) and macroses (can contains text, see #def)
> 2. Like this?
> 
> ```
> x = 100mm'shows x=100mm
> x'shows x=100mm
> x|m'shows x=100mm=0.1m
> x'shows x=100mm
> y = x|m'shows y=x=100mm=0.1m
> y'shows 0.1m
> ```

Thanks a lot.
