### ISSUE TITLE
Taller square roots do not print

### ISSUE THREAD

**Issue by firai** [Proektsoftbg/Calcpad#352]
Square root types `r1` through `r3` don't seem to print. The symbols _display_ within the built-in output panel and in other browsers, but they do not print using either the built-in print command or through other browsers (via HTML).

Source code
![image](https://github.com/user-attachments/assets/ce7693c9-971f-4840-bb12-0809bf24b919)
Display in built-in output panel (HTML display in other browsers similar)
![image](https://github.com/user-attachments/assets/f03ca324-a4b2-4ae8-89a0-ff3c6c7fc12a)
Printed from built-in print command (printing from other browsers similar)
![image](https://github.com/user-attachments/assets/86c902f7-e61b-406e-8fc2-6883b8ee01a3)

**Comment by firai** [comment]
It turns out the symbols will print when the background image option is turned on, which was not turned on by default for me. This may deserve a mention in the documentation.

**Comment by Proektsoftbg** [comment]
Yes, thank you. It should be the background image option.
