### ISSUE TITLE
Inserting image at cursor

### ISSUE THREAD

**Issue by yuncu** [Proektsoftbg/Calcpad#36]
Hi,

When inserting an image in the document using the "Insert Image" button, the image is inserted at the top of document, instead of the cursor position. Maybe it can be inserted below or above the current line.

Thanks.

**Comment by Proektsoftbg** [comment]
@yuncu , thank you for reporting this. It was fixed in the latest release:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v.5.8.2
