### ISSUE TITLE
Support for Dictionary Objects or Table Lookups

### ISSUE THREAD

**Issue by imartincei** [Proektsoftbg/Calcpad#365]
My company is looking to migrate a lot of our internal Excel sheets to CalcPad, and I have not found a way to conveniently simulate lookup tables in Excel. As an alternative to using lots of if statements, would it be possible to add support for a dictionary-like object that can lookup a numerical value by a key? One practical example of this is rebar areas, so instead of:

if bar_size == "#3" -> return 0.11
elseif bar_size == "#4" -> return 0.2
etc...

You could create an object and lookup the text key to return the value (this syntax is how I would do this in Python):

bar_areas = {"#3": 0.11, "#4": 0.2, etc...}
As = bar_areas[bar_size]

Let me know if I'm missing any current functionality outside if statements that can do the same thing.

Thank you!

**Comment by Proektsoftbg** [comment]
Hi!

Probably you are not using the latest version. Download and install version 7.0.7.
https://github.com/Proektsoftbg/Calcpad/releases/tag/v7.0.7

It already have a lookup function like Excel. Try the following code:
```
Ø = [3; 4; 5]'- bar sizes
A_s = [0.11; 0.2; 0.3]'- bar areas
A_s(ø) = take(1; lookup(Ø; A_s; ø))'- lookup for ø in Ø and return A_s. Then take the first element, since lookup returns a vector.
A_s(3)
A_s(4)
'Alternatively, search for ø in Ø and use its index to return A_s
A_s(ø) = A_s.search(Ø; ø; 1)
A_s(4)
A_s(5)
```

![image](https://github.com/user-attachments/assets/210ea604-fbc6-4671-a01b-ea49bc3ed498)

**Comment by imartincei** [comment]
I just didn't make that connection from the docs, thank you!

**Comment by Proektsoftbg** [comment]
I am always glad to help. I wish you success with your migration.
