### ISSUE TITLE
Problem for displaying index of vector's elements

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#367]
The Calcpad codes are as follow:
```
n = ? {10}
x = vector(n)
#for i = 1 : n
x.i = i^2 - 1
#loop
'<hr/>
x.1
x.2
x.3
$repeat{x.j = j^2 + 2 @ j = 1 : 10}
x.1
x.2
x.3
#for i = 1 : n
x.i
#loop
```

**Comment by idealkindom** [comment]
Maybe I have not get the right way of using and taking elements of a vector. There is one more problem I tested.
```
n = 10
x = vector(n)
#for i = 1 : n
#hide
x.i = i - 1
#post
x.i
#loop
```

**Comment by idealkindom** [comment]
b

> Maybe I have not get the right way of using and taking elements of a vector. There is one more problem I tested.
> 
> ```
> n = 10
> x = vector(n)
> #for i = 1 : n
> #hide
> x.i = i - 1
> #post
> x.i
> #loop
> ```

Once again, I changed the code only for adding one"#val" after #post, the output become totally varied.
```
n = 10
x = vector(n)
#for i = 1 : n
#hide
x.i = i - 1
#post
#val
x.i
#loop
```

**Comment by Proektsoftbg** [comment]
Hi!

Thank you so much for reporting this. I tried and noticed that it does not display the correct index. It is always 1.
This is probably after optimizing loops by pre-compiling. The compiled expression does not update the index display, although internally it refers to the correct element. I will fix that.

**Comment by idealkindom** [comment]
> Hi!
> 
> Thank you so much for reporting this. I tried and noticed that it does not display the correct index. It is always 1. This is probably after optimizing loops by pre-compiling. The compiled expression does not update the index display, although internally it refers to the correct element. I will fix that.

Pls pay special attentions to my supplementary comment about the "#val" effect, for which I guess some logic confusions happen there.
