### ISSUE TITLE
Units improvements

### ISSUE THREAD

**Issue by jgagnonNT** [Proektsoftbg/Calcpad#37]
Hello,

Some suggestions to improve the units conversion:
1- The built-in "g" value is 9.81 without units. I think it would be more useful to have it with units : 9.81m/s²
2- While trying to enter energy density such as E = 5J/g  It considers g as "9.81" instead of as "gram". Thus there is a confusion between the two. I'm ot too sure how to solve this. Perhaps having g as "gram" per default unless g is stated as "9.81m/s^2".
3- Adding the units of viscosity : Poise, Centipoise, Stokes, Centistoke could be useful. Those units are always a hassle to play with.

Thanks for your great work

**Comment by cser** [comment]
You can just overwrite g: `g=9.81N/kg`

**Comment by cser** [comment]
2 - yes, it's problem with units syntax, workaround for it: `E=5j/1g`.

**Comment by Proektsoftbg** [comment]
There is only one problem with writing `E = 5J/1g`. The program will hot treat this as composite units of type `J/g` and will decompose them to m2/s2. To retain the composite units, also add vertical bar conversion at the end:
`E = 5J/1g|J/g`

![image](https://user-images.githubusercontent.com/90918363/184454891-099dd76c-d3a8-49db-85e9-be40bea1d184.png)
