### ISSUE TITLE
possible problem on compiled cpdz file

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#370]
Just for think:
I tried Calcpad VM 7.0.9 with former compiled cpdz files. several of them errors.

And I transfer back to 6.2.3 to make sure that the compiled cpdz files work fine.

I don't know what's the reason.

When I have more time I will try with the example files.

**Comment by Proektsoftbg** [comment]
Hi!

Are you sure you installed .NET 8.0 as well? What is your Windows version?

**Comment by idealkindom** [comment]
Yes, .NET 8 is correctly intalled. I installed and uninstalled version 7.0.9 and 6.2.4 for several times to see, I guess maybe there are some problem in compatibility or say consistency in the core.However , I'm not sure for that untill.now . Recently I have been busy somehow, I Will keep testing and try to clarify if I  could find the rules of occurrance.
















At 2024-10-21 17:27:43, "Ned Ganchovski" ***@***.***> wrote:

Hi!

Are you sure you installed .NET 8.0 as well? What is your Windows version?
