### ISSUE TITLE
Issue with Using the #input Command

### ISSUE THREAD

**Issue by mattiasstok** [Proektsoftbg/Calcpad#374]
When using the #input command, it appears that the value of the input box does not update in the current calculation. For instance, consider the following code:
```
b = ? {3}
10*b
#input
c = ? {4}
10*c
```
In this example, when I run the code, I can change the value of `b` to 5, and it correctly calculates `10*b` as `10*5=50`. However, after using the #input command to change the value of `c` to 6, it continues to calculate `10*c` as `10*4`. The correct value is only used after I run the entire code again, indicating that the previous input value is retained.

It's possible that I may not fully understanding how the #input command works.

Could you please investigate this issue?  Thank you.

**Comment by sononicola** [comment]
Yep it seems to be a bug and it's related to this my discussion: #372

**Comment by Proektsoftbg** [comment]
Hi!

This is now fixed in version 7.1.0:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v7.1.0
