### ISSUE TITLE
Unexpected error: Index was outside the bounds of the array. Please check the expression consistency.

### ISSUE THREAD

**Issue by strsthapa** [Proektsoftbg/Calcpad#375]
was playing with latest calcpad version, error comes when the matrix has >70 number of rows. I have included output.txt and try to print WBEAMDATA but results this error. It works well up to 70 number of rows or if I divided the input data into 70 multiple data and augment or stack the matrix.
[output.txt](https://github.com/user-attachments/files/17523315/output.txt)

**Comment by Proektsoftbg** [comment]
Hi!

This is now fixed in version 7.1.0:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v7.1.0
