### ISSUE TITLE
Rotational work unit not recognized as an energy unit (J)

### ISSUE THREAD

**Issue by gogomichoud** [Proektsoftbg/Calcpad#381]
Hi!

Rotational work is not recognized as an energy unit (J).

Exemple :
|   | Code                    | Output                                                                                                                            |
|---|-------------------------|-----------------------------------------------------------------------------------------------------------------------------------|
| 1 | angle = 0.9rad          | angle = 0.9 rad                                                                                                                   |
| 2 | torque = 4N.m           | torque = 4 N·m                                                                                                                    |
| 3 | work = angle*torque     | work = angle·torque = 0.9 rad·4 N·m = 3.6 kg·m2/s2·rad                                                                            |
| 4 | work2 = angle*torque\|J | Error in "work2 = angle*torque\|J" on line [4]: The calculated units "kg·m^2/s^2·rad" are inconsistent with the target units "J". |

I guess that is related to the dimensionless "rad" component of the work output unit. which result in a error due to units consistency (kg·m^2/s^2·rad VS kg·m^2/s^2==J)

This causes problem with units consistency on the next step of calculation.

**Comment by Proektsoftbg** [comment]
Hi!

Yes, these units are not consistent with `J`. But if you convert them to '|J*rad' it will work. Angle units are implicit and for many reasons they do not convert to unitless values automatically. So, everything will be just fine if you get rid of the implicit `rad` units from the very begining.  Use explicit `#rad` units:
```
#rad
angle = 0.9'rad
torque = 4N*m
work = angle*torque|J
```

**Comment by gogomichoud** [comment]
Thanks for that really fast answer!
