### ISSUE TITLE
Error on matrix determinant calculation

### ISSUE THREAD

**Issue by javila** [Proektsoftbg/Calcpad#392]
Hi!

I was reading the instructions to install Calcpad on Linux and I noticed an error on matrix determinant calculation shown in [CLI screenshot example](https://github.com/Proektsoftbg/Calcpad/raw/main/Setup/Linux/Images/Cli.png). The correct determinant answer should be -2.

After doing some calculations, I found out that Calcpad is calculating $\det(A) = \det(L)\det(U)$, as I later verified it in _GetDeterminant(Matrix lu)_ function in [Calcpad.Core/Matrix/Matrix.cs](https://github.com/Proektsoftbg/Calcpad/blob/main/Calcpad.Core/Matrix/Matrix.cs) source code. However, the correct calculation should be $\det(A) = \det(P)\det(L)\det(U)$, where $P$ is the permutation matrix used in LU decomposition.

**Comment by Proektsoftbg** [comment]
Hi!

Thank you so much for reporting this. You are absolutely right.

I checked and I found that I have missed to account for the determinant sign flips during pivot row interchanges. I will fix this now and issue and update soon. No need to build the P matrix implicitly, there is another way to do this much easier as recommended in the "Numerical Recipes in C" book.

**Comment by javila** [comment]
Hi!

You absolutely right. You really don't need to build the P matrix.

**Comment by Proektsoftbg** [comment]
Hi!

This is now fixed in version 7.1.3:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v7.1.3

The updated Linux packages are available here:
https://github.com/Proektsoftbg/Calcpad/tree/main/Setup/Linux
