### ISSUE TITLE
Problem when using the percentage sign %

### ISSUE THREAD

**Issue by KrisPL7** [Proektsoftbg/Calcpad#397]
Hello! 

There seems to be a calculation issue when using % for decimals. (in engineering, strain is sometimes recorded as %)

I'm not sure if it's worth considering. The following image is provided for reference:

![image](https://github.com/user-attachments/assets/0dc5c73a-49e1-499e-aa46-ca2ffc903ea7)

**Comment by Proektsoftbg** [comment]
Hi!

Thank you very much for reporting this. It is a serious issue and is definitely worth paying attention to it.
I will take a look now and fix it.

**Comment by javila** [comment]
Hi, Ned!

I did some quick tests and the problem is probably related to pow function:

![Screenshot 2024-11-28 081916](https://github.com/user-attachments/assets/ea31eef1-68cd-4bb9-b917-86f279b8ea30)

I didn't check the code yet, but maybe it would be necessary to just change the % "unit" to its real value "0.01" before the calculation, no?

**Comment by Proektsoftbg** [comment]
Hi! Thank you very much for your effort. The feadback you provided is very valuable to find where the problem is. Can you please also post the code you used to generate this output? This will save some time to me.

**Comment by javila** [comment]
Hi! Here is the code I used:

a = 3.3%
b = 0.033

a - b
b - a
a ≡ b

a^1
b^1

a^1 - b^1
b^1 - a^1
a^1 ≡ b^1

sqrt(a)
sqrt(b)

c = 1‰
d = 0.001
c ≡ d

c^1
d^1

**Comment by Proektsoftbg** [comment]
Great! Thank you so much! I will come back soon...

**Comment by javila** [comment]
Pardon me if I say some stupid thing now but...

If you change the line 1689 of Calcpad.Core/BaseTypes/Unit.cs file to:

`var result = (u*u.GetDimensionlessFactor()).Pow((float)d) / u.GetDimensionlessFactor();`
or
`var result = u.Pow((float)d) * u.GetDimensionlessFactor().Pow(((float)d)-1.0);`
(or something like that)

Would that fix the problem? Of course you would need to do something similar to root function.

(I'm sorry. I can't test my suggestion at the moment...)

**Comment by Proektsoftbg** [comment]
Hi!

I think I fixed it. Also added cbrt, root and everything that can be affected. It seems to me that everything works now, but please also try by yourself. I haven't still issued a release. You can use the source code or download and reinstall it from here:
https://github.com/Proektsoftbg/Calcpad/blob/main/Setup/calcpad-VM-setup-en-x64.zip

Uninstall the old version before that, just for case.

![image](https://github.com/user-attachments/assets/71153334-c432-46b7-93c9-9b1055e08a02)

**Comment by Proektsoftbg** [comment]
OK. I also tried to make a and b vectors and matrices and it also works. If you cannot find any other problems, I will issue a new release with these fixes. Even, if any, we can always fix them in the future. :)

**Comment by KrisPL7** [comment]
It’s working fine now, thanks. :)
