### ISSUE TITLE
Macro: replace order bug(?)

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#40]
There some problem that short variables can to brake more long variables:
```nginx
#def MACRO1$(Dx$; x$)
    x$ + Dx$
#end def
#def MACRO2$(x$; Dx$)
    x$ + Dx$
#end def

MACRO1$(10; 20)'shows 20+10=30
MACRO2$(10; 20)'Error in "10 + D10" on line [2]: Undefined variable or units: "D10".
```
I'm not shure is it bug or not, but can we replace variables from long to short order?

**Comment by Proektsoftbg** [comment]
Yes, It is a bug. Variables are parsed from longer to shorter. But for replacement, I simply used the string.Replace() method in C#, cycling through the parameter in their original order. The best way is to write custom replace method that does the job in just one pass, but it will take time.

Now, I can make a quick fix by preliminary sorting the parameters by their length - from longer to shorter and perform the replacement in this order.

**Comment by Proektsoftbg** [comment]
@cser, I fixed this in version 5.8.2. release:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v.5.8.2

**Comment by cser** [comment]
✔ This works:
```enginx
#def MACRO1$(Dx$; x$)
    x$ + Dx$
#end def
#def MACRO2$(x$; Dx$)
    x$ + Dx$
#end def

MACRO1$(10; 20)'shows 20+10=30
MACRO2$(10; 20)'shows 10+20=30
```
❌ But what happened with one-symbol parameters?
```enginx
#def MACRO$(a$; b$)
    a$ + b$
#end def
```
Shows: There were errors processing includes and macros. #Error in "#end def" on line [[3](about:blank#0)]: An item with the same key has already been added. Key: 2 (Parameter 'key')

**Comment by cser** [comment]
@Proektsoftbg, it's not a problem with one-symbol parameters, it's problem with similar length parameters.
This OK:
```
#def MACRO1$(a$; bb$) = a$+bb$
```
This shows error:
```
#def MACRO2$(aa$; bb$) = aa$+bb$
```

**Comment by Proektsoftbg** [comment]
Sorry, It was a little bit more complicated than I thought.
Now it is OK. I ammended the same release, so, you can download and install it again.
https://github.com/Proektsoftbg/Calcpad/releases/tag/v.5.8.2

**Comment by cser** [comment]
Thanks! It works correctly now (so big problems not found at least)
