### ISSUE TITLE
Plotting a sin curve results in straight line

### ISSUE THREAD

**Issue by graott** [Proektsoftbg/Calcpad#402]
It seems all versions of calcpad after 6.1.7 plot sin curves as a straight line. The code below reproduces the effect:
``` 
    pk = 20
    d = 20
    a(t) = pk*sin(t*π/d)
    $Plot{a(t) @ t = 0 : d}
```
in 6.1.7 you get the following graph: 
<img width="447" alt="Calcpad 6 1 7" src="https://github.com/user-attachments/assets/5d91a0e0-ac2a-4da3-a4f4-bf2e08c6bcfb">
7.1.4 produces this graph:
<img width="463" alt="Calcpad 7 1 4" src="https://github.com/user-attachments/assets/10a2c329-7be0-4fdb-b996-0ace2cb6907e">

**Comment by Proektsoftbg** [comment]
Hi! Maybe it is in degrees. Write `#rad` on the top row.

**Comment by graott** [comment]
I can't believe I missed that! Thanks so much for the help.
