### ISSUE TITLE
A strange bug introduced after v6.2.4

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#416]
The following code runs well on V 6.2.3, but errors since V 6.2.4, and the message goes"Unexpected error: An expression of type 'Calcpad.Core.Value' cannot be used to initialize an array of type 'Calcpad.Core.IValue' Please check the expression consistency."
```
D = 4.42
Q = 597.31
Lmin = 7.5
Lmax = 50
P_1(L) = 1.84*Q/(D^2*L) + 0.446*sqrt(Q/(D^2*L))
P_2(L) = 0.17655*(Q/(D^2*L))^(1/3) + 0.0313*(Q/(D^2*L))^(2/3) + 2.589*(Q/(D^2*L))
P_3(L) = switch(and(D/Q^(1/3) ≥ 0.2; D/Q^(1/3) ≤ 1.0); 2.6125*(D/Q^(1/3))^(-1.775)*(L/Q^(1/3))^(-0.886); D/Q^(1/3) > 1.0; 2.6102*(L/Q^(1/3))^(-0.886))
$Plot{P_1(L) & P_2(L) & P_3(L) @ L = Lmin : Lmax}


```

**Comment by javila** [comment]
Hi!

I did some tests and I think the problem may be related to the **and( )** function. The code worked pretty fine in v.7.1.4 when I change your **P_3(L)** function to:

`P_3(L) = switch(((D/Q^(1/3) ≥ 0.2) ∧ (D/Q^(1/3) ≤ 1.0)); 2.6125*(D/Q^(1/3))^(-1.775)*(L/Q^(1/3))^(-0.886); D/Q^(1/3) > 1.0; 2.6102*(L/Q^(1/3))^(-0.886))`

Your original code works in Calcpad's website IDE running Core v.6.2.4.0 though.

BTW, it would be nice if a multiplot graph could have a legend, no?

**Comment by idealkindom** [comment]
> Hi!
> 
> I did some tests and I think the problem may be related to the **and( )** function. The code worked pretty fine in v.7.1.4 when I change your **P_3(L)** function to:
> 
> `P_3(L) = switch(((D/Q^(1/3) ≥ 0.2) ∧ (D/Q^(1/3) ≤ 1.0)); 2.6125*(D/Q^(1/3))^(-1.775)*(L/Q^(1/3))^(-0.886); D/Q^(1/3) > 1.0; 2.6102*(L/Q^(1/3))^(-0.886))`
> 
> Your original code works in Calcpad's website IDE running Core v.6.2.4.0 though.
> 
> BTW, it would be nice if a multiplot graph could have a legend, no?

Thanks for finding a way flanking the problem. BTW,since and(A;B;...) is equivalent to A^B^...， you just helped to confirm that this is a bug. Right?

**Comment by Proektsoftbg** [comment]
Hi! Yes, this is a bug in the compiler. After introducing vectors and matrices, operator and function arguments where abstracted with IValue interface. Some functions just still miss to return the correct type. I fixed it and will publish in the next few days.

**Comment by Proektsoftbg** [comment]
Hi!

Now it works in version 7.5.1:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v7.1.5

![image](https://github.com/user-attachments/assets/90ebe807-f97a-4c87-aef6-0410bc66b191)

**Comment by idealkindom** [comment]
> Hi!
> 
> Now it works in version 7.5.1: https://github.com/Proektsoftbg/Calcpad/releases/tag/v7.1.5
> 
> ![image](https://private-user-images.githubusercontent.com/90918363/396112085-90ebe807-f97a-4c87-aef6-0410bc66b191.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MzU0MjQsIm5iZiI6MTczNDQzNTEyNCwicGF0aCI6Ii85MDkxODM2My8zOTYxMTIwODUtOTBlYmU4MDctZjk3YS00Yzg3LWFlZjYtMDQxMGJjNjZiMTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDExMzIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMDA0YmI3MDJmN2M4N2MyNzdlOTczOTU4MWM3NjEwMTY2YWE5ZTZkYjRmMzJhZGVjZjVmOTU1ODI0NThhYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zmLGRBNmAfcOzgYUmVpK6VkBQHe3pRUiArNB6usE8HM)

Nice work.
