### ISSUE TITLE
Possibly a bug with #round command?

### ISSUE THREAD

**Issue by javila** [Proektsoftbg/Calcpad#417]
Hi!

The _#round_ command isn't affecting the "typed in" numbers; only the calculated ones. The "typed in" numbers are still being affected by the _Round input box_ value in the bottom left of the Calcpad screen. Is this a bug or am I doing something wrong?

This is what I get with **#round 5** command and **Round 2** in the input box:

#round 5
C_G = 1.23456*(1.23456)^-1.23456

![test_round](https://github.com/user-attachments/assets/9900792c-3e17-441f-b45f-e2033b17a47f)

IMHO, I think the "typed in" numbers shouldn't be formatted/rounded at all.

**Comment by Proektsoftbg** [comment]
Hi!

Thank you for your feedback. Yes, currently it affects only the final result. This is how we made it.  But you are right, it looks like a bug in this way. It is more logical to completely replace the UI Round setting.

You also rise and interesting discussion. Should "typed in" numbers be rounded? I definitely have to think about that. I hope also other users share their opinion here.

**Comment by jgagnonNT** [comment]
In my opinion Input "typed in" numbers should not be rounded at all.
When verifying someone else's calculation, it would make it easier to attest that the input was correct.

**Comment by Proektsoftbg** [comment]
Hi!

I fixed the #round function in version 7.1.5:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v7.1.5

However, about hard coded constants, it is not easy now to not format them. Currently Calcpad formats all numbers in the output and it is not so easy to change that. For example, some decimal numbers cannot be represented exactly in binary. 0.1 will become  0.100000000000000005551115123126 without any rounding. There are also some other problems that need to be solved and it will take time. So, for now I will leave this as is. It is also not so bad.

![image](https://github.com/user-attachments/assets/410d1b1c-4bf8-4136-955c-887bf3ad01f3)
