### ISSUE TITLE
conventions changed between V6.2.3 and V 7.1.4

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#419]
Recently, I use V7.1.4 to run some compiled cpdz files formerly built with V6.2.3. I  found there are some conventions changed between the two big versions.
I will gradually test those cpdz with both Versions and list the problems I confronted with here:

1. It looks like Comments after any command begun with "#" cause errors now(2024.12.12 reported).Here I supplement with the sample codes which error in V 7.1.4 but run normally in V6.2.3:
```
n = ? {2}
#post
#repeat n'<!----中adaff--!>
#input'<!----中adaff--!>
a = ? {1}'.
#post'<!----中adaff--!>
#if a > 0'<!----中adaff--!>
b = a
#else'<!----中adaff--!>
b = a + 1
#end if'<!----中adaff--!>
#loop

```
2. a ＃repeat n  #loop include ＃input and #post，than the calculation after the ＃post but contains the value of input parameters will show errors during run but dispear after input and continuation of calculation. This however would not happen in V 6.2.3.Here I gave a sample of codes which V 7.1.4 and V6.2.3 gives different process experiences.
```
n = ? {2}
#post
#repeat n
#input
a = ? {1}'.
#post
#if a > 0
b = a
#else
b = a + 1
#end if
#loop
```
@Proektsoftbg

**Comment by Proektsoftbg** [comment]
Hi!

Yes, it has changed, because it was a sort of a bug before.
Actually, it was never intended to have some sort of code after 'sharp' keywords, like:
`#else'abcd`

It didn't display it anyway, but one could put for example:
`#end if x=2`

This will secretly change the value of x to 2 without displaying it. It is potentially dangerous, not clear and not a good coding style. So, I added a check for that. Keywords that do not implicitly require some code like `#else`, `#end if`, `#loop`, etc are forced to be standalone on the line.

**Comment by idealkindom** [comment]
Then how about the second one ,bug or not?













At 2024-12-14 01:35:03, "Ned Ganchovski" ***@***.***> wrote:

Hi!

Yes, it has changed, because it was a sort of a bug before.
Actually, it was never intended to have some sort of code after 'sharp' keywords, like:
#else'abcd

It didn't display it anyway, but one could put for example:
#end if x=2

This will secretly change the value of x to 2 without displaying it. It is potentially dangerous, not clear and not a good coding style. So, I added a check for that. Keywords that do not implicitly require some code like #else, #end if, #loop, etc are forced to be standalone on the line.

**Comment by Proektsoftbg** [comment]
I still cannot say. I am working on it now.

**Comment by Proektsoftbg** [comment]
I tested the second one on version 7.1.5 and it is working perfectly. Probably, it was somehow fixed in the way, but I cannot tell exactly.

**Comment by Proektsoftbg** [comment]
Hi! This is what it shows and it is as expected:

![image](https://github.com/user-attachments/assets/b66f63fd-cc4f-4ccc-a597-4e3ebbdf2afa)

**Comment by idealkindom** [comment]
> Hi! This is what it shows and it is as expected:
> 
> ![image](https://private-user-images.githubusercontent.com/90918363/396115892-b66f63fd-cc4f-4ccc-a597-4e3ebbdf2afa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MzUzODgsIm5iZiI6MTczNDQzNTA4OCwicGF0aCI6Ii85MDkxODM2My8zOTYxMTU4OTItYjY2ZjYzZmQtY2M0Zi00Y2NjLWE1OTctNGUzZWJiZGYyYWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDExMzEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMzk1ODhhNTI1NWRkZWQ1MWRiMDg3N2I3MTVmNTFhZDY1MzdkMjIwODljMTBlNmMxMmJjNjE3OTdhNWQwYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9Y6MujA-GxTUq1W15F_AWDqEj69266Gp99zwVmuLies)

Nice work.
