### ISSUE TITLE
V 7.1.4 Portable's bug in displaying Matrices for output

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#424]
<img width="959" alt="7 1 4 portable bug in displaying Matrices" src="https://github.com/user-attachments/assets/335fc644-b125-46d1-92c0-e08c13a928d2" />
One screenshot is enough to show the problem.

**Comment by Proektsoftbg** [comment]
Hi!

It is working fine on my side. Please, open doc/template.html with Notepad and search for ".matrix" in the CSS. Date should be 20.09.2024.

Maybe some old files have remained that were not replaced.

**Comment by idealkindom** [comment]
> Hi!
> 
> It is working fine on my side. Please, open doc/template.html with Notepad and search for ".matrix" in the CSS. Date should be 20.09.2024.
> 
> Maybe some old files have remained that were not replaced.

Thks a lot. I'm sorry that I forgot to update the template.html.Now I close this issue.
