### ISSUE TITLE
Old bug with html/svg single tags breaking

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#43]
This a same old bug that now it's already annoying.
The code `'<span/>'` shows this: `<span/ id="line1">`
Expected `<span/>` or `<span id="line1"/>`
(`'<span></span>'` works correctly: `<span id="line2"></span>`)

**Comment by cser** [comment]
Elso `'<span''/>'` works normally, this transforms to `<span   />`. Without `''` - no metter how much spaces - it breaks tag by id.

**Comment by Proektsoftbg** [comment]
Hi @cser, this one was also fixed in the ammended v5.8.2.

**Comment by cser** [comment]
Yes, it dont breaks tag now: `<span id="line1"/>`
