### ISSUE TITLE
problem for output to MS Word with code automating Headings numbering

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#431]
Here I give the code of cpd:
```
"Test atoumatic Number list for Headings
'<ol>
'<li><h4>This is the 1st Heading.</h4></li>
'generally in Calcpad the output window display normally.However when you output to MS Word it errors.
'<li><h4>This is the 2nd Heading.</h4></li>
'<li><h4>This is the 3rd Heading.</h4></li>
'</ol>
```
Try to output to MS Word you will reproduce the error.

**Comment by Proektsoftbg** [comment]
Yes, you cannot have heading in list. Also paragraph in list, paragraph in heading, heading in paragraph, etc. All this will display in Html, but now in Word. This is because Word is more strict about the document structure than web browsers. You cannot have two block level elements one inside the other. Normally you can have one block level element like `h`, `p` or `li` that contain inline elements like `b`, `i`, `span`, etc.

**Comment by idealkindom** [comment]
> Yes, you cannot have heading in list. Also paragraph in list, paragraph in heading, heading in paragraph, etc. All this will display in Html, but now in Word. This is because Word is more strict about the document structure than web browsers. You cannot have two block level elements one inside the other. Normally you can have one block level element like `h`, `p` or `li` that contain inline elements like `b`, `i`, `span`, etc.

Al right, though good idea to automatic numbering , bad idea for output.

**Comment by Proektsoftbg** [comment]
In general, auto-mumbering of headings is performed by using CSS:
```
'<style>body{counter-reset:h3;}h3::before{counter-increment:h3;  content:counter(h3)". ";}</style>
'<h3>Heading</h3>'
'<h3>Heading</h3>'
'<h3>Heading</h3>'
```
<img width="495" alt="{56FA59CB-AA4A-49E2-A833-1B3BCC4AA1FA}" src="https://github.com/user-attachments/assets/63d14b96-1fac-4fa3-8ce7-fd5c152de653" />

It is not supported by Word, but also does not produce errors. In word, you can again autonumber it. Probably the best way in Calcpad is to use a Calcpad variable for that purpose:

```
'<!--'NH = 0'-->
#def nh3$(s$)
#val
'<h3>'NH = NH + 1'. s$</h3>
#equ
#end def
nh3$(Heading)
nh3$(Heading)
nh3$(Heading)
```
<img width="380" alt="{9272621D-188B-4331-AC23-E1D40006EA71}" src="https://github.com/user-attachments/assets/31780fdb-2a08-4e7b-b4d3-47643bc8fae9" />

In Word, numbers will appear, but will not be automatic. The best option is to add a native Calcpad autonumbering that will be supported in both Html and Word.

**Comment by idealkindom** [comment]
> In general, auto-mumbering of headings is performed by using CSS:
> 
> ```
> '<style>body{counter-reset:h3;}h3::before{counter-increment:h3;  content:counter(h3)". ";}</style>
> '<h3>Heading</h3>'
> '<h3>Heading</h3>'
> '<h3>Heading</h3>'
> ```
> 
> <img alt="{56FA59CB-AA4A-49E2-A833-1B3BCC4AA1FA}" width="495" src="https://private-user-images.githubusercontent.com/90918363/397937584-63d14b96-1fac-4fa3-8ce7-fd5c152de653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDU2OTMsIm5iZiI6MTczNDgwNTM5MywicGF0aCI6Ii85MDkxODM2My8zOTc5Mzc1ODQtNjNkMTRiOTYtMWZhYy00ZmEzLThjZTctZmQ1YzE1MmRlNjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE4MjMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNWU3NWU5MTkyYWY1ZmNiOWE2MmZmZTUzNTkzNTZiZjlkZTNhYTdkM2U2ODQzY2M2ZmU2MDFjYTRjZmQ4YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kEtZBVZpLt73QycO02wDenLpF0azyLQu9qKVPVljoOk">
> 
> It is not supported by Word, but also does not produce errors. In word, you can again autonumber it. Probably the best way in Calcpad is to use a Calcpad variable for that purpose:
> 
> ```
> '
> #def nh3$(s$)
> #val
> '<h3>'NH = NH + 1'. s$</h3>
> #equ
> #end def
> nh3$(Heading)
> nh3$(Heading)
> nh3$(Heading)
> ```
> 
> <img alt="{9272621D-188B-4331-AC23-E1D40006EA71}" width="380" src="https://private-user-images.githubusercontent.com/90918363/397937882-31780fdb-2a08-4e7b-b4d3-47643bc8fae9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDU2OTMsIm5iZiI6MTczNDgwNTM5MywicGF0aCI6Ii85MDkxODM2My8zOTc5Mzc4ODItMzE3ODBmZGItMmEwOC00ZTdiLWI0ZDMtNDc2NDNiYzhmYWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE4MjMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNDE5NjAzYjMyN2RiMDFiZWEyMGQzMzUyODdlNTc2N2I3YTBiNWFlZTk0OTdkZGMyOTg3M2JjZWE0NTg5ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g8i5ulRzUE08QsstnJbaYYYe6lNtDaXdijAoeX3GMms">
> 
> In Word, numbers will appear, but will not be automatic. The best option is to add a native Calcpad autonumbering that will be supported in both Html and Word.

I like the method of defining a customized macro, which I will use definitely.
