### ISSUE TITLE
An example pertaining to the program dose not work properly

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#432]
The example of "Area of reinforcement bars", as I see, does not work properly as before, for which I attached a screenshot behind.
<img width="511" alt="2024-12-21_Area of reiforcement Bars" src="https://github.com/user-attachments/assets/4610c599-53d9-40b3-9dbd-6f1fe3c227ad" />
Another thing is that I played with the only example in the path of Examples\Structural Design\Steel, I see there is comment after a "#if", however it looks to work on 7.1.5 without problem. But I remember that I was told that conventions changed that any commnets after a "#"command are not allowed.

**Comment by Proektsoftbg** [comment]
Hi! It works on my side. Can you please tell what is exactly the problem. I cannt see it from the picture.
I also do not have a folder steel. Probably this example has remained from older versions and removed later.
#if allows text after the keyword because you have to specify the condition. #else and #end if does not.
In a similar way, #repeate, #while and #for allow, but #loop not.

**Comment by idealkindom** [comment]
> Hi! It works on my side. Can you please tell what is exactly the problem. I cannt see it from the picture. I also do not have a folder steel. Probably this example has remained from older versions and removed later. #if allows text after the keyword because you have to specify the condition. #else and #end if does not. In a similar way, #repeate, #while and #for allow, but #loop not.

I remember I used this some time back that the qualified resulting reinforcement bar will be displyed like a upstair so from a blink of eyes you could tell which result to implement.

But with the screenshot I attached you have to read to figure it out.

I also read the code there are some specifications of color.

**Comment by idealkindom** [comment]
> Hi! It works on my side. Can you please tell what is exactly the problem. I cannt see it from the picture. I also do not have a folder steel. Probably this example has remained from older versions and removed later. #if allows text after the keyword because you have to specify the condition. #else and #end if does not. In a similar way, #repeate, #while and #for allow, but #loop not.


> Hi! It works on my side. Can you please tell what is exactly the problem. I cannt see it from the picture. I also do not have a folder steel. Probably this example has remained from older versions and removed later. #if allows text after the keyword because you have to specify the condition. #else and #end if does not. In a similar way, #repeate, #while and #for allow, but #loop not.

There is another old example cpd called Optimization of foundation pad dimensions, which on my PC could not give a purposed legend.
<img width="477" alt="2024-12-22_02-24-56bug on lengend" src="https://github.com/user-attachments/assets/76671c2c-326d-4327-b8db-9eb2286bec2d" />
