### ISSUE TITLE
usual function parsing bug - missing ')'

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#46]
```
a = 1/2
switch(a ≡ 1/2; max(1mm; 2mm); 0mm)
```
Shows error: Error in "switch(a ≡ 1/[2](about:blank#0); max(1mm; 2mm); 0mm)" on line [2]: Missing right bracket ')'.
If fraction or `mm` missing - works correctly.

**Comment by idealkindom** [comment]
I tried with adding symbol of multipilication "*" and it works well.

**Comment by idealkindom** [comment]
Without "*" yes it errors.

**Comment by Proektsoftbg** [comment]
This is fixed in v.5.8.3. #48.

![image](https://user-images.githubusercontent.com/90918363/185739689-76c8f6d7-c1fe-44c2-9be6-3a9782e43a4e.png)

**Comment by cser** [comment]
Thank you very much!
