### ISSUE TITLE
The problem of function &root

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#50]
I tried the equation of x^2-2*x+1=0，but it can not find a solution in the range of(-1,2)

**Comment by Proektsoftbg** [comment]
No, it cannot. Not it this case.

Calcpad uses numerical methods to find the root. It does not solve the equation symbolically. It cannot fnd the root by algebraic operations as we would do in this case. The method used in Calcpad is a combination between [bisection](https://en.wikipedia.org/wiki/Bisection_method) and Anderson Bjork's method. It works only if the function is **continuous** and has **opposite signs** at the ends of the interval. Then, according to the Boltzano (immediate value) [theorem](https://en.wikipedia.org/wiki/Intermediate_value_theorem), at least one root exists. If there is exactly one root, bracketing methods, such as the one in Calcpad has guaranteed convergence and will always find it.

The function in your example transfprms to (x - 1)^2 and has a double root x_1 = x_2 = 1. It does not crosses the x-axis, so it cannot not have opposite signs at the end of the initial interval:

![image](https://user-images.githubusercontent.com/90918363/187047782-94b2c1df-b652-410c-9d23-f712f6dfbdfc.png)

This is one of the few special cases where you cannot use any bracketing methods to find the root. Such are all functions that are entirely positive or negative and only touches the x-axis at a single point. But you can use Newton's or secant methods.

So use the $root method in cases where the function crosses the x-axis (or x=const line) and has opposite signs at the end of the initial interval. Probably we have to include these explanations in the documentation.

**Comment by Proektsoftbg** [comment]
If you are interested, we published a paper about the root founding algorithm in Calcpad. We compared it to other similar methods and it apprered to be the faster of all other bracketing methods on average basis:

https://storage.googleapis.com/morressier_call_for_papers_production/674df2b0-daae-4d2b-a92f-1ce76c01258e.pdf
