### ISSUE TITLE
Not intuitive Find and replace focus

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#57]
Steps to reproduce:
- Press Ctlr+F - it shows find and replace dialog
- Write text to find
- Press Enter - it select first occurence - all works as expected
But then something unexpected happens: It focus on text area with code and after enter pressing - it insert a new line. And after all, Esc doesn't hide dialog.

Expected behaviour like a Notepad++/CudaText/Sublime Text/Notepad3/LibreOffice Writer/Microsoft Word. Focus must be on dialog, and after second enter pressing it must search next word. When Esc pressing - it hides dialog and focus moves to text area with code.

**Comment by Proektsoftbg** [comment]
@cser, thak you for reporting this!

I fixed it in version 5.8.5 together with a few more minor things:

https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.8.5
