### ISSUE TITLE
Output visual

### ISSUE THREAD

**Issue by jgagnonNT** [Proektsoftbg/Calcpad#59]
Hello,

It seems something changed in the recent versions of the software in the output windows, now the variables are stacked and hide some part of the divisors. Zooming in or out does not seems to change anything.

Version 5.8.5:
![image](https://user-images.githubusercontent.com/111089248/188720440-683e0a96-ce16-4551-bda4-b353f1aedb16.png)

Version 5.8.1:
![image](https://user-images.githubusercontent.com/111089248/188720490-074111bd-c583-4cad-babc-dfbe33a19e0f.png)

**Comment by Proektsoftbg** [comment]
Thank you! I am so sorry! :(

It was the CSS in the html template. Some margin was corrupted.

Now I fixed it and updated the last release.
