### ISSUE TITLE
Strings data

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#6]
How it works without string data:
```
R_y = 265MPa
R_u = 430MPa
#hide
CARBON = 1
AUSTENITIC = 2
steel = CARBON
#show
#if steel ≡ CARBON
    'Steel is CARBON'
    #if R_y/R_u ≥ 0.7
        n_y = 2.7'- for 'R_y/R_u'≥0.7:
    #else
        n_y = 2.3' - for 'R_y/R_u'<0.7:
    #end if
    #else if steel ≡ AUSTENITIC
        'steel is AUSTENITIC
    n_y = 1.8
#end if
R_yn = R_y/n_y
```
With string data:
```
R_y = 265MPa
R_u = 430MPa
#hide
steel = `CARBON`
#val
'Steel is 'steel
#if steel ≡ `CARBON`
    #if R_y/R_u ≥ 0.7
        n_y = 2.7'- for 'R_y/R_u'≥0.7:
    #else
        n_y = 2.3' - for 'R_y/R_u'<0.7:
    #end if
#else if steel ≡ `AUSTENITIC`
    n_y = 1.8
#end if
    R_yn = R_y/n_y
```
It looks much better, don't you think so?

**Comment by Proektsoftbg** [comment]
Yes, this would be a good option. Thank you for your suggestion!

**Comment by StephaneIFO** [comment]
Hi, 
I have just discovered this software and it is very promising, bravo !
About string data, is it supposed to work with version 5.6.3 or did you close the ticket because the function will not be developed ? 
Stéphane

**Comment by Proektsoftbg** [comment]
Hi,

Thank you for your kind appreciation.

String variables will be a good option indeed and we consider adding it in the future. It is not available in version 5.6.3. Before that we are going to develop vector and matrix calculations. The program is young and there are a lot more to add. I closed it for now because there is nothing to discuss. When the time comes, we can always reopen it or just open a new one. :)

**Comment by berkdemir** [comment]
Hi, is this still in the same state?
When I checked the help, I thought that #def variable_name$ = "content" would work.
Currently, we don't have any option to assign a string to a variable, right?

**Comment by Proektsoftbg** [comment]
Hi!

`#def variable_name$ = "content"` actually works. But this is a macro variable. We do not have native string variables like, say in Python. I am afraid currently this task goes var beyond the capabilities of this project.

However, macro variables are very useful for many cases. You can check this example:
https://github.com/Proektsoftbg/Calcpad/blob/main/Examples/Demos/TT%20Panel.cpd
