### ISSUE TITLE
F4 / F5

### ISSUE THREAD

**Issue by hildebrandopsj** [Proektsoftbg/Calcpad#60]
@Proektsoftbg, i notice when i press F5 to calculate and press F5 again, all the input data is gone.

I notice too when after i press F5 for the first time and press F4, we don't return to input form. I don't know if this is a bug or not.

**Comment by Proektsoftbg** [comment]
Hi, Thank you for reporting this!

About F5-F5, I tried it many times but could not reproduce it. Does it happen each time? Can you please try this on some of the ready made examples?

About F5-F4, it is not a bug. F4 is disabled when the calculations are on. That is because, Calcpad needs to reed all the input fields from the html form, before unlocking the code and chache them. Otherwise, they will always reset to the default values when you are back.

**Comment by hildebrandopsj** [comment]
Thank you! I Will try this on my personal computer and inform you.

It would be great If we have a hotkey to unlock the form, for example: today i verified 45 sections or more of reinforced concrete. With a hotkey, i dont need to use mouse to do this repetitive task.

**Comment by Proektsoftbg** [comment]
The hotkey is to press again F5 and you should get back to the input form. It works on my side, but it is interesting why you loose the input data. I suppose that there is some specific reason for that and we will discover it.

**Comment by hildebrandopsj** [comment]
I cannot reproduce the error in my personal computer. Strange...

**Comment by Proektsoftbg** [comment]
@hildebrandopsj  Such bugs are the nastiest ones - that happen occasionally and it is difficult to discover them. So, you can continue working as normal, and if it happens once again some day, you will probably notice how. I will also keep an eye on it. Thanks!

**Comment by hildebrandopsj** [comment]
Thank you so much!

**Comment by Proektsoftbg** [comment]
@hildebrandopsj I think I managed to locate this problem and fix it. I hope input vaules will never reset to zero anymore. I ammended the latest release #v5.8.6:

https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.8.6

**Comment by Proektsoftbg** [comment]
It is related to error tooltips that was recently added. Input values are also stored in tooltips and some conflicts occured. I the latest release,  also made tooltips to open after 0.5s which is quite comfortable. Also, added some cool dark design:

![image](https://user-images.githubusercontent.com/90918363/190724213-e17f8292-df99-4771-91b1-0ff22c5fe9cf.png)
