### ISSUE TITLE
units for Electrical engineering are not correctly displayed

### ISSUE THREAD

**Issue by HEA-sGuzman** [Proektsoftbg/Calcpad#61]
I'm having issues with proper conversion of electrical engineering units for example 1A*1V does not equal 1W but I get kg*m^2/s^3.

This seems to apply for any equation involving Volts,Amps,Ohms, and Watts. 

Also, if this is not possible, is there a way to create custom units ?

Any help would be appreciated

**Comment by Proektsoftbg** [comment]
Hi!

By default, arithmetic operations decompose the units to basic physical dimensions. This is how it works, even in MathCAD. To convert the result to the desired units just add a vertical bar and the units, e.g.:

`A*V | W`

BTW, in physics, 1W = 1J/s = 1Nm/s = 1kg*m^2/s^3. This is what you actually get.

Calcpad is actually able to compose the desired units by default, but we need to explicitly add this feature. This will save you writing the output units each time for trivial cases. We already did this for mechanical units. I can do the same for electrical uints, but I need help by an electical engineer. If you send me the formulas and what units do you need to get by default for each formula, I will be able to set these defaults. I am a structural engineer and I am not quite sure, I can do this alone properly.

Sometimes, this can get ambiguous. For example, N*m can be torgue (Nm) or energy (J). It mostly depends on which engineering field (mechanical, electrical, thermodynamical, etc.) is the problem. But we can add this as an option and after you select the desired field, you will always get the proper units for your job.

**Comment by HEA-sGuzman** [comment]
Thank you for the quick reply.  You are correct in regards to the units that is calculated my apologies for that.  I'm an electrical engineer and I am use to using Watts on a day to day basis.  I can provide you with the most commonly used formulas and units that would be helpful for someone like me.  
This software of yours looks very very promising and very powerful, I've just started looking for an alternative to Smath studio as I have been using this for 4-5 years but now I feel like i need more features that do not require me to have a subscription so thank you again for this project.
What would be the best way to provide you with the formulas and units?

**Comment by Proektsoftbg** [comment]
@HEA-sGuzman thank you so much! You can simply post them here (if they are not confidential ;) or you can send me an email to proektsoft.bg@gmail.com. Your contribution will be highly appresiated. :)

**Comment by hildebrandopsj** [comment]
> This software of yours looks very very promising and very powerful, I've just started looking for an alternative to Smath studio as I have been using this for 4-5 years but now I feel like i need more features that do not require me to have a subscription so thank you again for this project. 

@HEA-sGuzman i using Smath Studio for 10 years now, and i can say the calcpad is far superior to me because of some points:

1. It's **incridible fast and easy** to create good calculation with beautiful report's. We don't need to spend much time positioning text's and formulas.
2. We can made script's to see only the input's in the first moment, and after calculation we get a complete report.
3. It's DOCX, no more wasting hours to merge several PDF's (With not so good result's)

**Comment by HEA-sGuzman** [comment]
@Proektsoftbg 
Here is a list of some of the most common equations i use.  Its not as extensive as I would like but i've had limited time.  I hope this helps, Im really excited to use this software and great work so far it already looks very professional.
![20220912_EE_Units](https://user-images.githubusercontent.com/104866469/189722360-436a8f08-1f0e-4a4f-abae-ab3ae7fdafb0.png)

**Comment by Proektsoftbg** [comment]
Hi, thank you for the information. I think, I managed to implement almost all of the above conversions as default output units. Please, check the screenshot bellow:

![image](https://user-images.githubusercontent.com/90918363/190125784-4aa9fcd4-941c-4606-82b1-74bf79afb4a7.png)

I hope it is correct. Calcpad only cannot resolve ambiguous units (that are dimensionally equivalent), like:
Siemens (S) - Mho (℧) or W - VAR - VA. In such cases, only one of the equivalent units can be the default one. For the others, you will have to add vertical bar "|" conversion at the end. But I think this is not such a big trouble. :)

**Comment by cser** [comment]
Offtopic for @Proektsoftbg:
There are some trick: to use utf-8 characters `ᅟ` (U+115F) or `ᅠ` (U+1160) or `ㅤ` (U+3164) isteand of `&emsp;` to make code more readable, i.e.:
```
4A*2Ω'ᅟᅟ'4W/2A'ᅟᅟ'sqrt(4Ω*2W)
```

**Comment by Proektsoftbg** [comment]
Default electrical units are now available in the latest release:

https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.8.6

You can download and try them.

**Comment by hildebrandopsj** [comment]
> @cser thank you so much! I even didn't expect that Calcpad would accept that. There is always something new to learn. @hildebrandopsj you can add this to tips and tricks too.

Ok! I will start the wiki this week! ;) I need to finish a monstrous report

**Comment by HEA-sGuzman** [comment]
@Proektsoftbg This is awesome, the units look good.  As for the AC units thats ok, using the "|" define parameter will work just fine. Thank you again.
