### ISSUE TITLE
feature request: title syntax highlighting

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#62]
I just suggest improving readability of title comments. How about to make it bold with full-line background?
![image](https://user-images.githubusercontent.com/655339/189302318-05390212-ad9a-4d0d-9dc9-3e4032510bfc.png)

**Comment by Proektsoftbg** [comment]
Yes, it looks very good and it is also easy to implement. 

Thank you for this suggestion! I will include it in the next update.

**Comment by hildebrandopsj** [comment]
Good catch by @cser! I would just add the same feature with HTML titles ;)

**Comment by Proektsoftbg** [comment]
I added this in the new release:

https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.8.6

**Comment by hildebrandopsj** [comment]
Hi @Proektsoftbg it's hard to do the same with html titles?

**Comment by Proektsoftbg** [comment]
@hildebrandopsj I am not sure I understand what you mean: 
1. The same Calcpad titles, but in the output or
2. Titles in the source code that are Html: 
`'<h1>Title</h1>`

**Comment by hildebrandopsj** [comment]
Sorry, for that, but i mean the Titles in the source code that are Html

**Comment by Proektsoftbg** [comment]
This will be more difficult to do, because the content between tags is not currently parsed. I will try it for some other release. Titles with double quotes are a native Calcpad feature that comes from the calcpad language and they are parsed. I only had to add the decoration.

**Comment by hildebrandopsj** [comment]
OK! Leave it as it is, I won't die from it ;)

**Comment by Proektsoftbg** [comment]
@hildebrandopsj Thank you! I really hope so ;)
