### ISSUE TITLE
Resent files - missing files that opened by double click

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#66]
Files that opened with File→Open is shows in File→Resent Files menu, but if file was opened from OS by double mouse click - it doesn't showed in this menu.

**Comment by Proektsoftbg** [comment]
Thank you!

It is fixed in version 5.8.6:

https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.8.6

**Comment by cser** [comment]
Tested - Still doesn't remember opened by double click O_o

**Comment by cser** [comment]
> adding dobule-clicked files to resent list still doesn't 😮 - it doesn't show file inside resent list immediately after opening by double click and after restart CalcPad too.

**Comment by Proektsoftbg** [comment]
@cser  Now it must work for sure. I updated the release.

**Comment by cser** [comment]
> @Proektsoftbg: Thanks, now recent files works normally
