### ISSUE TITLE
Plotting function with min/max problem

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#69]
I try to plot:
```
$Plot{min(3; 14/(9*a)) @ a = 0.1 : 3}
```
But was: Unexpected error: Index was outside the bounds of the array. Please check the expression consistency.
This works correctly:
```
$Plot{14/(9*a)*(14/(9*a) ≤ 3) + 3*(14/(9*a) > 3) @ a = 0.1 : 3}
```
So, is it simple mistake or deep calculation problem?
`$Area` works nomally with this function, `$Integral` doesn't works too.

**Comment by cser** [comment]
@Proektsoftbg another one question:
Is it possible to make $Area shows as $Integral with ∫? It seems they don't really need to be distinguished in the output.

**Comment by Proektsoftbg** [comment]
OK. No problem, I will do it!

**Comment by Proektsoftbg** [comment]
@cser  Both are now fixed. You can download and resintall the latest release. Before that, uninstall the previous one.

**Comment by cser** [comment]
Yes! It works now.
