### ISSUE TITLE
link to download Notepad++.xml

### ISSUE THREAD

**Issue by xyont** [Proektsoftbg/Calcpad#7]
it seems the links to [download](http://calcpad.net/Download/Notepadpp.zip) is missing?

**Comment by Proektsoftbg** [comment]
Thank you for your feedback! 

I can see that it is still linked to the old website. Alternatively, you can find these files in our [GitHub repository](https://github.com/Proektsoftbg/Calcpad/tree/main/Setup/Syntax%20for%20Notepad%2B%2B), including the new awsome dark theme.

![image](https://user-images.githubusercontent.com/90918363/155109776-086c5fda-8038-4e06-b348-61ba2f2502bd.png)

I would also recommend to install the [RunMe](https://github.com/francostellari/NppPlugins/tree/main/RunMe) plugin by Franco Stellari. It allows you to run Calcpad programs directly from Notepad++. Detailed instructions how to install RunMe In Notepad++ are provided here: [install.txt](https://github.com/francostellari/NppPlugins/blob/main/install.txt).
