### ISSUE TITLE
Overlap in output

### ISSUE THREAD

**Issue by jgagnonNT** [Proektsoftbg/Calcpad#71]
Hello, it seems there is still some cases where the variable background overlaps and hide the division line in the output window.
Not a big deal but it can make it hard to read.
![image](https://user-images.githubusercontent.com/111089248/191589122-03796397-0765-4768-b963-311a8570ae03.png)
![image](https://user-images.githubusercontent.com/111089248/191589181-92d43992-2eb6-4b9b-80ca-3d28a8ca6436.png)

**Comment by Proektsoftbg** [comment]
Hi, I am sorry, but this are not new cases. It is my fault. Somehow I managed to replace back the old template. Now it is fixed, so, you can download the latest release and reinstall it. Uninstall the current version first, and make a clean install.
