### ISSUE TITLE
Missing function exp(x)

### ISSUE THREAD

**Issue by cser** [Proektsoftbg/Calcpad#77]
Many times I had to rewrite `exp(x)` to `e^x`. This is not the only problem. When the variable e is redefined in calculation - there are no beautiful ways to write the exponent.
P.S. It's possible, of cause to write my own exp(x)=2,718281828459045^x, but may be better to append it to standard functions

**Comment by Proektsoftbg** [comment]
How do you prefer `exp(x)` to be formatted in the output: as exp(x) or as e^x with x as superscript?

**Comment by cser** [comment]
Let it remains exp(x) in output

**Comment by Proektsoftbg** [comment]
OK, Great! 

Then, I am almost ready with all recent requests and will upload the new release today.

**Comment by Proektsoftbg** [comment]
Fixed in v5.8.8.
