### ISSUE TITLE
default apps when exports & opening Docx  

### ISSUE THREAD

**Issue by xyont** [Proektsoftbg/Calcpad#8]
every time i try to export in Docx, it seems the programs not only exporting but opening the files also. 

however, on my PC the default application to opening of file is not as in Windows setting. any hints?

**Comment by Proektsoftbg** [comment]
Hi,

What Calcpad does is just to start the document file. Then, it is up to Windows to decide which program to use. However, there is a simple way to set your default program:

Right click on any docx file an seelect "Open with" -> "Choose another app" from the dropdown menu.

![image](https://user-images.githubusercontent.com/90918363/155302261-e145157b-22ac-43ef-9d0f-dc75b7992ccf.png)

Then select the preferred application and check "Always use this app to open .docx files".

![image](https://user-images.githubusercontent.com/90918363/155301770-9e2c2854-6e2f-47f4-8581-41db3847ca60.png)

And that is all you need to do. The settings you have found are used for the web MIME types.

**Comment by xyont** [comment]
it's true, should be depending on Windows system setting. however this is not working, may the problem is specific to my pc.
