### ISSUE TITLE
different opening menue

### ISSUE THREAD

**Issue by hanneskoenig457** [Proektsoftbg/Calcpad#88]
### Discussed in https://github.com/Proektsoftbg/Calcpad/discussions/87

<div type='discussions-op-text'>

<sup>Originally posted by **hanneskoenig457** October 21, 2022</sup>
sometimes when I press Ctrl+O it returns this:

![image](https://user-images.githubusercontent.com/92821653/197135625-7283e0e0-0c60-46b7-afa6-00d258ff5ac6.png)

is this a kind of bug? it´s quite disturbing

</div>

**Comment by Proektsoftbg** [comment]
Thank you for posting this issuse. It is fixed now in the latest release: https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.8.9
