### ISSUE TITLE
Feature Request: New output control - show only equation and its result

### ISSUE THREAD

**Issue by FEA-eng** [Proektsoftbg/Calcpad#93]
Hi,

this software is really amazing. If I may suggest a small improvement, it would be great to add one more output control command that would enable the display of only the equation and the result, with no intermediate calculations.

For example, with the default settings I get:

`c = a + b = 2 m + 3 m = 5 m`

And I would like to get:

`c = a + b = 5 m`

It seems that the current output controls don't allow for this but please correct me if I'm wrong.

**Comment by Proektsoftbg** [comment]
Hi @FEA-eng,

Thank you for your kind words! You have to uncheck the "**Substitute**" checkbox on the bottom strip. Then, values are not substituted, but if you hover over a variable, the value will popup as a black tooltip.

![image](https://user-images.githubusercontent.com/90918363/198318845-acaf953f-c56e-4408-b9b1-6ebc3f2111ef.png)

**Comment by FEA-eng** [comment]
Great, thanks for the clarification :-)
