### ISSUE TITLE
Is it possible to display picewise function more intuitively

### ISSUE THREAD

**Issue by idealkindom** [Proektsoftbg/Calcpad#96]
There are some piecewise functions in self extracted examples of Calcpad.Still, they are displayed like f(x)=…·(x＜1)，where (x<1)defines its applicable zone for the factor.However, the output is not so manifest, eapecially when the function's pieces are many, thus making the output form of function too long.

I am wondering that is it possible to define a picewise function with "#if #else if …#else #end if"block, not only to make it more clearly, but also display more manifestly.

There is another problem incurring by present method of defining a many piecewise function, i.e.,Calcpad is very sensitive about whitespace before or after operators like "＋" etc., which makes it bug so often,while hard to find the trivial whitespace.

**Comment by Proektsoftbg** [comment]
It is interesting about the whitespace problem. It is supposed that whatever whitespace you enter, Calcpad to fix it automatically without giving errors. Can you please, provide some sample code.

About the piecewise functions, the examples are a bit old. Now, You can use if() and switch functions instead of  ·(x＜1). The simplest think that we can do to improve readibility is to allow functions to split on more lines like follows:
```
switch ( _
    x < 1;  y = 2; _
    x > 3;  y = 3; _
    x = 0;  y = 1; _
    y = 0 _
)
```

**Comment by Proektsoftbg** [comment]
Hi,

Line warping is not yet implemented. Probably it is not quite clear from my explanations. It just is an idea that came to me. If you like it, I can include it in the future releases.

**Comment by cser** [comment]
I like it (allowing line wrapping inside brackets).
I also had a need for a readable html display of switch
It's just an example, I don't use it because `switch2$(v; ...;. ..)` instead of `v = switch(...; ...)` hard to read:
```nginx
#def switch2$(v$; a_cond$; a$; b_cond$; b$)
	#hide
	v$ = switch(a_cond$; a$; b_cond$; b$)
	#show
	#noc
	'<table>
	'<tr><td style="vertical-align:middle">'v$'=</td>
	'<td style="vertical-align:middle">⎰<br/>⎱</td>
	'<td style="vertical-align:middle">
	'<table style="display:inline"> 
	'  <tr><td>'a$',</td><td>'a_cond$'</td></tr>
	'  <tr><td>'b$',</td><td>'b_cond$'</td></tr>
	'</table>
	#equ
	'</td><td style="vertical-align:middle">=
	#equ
	#if (a_cond$)
		'<span/>'a$
	#else if (b_cond$)
		'<span/>'b$
	#end if
	'</td></tr></table>
#end def

a = 5
v = switch(a ≤ 4; a + 20; a > 4; 2*sqrt(a) + 20)
switch2$(v; a ≤ 4; a + 20; a > 4; 2*sqrt(a) + 20)
```
![image](https://user-images.githubusercontent.com/655339/200743973-a2b10120-2efc-45cf-91c0-875f1d77a1fa.png)

**Comment by Proektsoftbg** [comment]
@cser Thank you for posting this macro. Great job and looks much better that way. I can embed this option inside Calcpad and provide native support for multiline switch display in the output.

**Comment by idealkindom** [comment]
> I like it (allowing line wrapping inside brackets). I also had a need for a readable html display of switch It's just an example, I don't use it because `switch2$(v; ...;. ..)` instead of `v = switch(...; ...)` hard to read:
> 
> ```nginx
> #def switch2$(v$; a_cond$; a$; b_cond$; b$)
> 	#hide
> 	v$ = switch(a_cond$; a$; b_cond$; b$)
> 	#show
> 	#noc
> 	'<table>
> 	'<tr><td style="vertical-align:middle">'v$'=</td>
> 	'<td style="vertical-align:middle">⎰<br/>⎱</td>
> 	'<td style="vertical-align:middle">
> 	'<table style="display:inline"> 
> 	'  <tr><td>'a$',</td><td>'a_cond$'</td></tr>
> 	'  <tr><td>'b$',</td><td>'b_cond$'</td></tr>
> 	'</table>
> 	#equ
> 	'</td><td style="vertical-align:middle">=
> 	#equ
> 	#if (a_cond$)
> 		'<span/>'a$
> 	#else if (b_cond$)
> 		'<span/>'b$
> 	#end if
> 	'</td></tr></table>
> #end def
> 
> a = 5
> v = switch(a ≤ 4; a + 20; a > 4; 2*sqrt(a) + 20)
> switch2$(v; a ≤ 4; a + 20; a > 4; 2*sqrt(a) + 20)
> ```
> 
> ![image](https://user-images.githubusercontent.com/655339/200743973-a2b10120-2efc-45cf-91c0-875f1d77a1fa.png)

Awesome, so cool.That's what I wanted.Thanks a lot.

**Comment by idealkindom** [comment]
> I like it (allowing line wrapping inside brackets). I also had a need for a readable html display of switch It's just an example, I don't use it because `switch2$(v; ...;. ..)` instead of `v = switch(...; ...)` hard to read:
> 
> ```nginx
> #def switch2$(v$; a_cond$; a$; b_cond$; b$)
> 	#hide
> 	v$ = switch(a_cond$; a$; b_cond$; b$)
> 	#show
> 	#noc
> 	'<table>
> 	'<tr><td style="vertical-align:middle">'v$'=</td>
> 	'<td style="vertical-align:middle">⎰<br/>⎱</td>
> 	'<td style="vertical-align:middle">
> 	'<table style="display:inline"> 
> 	'  <tr><td>'a$',</td><td>'a_cond$'</td></tr>
> 	'  <tr><td>'b$',</td><td>'b_cond$'</td></tr>
> 	'</table>
> 	#equ
> 	'</td><td style="vertical-align:middle">=
> 	#equ
> 	#if (a_cond$)
> 		'<span/>'a$
> 	#else if (b_cond$)
> 		'<span/>'b$
> 	#end if
> 	'</td></tr></table>
> #end def
> 
> a = 5
> v = switch(a ≤ 4; a + 20; a > 4; 2*sqrt(a) + 20)
> switch2$(v; a ≤ 4; a + 20; a > 4; 2*sqrt(a) + 20)
> ```
> 
> ![image](https://user-images.githubusercontent.com/655339/200743973-a2b10120-2efc-45cf-91c0-875f1d77a1fa.png)

How about trying to define a 3 or more piecewise function,.i.e., the condition for switch ievitably include some region with both lower and higher bound.

**Comment by idealkindom** [comment]
> @cser Thank you for posting this macro. Great job and looks much better that way. I can embed this option inside Calcpad and provide native support for multiline switch display in the output.

how about considering to.merge this.into Calcpad？

**Comment by Proektsoftbg** [comment]
@idealkindom, yes, I am definitely considering both options:

1. To add manual line breaks " _" improve source code readibility and
2. To add stacking of switch options in the output as per @cser's macro.

It will be available soon in some of the next updates. :)

**Comment by idealkindom** [comment]
> It is interesting about the whitespace problem. It is supposed that whatever whitespace you enter, Calcpad to fix it automatically without giving errors. Can you please, provide some sample code.
> 
> About the piecewise functions, the examples are a bit old. Now, You can use if() and switch functions instead of ·(x＜1). The simplest think that we can do to improve readibility is to allow functions to split on more lines like follows:
> 
> ```
> switch ( _
>     x < 1;  y = 2; _
>     x > 3;  y = 3; _
>     x = 0;  y = 1; _
>     y = 0 _
> )
> ```

Hi, Ned. I sugeest to mergre built functions of if() and switch(),.and show the piecewise functions with cser's method.

**Comment by cser** [comment]
> @idealkindom, yes, I am definitely considering both options:
> 
> 1. To add manual line breaks " _" improve source code readibility and
> 2. To add stacking of switch options in the output as per @cser's macro.
> 
> It will be available soon in some of the next updates. :) It is in my task list.

The manual line breaks " _" is bed idea - Python is line-dependent too, but it allow to insert line breaks inside brackets ( )
https://stackoverflow.com/questions/53162/how-can-i-do-a-line-break-line-continuation-in-python

**Comment by Proektsoftbg** [comment]
Without manual line breaks Calcpad will not know if it is simply a missed bracket (syntax error) or line brakes inside brackets. So, the parser will have to do a lot of forward scans trying to continue the unfinished expression somehow. Probably it will stop at the end of the code or at a line where right brackets are more than left ones by accident. This will make this otherwise lightweight and fast parser unnecessary heavier and complicated. Although it is possible, Python codding style guidelines recommend using the explicit line continuation.

It also think that it is a good style for the user to explicitly specify that he/she wants to extent the expression on several lines. This will avoid accidental errors with unmatched brackets.

**Comment by hildebrandopsj** [comment]
@Proektsoftbg,

I suggest using the \\, like we use in LaTex.



Em ter., 21 de fev. de 2023 07:28, Ned Ganchovski ***@***.***>
escreveu:

**Comment by cser** [comment]
> Python codding style guidelines recommend using the explicit line continuation
It's surprise for me O_o. Okey.

**Comment by Proektsoftbg** [comment]
I am sorry, my mistake. For Python, it is exactly the opposite as I said: Implicit line continuation is recommended, not explicit (with \).
However, for me it will be difficult now to make it parse that. Calcpad is not Python. :) Another option is to use Shift + Enter = manual line break. Currently, it is supported by the editor, but not by the parser:

![image](https://user-images.githubusercontent.com/90918363/220894264-ee17e806-2627-4b28-a9b6-57fc241b9ab3.png)

I can easily make the parser to support it as well and no special symbol will be required.

**Comment by Proektsoftbg** [comment]
Figure display of conditional functions was added in the latest release:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.9.7

![image](https://user-images.githubusercontent.com/90918363/224173428-59124550-f280-448c-b591-2d84a6cbc710.png)

**Comment by Proektsoftbg** [comment]
I fixed some issues with this and made the curly bracket a bit smaller:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.9.8

**Comment by idealkindom** [comment]
> made the curly bracket a bit smaller:

Phantastic job.

**Comment by idealkindom** [comment]
> Figure display of conditional functions was added in the latest release: https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.9.7
> 
> ![image](https://user-images.githubusercontent.com/90918363/224173428-59124550-f280-448c-b591-2d84a6cbc710.png)

Since coming here, I want to come up with a request for your consideration,i.e., let mutiple factor functions to be displayed  in a more mathematical way. For example, we define f(x;y)=sin(x)*cos(x), I hope in the output window the result might be f(x,y)=sin(x)*cos(x), instead of f(x;y)

**Comment by idealkindom** [comment]
> Figure display of conditional functions was added in the latest release: https://github.com/Proektsoftbg/Calcpad/releases/tag/v5.9.7
> 
> ![image](https://user-images.githubusercontent.com/90918363/224173428-59124550-f280-448c-b591-2d84a6cbc710.png)

One more thing is that letting domain of definition behind the function might be better.like:
![image](https://user-images.githubusercontent.com/18344868/226400276-4deb3247-cc61-44f5-917b-edbb1de6c066.png)
